# Step 4 - Model Development

**Baseline: SARIMAX with exogenous regressors.**

Cleaned dataset only - no engineered features.

Metrics are MAPE and RMSE per the brief, with WAPE alongside because MAPE is
undefined on zero-consumption days (12.2% of rows). Selection is on the validation
split; the test period is not touched.

In [1]:
import sys
from pathlib import Path

# Project root
PROJECT_ROOT = Path.cwd().parent

# Add src folder to Python path
sys.path.insert(0, str(PROJECT_ROOT / "src"))

print("Project Root:", PROJECT_ROOT)

Project Root: c:\Users\Olami\OneDrive\Documents\DATASCIENCEPROJECT\MIG_Cement_Demand_Forecasting

In [2]:
import warnings

import numpy as np
import pandas as pd
from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.tsa.stattools import adfuller

from mig_cement.config import settings

warnings.filterwarnings("ignore")
pd.set_option("display.width", 170)
pd.set_option("display.max_columns", 30)

TRAIN_END, VAL_END = "2024-06-30", "2024-09-30"
TARGET = "y"
HORIZON_WEEKS = 8   # the forecast horizon the brief specifies

## 1. Load the cleaned dataset

In [3]:
clean = pd.read_parquet(settings.interim_dir / "operations_clean.parquet")
clean["date"] = pd.to_datetime(clean["date"])
clean = clean.sort_values(["site_id", "date"]).reset_index(drop=True)

print("shape:", clean.shape)
print("sites:", clean.site_id.nunique(), "| dates:", clean.date.nunique())
print("range:", clean.date.min().date(), "->", clean.date.max().date())

shape: (32880, 22)
sites: 30 | dates: 1096
range: 2022-01-01 -> 2024-12-31

## 2. Handle NaNs

Rows with NaN are removed, scoped to the columns this model uses.

A blanket `dropna()` would be a trap: `cover_days` is NaN exactly where
`consumed_tonnes == 0`, so it silently deletes every zero-consumption day - the
rain-blocked pours and stockouts, which are the hard cases.

In [4]:
print("NaN counts:")
print(clean.isna().sum()[lambda s: s > 0].to_string())
print("\nblanket dropna would give:", clean.dropna().shape,
      f"({100*(1-len(clean.dropna())/len(clean)):.1f}% lost)")
print("  zero-y rows before:", int((clean[TARGET] == 0).sum()),
      "| after:", int((clean.dropna()[TARGET] == 0).sum()))

NaN counts:
cover_days    4003

blanket dropna would give: (28877, 22) (12.2% lost)
  zero-y rows before: 4003 | after: 0

In [5]:
EXOG = ["planned_pour_tonnes", "rain_mm", "avg_temp_c", "opening_inventory_tonnes"]

before = len(clean)
clean = clean.dropna(subset=[TARGET] + EXOG).reset_index(drop=True)
print(f"rows: {before:,} -> {len(clean):,}")
print(f"zero-y rows retained: {int((clean[TARGET] == 0).sum()):,} "
      f"({(clean[TARGET] == 0).mean():.1%})")

rows: 32,880 -> 32,880
zero-y rows retained: 4,003 (12.2%)

### Why these four regressors

Of the 22 columns in the cleaned panel, most cannot be used:

- **target-derived / leaky**: `consumed_tonnes`, `served_tonnes`,
  `closing_inventory_tonnes`, `cover_days`, `silo_utilisation`, `was_constrained`,
  `unmet_tonnes`, `induced_shortfall`
- **not knowable at forecast time**: `deliveries_tonnes`, `received_tonnes`,
  `rejected_delivery_tonnes`
- **constant within each site**: `silo_capacity`, `region`, `behavior` - models are
  fitted per site, so these have no within-series variance and are collinear with
  the intercept
- **keys**: `date`, `site_id`, `cement_type`

## 3. Train / validation / test split

Chronological. The test period is held back.

In [6]:
d = clean["date"]
train = clean[d <= TRAIN_END]
val = clean[(d > TRAIN_END) & (d <= VAL_END)]
test = clean[d > VAL_END]

for name, part in [("train", train), ("val", val), ("test", test)]:
    print(f"{name:6s} {len(part):6,} rows  {part.date.min().date()} -> {part.date.max().date()}")

train  27,360 rows  2022-01-01 -> 2024-06-30
val     2,760 rows  2024-07-01 -> 2024-09-30
test    2,760 rows  2024-10-01 -> 2024-12-31

## 4. Model configuration

`d = 0` because the series are stationary. `seasonal_order = (0,0,0,0)` because
Step 3 tested weekly, monthly and annual seasonality per region against a shuffled
null and found none - seasonal terms would fit noise.

In [7]:
adf = pd.Series({s: adfuller(g[TARGET])[1] for s, g in clean.groupby("site_id")})
print(f"ADF p-values across {len(adf)} sites: max = {adf.max():.2e}")
print(f"sites rejecting a unit root at 1%: {(adf < 0.01).sum()} / {len(adf)}")
print("\n-> d = 0")

ADF p-values across 30 sites: max = 3.61e-17
sites rejecting a unit root at 1%: 30 / 30

-> d = 0

In [8]:
# order chosen by mean AIC across a sample of sites
GRID = [(1, 0, 0), (0, 0, 1), (1, 0, 1), (2, 0, 1), (2, 0, 2)]
aic = {}
for o in GRID:
    scores = []
    for site in sorted(train.site_id.unique())[:5]:
        g = train[train.site_id == site].set_index("date")
        try:
            scores.append(SARIMAX(g[TARGET], exog=g[EXOG], order=o,
                                  seasonal_order=(0, 0, 0, 0)).fit(disp=False).aic)
        except Exception:
            pass
    aic[str(o)] = np.mean(scores)

aic = pd.Series(aic).sort_values()
print(aic.round(1).to_string())
ORDER = (2, 0, 2)
print("\nselected:", ORDER)

(2, 0, 2)    4979.0
(2, 0, 1)    4984.3
(1, 0, 1)    4984.7
(1, 0, 0)    4985.9
(0, 0, 1)    4986.2

selected: (2, 0, 2)

## 5. Train the model

Fitted on one site first, in the plainest form.

In [9]:
SITE = "SITE_001"

y_train = train[train.site_id == SITE].set_index("date")[TARGET]
x_train = train[train.site_id == SITE].set_index("date")[EXOG]
y_val = val[val.site_id == SITE].set_index("date")[TARGET]
x_val = val[val.site_id == SITE].set_index("date")[EXOG]

print(f"{SITE}: train {y_train.shape[0]} rows, val {y_val.shape[0]} rows, "
      f"{x_train.shape[1]} exogenous regressors")

SITE_001: train 912 rows, val 92 rows, 4 exogenous regressors

In [10]:
model = SARIMAX(
    y_train,
    exog=x_train,
    order=ORDER,
    seasonal_order=(0, 0, 0, 0),
    enforce_stationarity=True,
)

results = model.fit(disp=False)
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  912
Model:               SARIMAX(2, 0, 2)   Log Likelihood               -3488.121
Date:                Mon, 10 Aug 2026   AIC                           6994.243
Time:                        15:41:21   BIC                           7037.584
Sample:                    01-01-2022   HQIC                          7010.789
                         - 06-30-2024
Covariance Type:                  opg
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
planned_pour_tonnes          0.6497      0.017     37.581      0.000       0.616       0.684
rain_mm                     -0.7636      0.054    -14.242      0.000      -0.869      -0.659
avg_temp_c                   0.1877      0.047      3.964      0.000       0.095       0.281
opening_inventory_tonnes     0.2729      0.020     13.435      0.000       0.233       0.313
ar.L1                        0.5998      1.215      0.494      0.622      -1.782       2.982
ar.L2                        0.2455      1.007      0.244      0.807      -1.729       2.220
ma.L1                       -0.5354      1.210     -0.443      0.658      -2.906       1.835
ma.L2                       -0.2606      0.941     -0.277      0.782      -2.104       1.583
sigma2                     123.0795      7.080     17.384      0.000     109.203     136.956
===================================================================================
Ljung-Box (L1) (Q):                   0.03   Jarque-Bera (JB):                60.37
Prob(Q):                              0.86   Prob(JB):                         0.00
Heteroskedasticity (H):               1.03   Skew:                            -0.63
Prob(H) (two-sided):                  0.82   Kurtosis:                         2.96
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

`enforce_stationarity=True` is deliberate. With it set to `False`, an unstable
AR root produced forecasts that diverged across the 92-day validation window -
one site reached an RMSE of 1.96e20. The series are stationary, so the constraint
costs nothing.

## 6. Predict

`y_val` / `X_val` below are the **validation** window (Jul-Sep 2024).
Oct-Dec 2024 stays held back and is not touched in this notebook.

In [11]:
y_pred = results.predict(start=y_val.index[0], end=y_val.index[-1], exog=x_val)
y_pred = y_pred.clip(lower=0)
y_pred

2024-07-01    29.360762
2024-07-02    22.727009
2024-07-03    36.482205
2024-07-04    32.125752
2024-07-05    39.117189
                ...
2024-09-26    36.900146
2024-09-27    34.793075
2024-09-28    29.244377
2024-09-29    39.149281
2024-09-30    37.968556
Freq: D, Name: predicted_mean, Length: 92, dtype: float64

## 7. Metrics

`sklearn.metrics.mean_absolute_percentage_error` returns a **fraction, not a
percentage** - a returned value of 15 means 1500%, not 15%.

It is also undefined when the actual is zero. 12.2% of site-days have no pour, and
on those rows sklearn divides by a tiny epsilon, so a handful of rows can dominate
the whole average. MAPE is therefore computed on non-zero actuals only, with the
raw sklearn figure shown alongside so the gap is visible.

In [12]:
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error

nz = y_val != 0

mape_raw = mean_absolute_percentage_error(y_val, y_pred)
mape_nonzero = mean_absolute_percentage_error(y_val[nz], y_pred[nz])
rmse = np.sqrt(mean_squared_error(y_val, y_pred))

print(f"{SITE}")
print(f"  zero-actual days      {int((~nz).sum())} of {len(y_val)}")
print(f"  MAPE (sklearn raw)    {mape_raw:.4f}  = {mape_raw*100:,.0f}%")
print(f"  MAPE (non-zero only)  {mape_nonzero:.4f}  = {mape_nonzero*100:.1f}%")
print(f"  RMSE                  {rmse:.3f} t")

SITE_001
  zero-actual days      16 of 92
  MAPE (sklearn raw)    9531950198781162.0000  = 953,195,019,878,116,224%
  MAPE (non-zero only)  0.2595  = 26.0%
  RMSE                  10.755 t

## 8. Fit all 30 sites and predict

In [13]:
models, preds = {}, []

for site, g_tr in train.groupby("site_id"):
    g_tr = g_tr.set_index("date")
    g_te = val[val.site_id == site].sort_values("date").set_index("date")

    y_tr, X_tr = g_tr[TARGET], g_tr[EXOG]
    y_te, X_te = g_te[TARGET], g_te[EXOG]

    try:
        res = SARIMAX(
            y_tr,
            exog=X_tr,
            order=ORDER,
            seasonal_order=(0, 0, 0, 0),
            enforce_stationarity=True,
        ).fit(disp=False)
        pred = res.predict(start=y_te.index[0], end=y_te.index[-1], exog=X_te).clip(lower=0)
    except Exception:
        res, pred = None, pd.Series(np.nan, index=y_te.index)

    models[site] = res
    preds.append(pd.DataFrame({"date": y_te.index, "site_id": site,
                               "actual": y_te.values, "pred": pred.values}))

fc = pd.concat(preds, ignore_index=True).dropna(subset=["pred"])
converged = sum(m is not None for m in models.values())
print(f"sites: {len(models)} | converged: {converged} | failed: {len(models) - converged}")
print(f"{len(fc):,} predictions | {fc.date.nunique()} dates x {fc.site_id.nunique()} sites")

sites: 30 | converged: 30 | failed: 0
2,760 predictions | 92 dates x 30 sites

## 9. Daily error, per site

One row per site-day: absolute error, squared error, and percentage error where the
actual is non-zero.

In [14]:
fc["abs_err"] = (fc.actual - fc.pred).abs()
fc["sq_err"] = (fc.actual - fc.pred) ** 2
fc["pct_err"] = np.where(fc.actual != 0, fc.abs_err / fc.actual, np.nan)

print(f"{len(fc):,} site-days | {fc.pct_err.isna().sum():,} with zero actual (no MAPE)")
fc.head(10).round(3)

2,760 site-days | 331 with zero actual (no MAPE)

        date   site_id  actual    pred  abs_err   sq_err  pct_err
0 2024-07-01  SITE_001   26.75  29.361    2.611    6.816    0.098
1 2024-07-02  SITE_001   22.51  22.727    0.217    0.047    0.010
2 2024-07-03  SITE_001   15.48  36.482   21.002  441.093    1.357
3 2024-07-04  SITE_001   44.07  32.126   11.944  142.665    0.271
4 2024-07-05  SITE_001   40.07  39.117    0.953    0.908    0.024
5 2024-07-06  SITE_001   30.06  17.259   12.801  163.856    0.426
6 2024-07-07  SITE_001    0.00   0.000    0.000    0.000      NaN
7 2024-07-08  SITE_001   35.45  30.025    5.425   29.426    0.153
8 2024-07-09  SITE_001   38.26  32.267    5.993   35.916    0.157
9 2024-07-10  SITE_001   14.56  33.081   18.521  343.013    1.272

In [15]:
per_site = pd.DataFrame({
    "n_days": fc.groupby("site_id").size(),
    "zero_days": fc.groupby("site_id").pct_err.apply(lambda s: int(s.isna().sum())),
    "mean_actual": fc.groupby("site_id").actual.mean(),
    "MAPE": fc.groupby("site_id").pct_err.mean(),
    "RMSE": fc.groupby("site_id").sq_err.mean() ** 0.5,
}).sort_values("MAPE", ascending=False)

print(f"MAPE across sites: best {per_site.MAPE.min():.1%} | "
      f"median {per_site.MAPE.median():.1%} | worst {per_site.MAPE.max():.1%}")
per_site.round(4)

MAPE across sites: best 6.3% | median 25.0% | worst 42.7%

          n_days  zero_days  mean_actual    MAPE     RMSE
site_id
SITE_017      92          8      28.1239  0.4273  12.5276
SITE_030      92          7      29.1316  0.3880  10.4852
SITE_025      92          7      30.8111  0.3872  11.8301
SITE_021      92          9      28.7862  0.3827  10.2459
SITE_010      92          4      30.0573  0.3704  10.6331
SITE_018      92          6      29.5473  0.3676  10.6119
SITE_022      92          8      29.5374  0.3613  10.6968
SITE_008      92         13      28.3165  0.3610  10.8089
SITE_006      92         19      25.7420  0.3145  10.8766
SITE_016      92         23      25.3807  0.2977  12.3412
SITE_003      92         10      29.9430  0.2888   9.8186
SITE_020      92          9      29.5273  0.2606   9.6457
SITE_001      92         16      29.0104  0.2595  10.7549
SITE_011      92          4      30.4378  0.2593  10.0182
SITE_007      92         12      30.3996  0.2559  10.3240
SITE_014      92         22      27.1127  0.2446  10.9871
SITE_005      92         15      30.7698  0.2241  10.9994
SITE_028      92         25      25.4123  0.1616   5.8225
SITE_026      92         20      32.3905  0.1598   7.2808
SITE_024      92         28      25.8827  0.1452  10.1078
SITE_013      92         25      26.3252  0.1388   5.9570
SITE_015      92          3      11.3630  0.0759   1.0118
SITE_012      92          6      10.9359  0.0758   1.0009
SITE_004      92          3      10.5129  0.0757   0.9750
SITE_002      92          3      11.4060  0.0749   0.9148
SITE_019      92          8      10.7532  0.0743   1.0113
SITE_023      92          5      10.6533  0.0740   1.0021
SITE_009      92          3      11.0623  0.0739   0.9871
SITE_029      92          7      11.0157  0.0671   0.9145
SITE_027      92          3      11.6418  0.0627   0.9465

## 10. Daily error, per calendar date across all sites

In [16]:
per_day = pd.DataFrame({
    "n_sites": fc.groupby("date").size(),
    "zero_sites": fc.groupby("date").pct_err.apply(lambda s: int(s.isna().sum())),
    "mean_actual": fc.groupby("date").actual.mean(),
    "mean_pred": fc.groupby("date").pred.mean(),
    "MAPE": fc.groupby("date").pct_err.mean(),
    "RMSE": fc.groupby("date").sq_err.mean() ** 0.5,
})

print(f"{len(per_day)} days | MAPE best {per_day.MAPE.min():.1%} | "
      f"median {per_day.MAPE.median():.1%} | worst {per_day.MAPE.max():.1%}")
per_day.round(4)

92 days | MAPE best 12.7% | median 21.8% | worst 42.6%

            n_sites  zero_sites  mean_actual  mean_pred    MAPE     RMSE
date
2024-07-01       30           4      25.9203    24.6203  0.1826   7.8758
2024-07-02       30           5      21.3010    22.6587  0.2188   7.1987
2024-07-03       30           4      24.4493    22.6018  0.1625   7.1571
2024-07-04       30           3      26.7497    24.0101  0.1561   7.4589
2024-07-05       30           4      22.8220    21.0906  0.2011   8.5433
...             ...         ...          ...        ...     ...      ...
2024-09-26       30           1      25.2933    23.3640  0.2444   8.4147
2024-09-27       30           4      18.4490    20.0372  0.3022   7.4022
2024-09-28       30           7      16.0650    20.5007  0.3233  10.4289
2024-09-29       30           2      26.2260    26.0981  0.2412   9.1938
2024-09-30       30           8      16.6353    17.9478  0.2771   7.9204

[92 rows x 6 columns]

In [17]:
per_day_h = per_day.reset_index()
per_day_h["horizon_day"] = np.arange(1, len(per_day_h) + 1)
per_day_h["week"] = ((per_day_h.horizon_day - 1) // 7) + 1

by_week = per_day_h.groupby("week").agg(
    days=("horizon_day", "size"), MAPE=("MAPE", "mean"), RMSE=("RMSE", "mean")).head(8)
print("error by forecast week (the 8-week horizon in the brief):")
by_week.round(4)

error by forecast week (the 8-week horizon in the brief):

      days    MAPE    RMSE
week
1        7  0.1808  7.3404
2        7  0.2165  7.7284
3        7  0.2028  7.7261
4        7  0.2224  9.0576
5        7  0.2307  8.7413
6        7  0.2288  8.9349
7        7  0.2780  9.9024
8        7  0.2115  8.2256

## 11. Overall, against baselines

In [18]:
def score(y_true, y_pred_):
    y_true, y_pred_ = np.asarray(y_true, float), np.asarray(y_pred_, float)
    nzm = y_true != 0
    return {
        "MAPE": mean_absolute_percentage_error(y_true[nzm], y_pred_[nzm]),
        "RMSE": np.sqrt(mean_squared_error(y_true, y_pred_)),
        "WAPE": np.abs(y_true - y_pred_).sum() / np.abs(y_true).sum(),
        "MAE": np.abs(y_true - y_pred_).mean(),
        "bias": (y_pred_ - y_true).mean(),
    }


rows = [
    {**score(val[TARGET], val["planned_pour_tonnes"]), "model": "baseline: planned_pour"},
    {**score(val[TARGET], np.full(len(val), train[TARGET].mean())), "model": "baseline: train mean"},
    {**score(fc.actual, fc.pred), "model": "SARIMAX (cleaned data)"},
]
results_tbl = pd.DataFrame(rows).set_index("model")[["MAPE", "RMSE", "WAPE", "MAE", "bias"]]
results_tbl.round(4)

                          MAPE     RMSE    WAPE      MAE    bias
model
baseline: planned_pour  0.3372  14.4142  0.3189   7.4622  7.4622
baseline: train mean    0.7077  16.6324  0.6094  14.2586  0.3923
SARIMAX (cleaned data)  0.2227   8.6144  0.2464   5.7660 -0.0270

---

# Experiment 2 - Weekly Aggregation

Same cleaned dataset, same regressors, same model. The only change is the grain:
each site-day is aggregated to a site-week.

Consumption and planned pour are **summed**, weather is **averaged**, and opening
inventory takes the **first** value of the week.

In [19]:
AGG = {
    "y": "sum",
    "planned_pour_tonnes": "sum",
    "rain_mm": "mean",
    "avg_temp_c": "mean",
    "opening_inventory_tonnes": "first",
}

grp = clean.set_index("date").groupby("site_id").resample("W")
weekly = grp.agg(AGG).reset_index()
weekly["n_days"] = grp.size().values

# Drop partial weeks. resample("W") opens and closes the series with buckets that
# hold fewer than 7 days - the final one covers only 30-31 Dec, and averages 49.5 t
# against 162.6 t for a full week. Left in, it reads as a demand collapse.
partial = weekly.n_days < 7
print(f"partial weeks dropped: {partial.sum()} of {len(weekly)}")
print(weekly.loc[partial, ["date", "n_days", "y"]].groupby("date")
             .agg(sites=("n_days", "size"), days=("n_days", "first"),
                  mean_y=("y", "mean")).round(1).to_string())

weekly = (weekly[~partial]
          .drop(columns="n_days")
          .dropna(subset=["y"])
          .sort_values(["site_id", "date"])
          .reset_index(drop=True))

print("\ndaily :", clean.shape, "| mean y", round(clean.y.mean(), 2), "t",
      "| zero rows", f"{(clean.y == 0).mean():.1%}")
print("weekly:", weekly.shape, "| mean y", round(weekly.y.mean(), 2), "t",
      "| zero rows", f"{(weekly.y == 0).mean():.1%}")
weekly.head()

partial weeks dropped: 60 of 4740
            sites  days  mean_y
date
2022-01-02     30     2    60.8
2025-01-05     30     2    49.5

daily : (32880, 22) | mean y 23.72 t | zero rows 12.2%
weekly: (4680, 7) | mean y 165.94 t | zero rows 0.0%

    site_id       date       y  planned_pour_tonnes   rain_mm  avg_temp_c  opening_inventory_tonnes
0  SITE_001 2022-01-09  208.96               234.47  2.734286   13.060000                     38.56
1  SITE_001 2022-01-16  269.66               286.58  3.372857   11.337143                     34.38
2  SITE_001 2022-01-23  235.01               346.98  3.258571   12.935714                      4.95
3  SITE_001 2022-01-30  235.11               341.55  7.021429   12.470000                      7.22
4  SITE_001 2022-02-06  196.26               307.16  4.274286   17.685714                      3.59

Aggregation removes the zero-consumption problem entirely: no site goes a full
week without pouring, so MAPE becomes well-defined on every row.

## Split

In [20]:
dw = weekly["date"]
train_w = weekly[dw <= TRAIN_END]
val_w = weekly[(dw > TRAIN_END) & (dw <= VAL_END)]
test_w = weekly[dw > VAL_END]

# The brief asks for forecasts up to 8 weeks ahead, so scoring is capped at that
# horizon. Beyond it the model is being judged on something it does not promise.
val_w = val_w.groupby("site_id").head(HORIZON_WEEKS).reset_index(drop=True)
test_w = test_w.groupby("site_id").head(HORIZON_WEEKS).reset_index(drop=True)

for name, part in [("train", train_w), ("val", val_w), ("test", test_w)]:
    print(f"{name:6s} {len(part):5,} rows  {part.date.min().date()} -> {part.date.max().date()}"
          f"  ({part.groupby('site_id').size().mean():.0f} weeks per site)")

train  3,900 rows  2022-01-09 -> 2024-06-30  (130 weeks per site)
val      240 rows  2024-07-07 -> 2024-08-25  (8 weeks per site)
test     240 rows  2024-10-06 -> 2024-11-24  (8 weeks per site)

## Order selection

In [21]:
aic_w = {}
for o in GRID:
    scores = []
    for site in sorted(train_w.site_id.unique())[:5]:
        g = train_w[train_w.site_id == site].set_index("date").asfreq("W")
        try:
            scores.append(SARIMAX(g[TARGET], exog=g[EXOG], order=o,
                                  seasonal_order=(0, 0, 0, 0)).fit(disp=False).aic)
        except Exception:
            pass
    aic_w[str(o)] = np.mean(scores) if scores else np.nan

aic_w = pd.Series(aic_w).sort_values()
print(aic_w.round(1).to_string())
ORDER_W = eval(aic_w.index[0])
print("\nselected:", ORDER_W)

(2, 0, 2)     991.1
(1, 0, 1)     992.7
(1, 0, 0)     995.1
(0, 0, 1)     997.4
(2, 0, 1)    1210.6

selected: (2, 0, 2)

## Train the model

In [22]:
y_train_w = train_w[train_w.site_id == SITE].set_index("date").asfreq("W")[TARGET]
x_train_w = train_w[train_w.site_id == SITE].set_index("date").asfreq("W")[EXOG]
y_val_w = val_w[val_w.site_id == SITE].set_index("date").asfreq("W")[TARGET]
x_val_w = val_w[val_w.site_id == SITE].set_index("date").asfreq("W")[EXOG]

print(f"{SITE}: train {len(y_train_w)} weeks, val {len(y_val_w)} weeks")

SITE_001: train 130 weeks, val 8 weeks

In [23]:
model_w = SARIMAX(
    y_train_w,
    exog=x_train_w,
    order=ORDER_W,
    seasonal_order=(0, 0, 0, 0),
    enforce_stationarity=True,
)

results_w = model_w.fit(disp=False)
results_w.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  130
Model:               SARIMAX(2, 0, 2)   Log Likelihood                -631.374
Date:                Mon, 10 Aug 2026   AIC                           1280.749
Time:                        15:41:48   BIC                           1306.557
Sample:                    01-09-2022   HQIC                          1291.235
                         - 06-30-2024
Covariance Type:                  opg
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
planned_pour_tonnes          0.6488      0.027     23.953      0.000       0.596       0.702
rain_mm                     -0.9474      1.272     -0.745      0.456      -3.440       1.545
avg_temp_c                   0.4889      0.386      1.268      0.205      -0.267       1.245
opening_inventory_tonnes     1.0737      0.119      9.007      0.000       0.840       1.307
ar.L1                        0.8700      0.076     11.404      0.000       0.720       1.019
ar.L2                       -0.7918      0.083     -9.535      0.000      -0.955      -0.629
ma.L1                       -1.0578      0.946     -1.118      0.264      -2.913       0.797
ma.L2                        0.9988      1.788      0.558      0.577      -2.506       4.504
sigma2                     932.1764   1624.986      0.574      0.566   -2252.738    4117.091
===================================================================================
Ljung-Box (L1) (Q):                   0.25   Jarque-Bera (JB):                 1.10
Prob(Q):                              0.62   Prob(JB):                         0.58
Heteroskedasticity (H):               1.06   Skew:                            -0.21
Prob(H) (two-sided):                  0.85   Kurtosis:                         2.85
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

## Predict

In [24]:
y_pred_w = results_w.predict(start=y_val_w.index[0], end=y_val_w.index[-1], exog=x_val_w)
y_pred_w = y_pred_w.clip(lower=0)

print(f"{SITE}")
print(f"  MAPE {mean_absolute_percentage_error(y_val_w, y_pred_w):.4f}"
      f"  = {mean_absolute_percentage_error(y_val_w, y_pred_w)*100:.1f}%")
print(f"  RMSE {np.sqrt(mean_squared_error(y_val_w, y_pred_w)):.3f} t")
y_pred_w

SITE_001
  MAPE 0.1385  = 13.8%
  RMSE 33.844 t

2024-07-07    179.692574
2024-07-14    238.775067
2024-07-21    159.514327
2024-07-28    224.081820
2024-08-04    239.884778
2024-08-11    259.208129
2024-08-18    221.244421
2024-08-25    174.479466
Freq: W-SUN, Name: predicted_mean, dtype: float64

## Fit all 30 sites

In [25]:
models_w, preds_w = {}, []

for site, g_tr in train_w.groupby("site_id"):
    g_tr = g_tr.set_index("date").asfreq("W")
    g_te = val_w[val_w.site_id == site].sort_values("date").set_index("date").asfreq("W")

    try:
        res = SARIMAX(
            g_tr[TARGET],
            exog=g_tr[EXOG],
            order=ORDER_W,
            seasonal_order=(0, 0, 0, 0),
            enforce_stationarity=True,
        ).fit(disp=False)
        pred = res.predict(start=g_te.index[0], end=g_te.index[-1],
                           exog=g_te[EXOG]).clip(lower=0)
    except Exception:
        res, pred = None, pd.Series(np.nan, index=g_te.index)

    models_w[site] = res
    preds_w.append(pd.DataFrame({"date": g_te.index, "site_id": site,
                                 "actual": g_te[TARGET].values, "pred": pred.values}))

fc_w = pd.concat(preds_w, ignore_index=True).dropna(subset=["pred"])
converged_w = sum(m is not None for m in models_w.values())
print(f"sites: {len(models_w)} | converged: {converged_w} | failed: {len(models_w) - converged_w}")
print(f"{len(fc_w):,} predictions | {fc_w.date.nunique()} weeks x {fc_w.site_id.nunique()} sites")

sites: 30 | converged: 30 | failed: 0
240 predictions | 8 weeks x 30 sites

## Weekly error, per calendar week across all sites

In [26]:
fc_w["abs_err"] = (fc_w.actual - fc_w.pred).abs()
fc_w["sq_err"] = (fc_w.actual - fc_w.pred) ** 2
fc_w["pct_err"] = np.where(fc_w.actual != 0, fc_w.abs_err / fc_w.actual, np.nan)

per_week = pd.DataFrame({
    "n_sites": fc_w.groupby("date").size(),
    "zero_sites": fc_w.groupby("date").pct_err.apply(lambda s: int(s.isna().sum())),
    "mean_actual": fc_w.groupby("date").actual.mean(),
    "mean_pred": fc_w.groupby("date").pred.mean(),
    "MAPE": fc_w.groupby("date").pct_err.mean(),
    "RMSE": fc_w.groupby("date").sq_err.mean() ** 0.5,
})

print(f"{len(per_week)} weeks | MAPE best {per_week.MAPE.min():.1%} | "
      f"median {per_week.MAPE.median():.1%} | worst {per_week.MAPE.max():.1%}")
per_week.round(4)

8 weeks | MAPE best 7.2% | median 8.7% | worst 16.5%

            n_sites  zero_sites  mean_actual  mean_pred    MAPE     RMSE
date
2024-07-07       30           0     174.7333   166.1391  0.0792  24.8656
2024-07-14       30           0     175.2223   170.2178  0.1082  29.0876
2024-07-21       30           0     169.4383   160.0650  0.0834  20.2427
2024-07-28       30           0     157.9543   165.7782  0.1071  25.8245
2024-08-04       30           0     160.8960   162.3869  0.0720  17.9903
2024-08-11       30           0     162.0863   165.0614  0.0908  24.2762
2024-08-18       30           0     164.8863   178.2204  0.1651  46.7823
2024-08-25       30           0     163.2863   158.3377  0.0756  22.2019

## Weekly error, per site

In [27]:
per_site_w = pd.DataFrame({
    "n_weeks": fc_w.groupby("site_id").size(),
    "mean_actual": fc_w.groupby("site_id").actual.mean(),
    "MAPE": fc_w.groupby("site_id").pct_err.mean(),
    "RMSE": fc_w.groupby("site_id").sq_err.mean() ** 0.5,
}).sort_values("MAPE", ascending=False)

print(f"MAPE across sites: best {per_site_w.MAPE.min():.1%} | "
      f"median {per_site_w.MAPE.median():.1%} | worst {per_site_w.MAPE.max():.1%}")
per_site_w.round(4)

MAPE across sites: best 1.8% | median 9.4% | worst 25.8%

          n_weeks  mean_actual    MAPE     RMSE
site_id
SITE_008        8     193.2875  0.2584  49.7331
SITE_014        8     196.0475  0.2535  68.5483
SITE_016        8     201.5688  0.1845  33.3222
SITE_006        8     180.9462  0.1525  31.4151
SITE_021        8     213.8212  0.1471  33.3388
SITE_001        8     199.2613  0.1385  33.8443
SITE_007        8     214.1362  0.1375  41.7515
SITE_010        8     205.2512  0.1304  29.4001
SITE_020        8     199.9950  0.1299  30.7577
SITE_030        8     201.3225  0.1249  29.9699
SITE_003        8     203.9312  0.1245  31.4595
SITE_011        8     217.6175  0.1109  33.3276
SITE_025        8     224.9138  0.1051  36.0407
SITE_018        8     205.8050  0.1025  25.8956
SITE_022        8     198.7338  0.0971  23.3270
SITE_026        8     238.9738  0.0913  25.1303
SITE_013        8     192.2850  0.0885  18.6261
SITE_017        8     214.8512  0.0863  19.7008
SITE_028        8     170.3600  0.0842  15.2588
SITE_005        8     209.9338  0.0745  19.0298
SITE_024        8     192.5338  0.0740  20.1422
SITE_012        8      81.0862  0.0331   2.7602
SITE_023        8      74.5350  0.0312   2.4593
SITE_015        8      84.0000  0.0304   2.9849
SITE_009        8      78.8438  0.0261   2.2891
SITE_019        8      73.7075  0.0245   1.8114
SITE_004        8      74.5112  0.0242   2.0434
SITE_002        8      80.7587  0.0237   2.3343
SITE_029        8      74.1325  0.0226   1.9176
SITE_027        8      84.7362  0.0185   2.0788

## Daily vs weekly

In [28]:
rows_w = [
    {**score(val_w[TARGET], val_w["planned_pour_tonnes"]), "model": "planned_pour (weekly)"},
    {**score(fc_w.actual, fc_w.pred), "model": "SARIMAX (weekly)"},
]
comparison = pd.concat([results_tbl, pd.DataFrame(rows_w).set_index("model")[
    ["MAPE", "RMSE", "WAPE", "MAE", "bias"]]])
comparison.round(4)

                          MAPE     RMSE    WAPE      MAE     bias
model
baseline: planned_pour  0.3372  14.4142  0.3189   7.4622   7.4622
baseline: train mean    0.7077  16.6324  0.6094  14.2586   0.3923
SARIMAX (cleaned data)  0.2227   8.6144  0.2464   5.7660  -0.0270
planned_pour (weekly)   0.2698  73.4089  0.3004  49.8817  49.8817
SARIMAX (weekly)        0.0977  27.6937  0.1063  17.6516  -0.2871

**RMSE is not comparable across grains.** A weekly total is roughly seven times a
daily value, so its RMSE is larger by construction - that is arithmetic, not a
worse model. MAPE and WAPE are scale-relative and can be compared.

Aggregation also makes the problem mechanically easier: day-to-day noise cancels
when summed, and the 12.2% of zero-pour days disappear. A lower weekly MAPE is
therefore partly a real gain in usable accuracy and partly an easier question. The
figure that carries meaning is the **gap between SARIMAX and `planned_pour` at each
grain**, since both face the same conditions.

Weekly is also the grain MIG actually reorders on, which is the practical argument
for it regardless of the arithmetic.

---

# Experiment 3 - Engineered Features, Weekly Aggregation

Weekly grain again, but with the engineered features from notebook 03 as regressors
instead of the four raw columns.

Aggregation is per feature type rather than one blanket rule - summing a flag and
summing a tonnage mean different things:

| feature | rule | meaning at weekly grain |
|---|---|---|
| `planned_pour_tonnes` | sum | tonnes scheduled that week |
| `planned_pour_next_7/14` | last | schedule looking forward from week end |
| `pour_blocked_rain` | **sum** | days lost to rain that week |
| `frost` | **sum** | frost days that week |
| `rain_mm`, `avg_temp_c` | mean | average conditions |
| `opening_inventory_tonnes`, `inventory_vs_capacity`, `headroom_tonnes` | first | position entering the week |
| `cover_days_7`, `days_since_planned_pour` | first | state entering the week |

`pour_blocked_rain` is the interesting one: as a daily 0/1 flag it marks a single
lost day, but summed it becomes "how many pour days this week were rained off",
which is a genuinely different and more useful quantity.

Target lags and rolling means are **excluded**. SARIMAX already models the
autoregressive structure through its AR terms, so passing lagged target values as
exogenous regressors double-counts them and destabilises the fit.

In [29]:
feats = pd.read_parquet(settings.processed_dir / "operations_feature_engineered.parquet")
feats["date"] = pd.to_datetime(feats["date"])
feats = feats.sort_values(["site_id", "date"]).reset_index(drop=True)
print("engineered daily matrix:", feats.shape)

AGG_ENG = {
    "y": "sum",
    "planned_pour_tonnes": "sum",
    "planned_pour_next_7": "last",
    "planned_pour_next_14": "last",
    "pour_blocked_rain": "sum",
    "frost": "sum",
    "rain_mm": "mean",
    "avg_temp_c": "mean",
    "opening_inventory_tonnes": "first",
    "inventory_vs_capacity": "first",
    "headroom_tonnes": "first",
    "cover_days_7": "first",
    "days_since_planned_pour": "first",
}

grp_e = feats.set_index("date").groupby("site_id").resample("W")
weekly_eng = grp_e.agg(AGG_ENG).reset_index()
weekly_eng["n_days"] = grp_e.size().values

EXOG_ENG = [c for c in AGG_ENG if c != "y"]

before = len(weekly_eng)
partial_e = weekly_eng.n_days < 7
weekly_eng = (weekly_eng[~partial_e]
              .drop(columns="n_days")
              .dropna(subset=["y"] + EXOG_ENG)
              .sort_values(["site_id", "date"])
              .reset_index(drop=True))
print(f"partial weeks dropped: {partial_e.sum()}")
print(f"weekly engineered: {before:,} -> {len(weekly_eng):,} rows")
print(f"{len(EXOG_ENG)} regressors (weekly used 4)")
weekly_eng.head()

engineered daily matrix: (32880, 44)
partial weeks dropped: 60
weekly engineered: 4,740 -> 4,680 rows
12 regressors (weekly used 4)

,site_id,date,y,planned_pour_tonnes,planned_pour_next_7,planned_pour_next_14,pour_blocked_rain,frost,rain_mm,avg_temp_c,opening_inventory_tonnes,inventory_vs_capacity,headroom_tonnes,cover_days_7,days_since_planned_pour
0,SITE_001,2022-01-09,208.96,234.47,248.84,593.06,0,0,2.734286,13.060000,38.56,0.086071,409.44,0.388400,0.0
1,SITE_001,2022-01-16,269.66,286.58,344.22,687.46,0,1,3.372857,11.337143,34.38,0.076741,413.62,1.151704,0.0
2,SITE_001,2022-01-23,235.01,346.98,343.24,646.20,0,0,3.258571,12.935714,4.95,0.011049,443.05,0.128495,0.0
3,SITE_001,2022-01-30,235.11,341.55,302.96,619.21,0,0,7.021429,12.470000,7.22,0.016116,440.78,0.215055,0.0
4,SITE_001,2022-02-06,196.26,307.16,316.25,600.74,0,0,4.274286,17.685714,3.59,0.008013,444.41,0.106886,0.0

In [30]:
print("what the aggregated flags look like:")
print(weekly_eng[["pour_blocked_rain", "frost"]].describe().loc[
    ["mean", "50%", "max"]].round(2).to_string())
print(f"\nweeks with at least one rained-off day: "
      f"{(weekly_eng.pour_blocked_rain > 0).mean():.1%}")
print(f"weeks with at least one frost day:       {(weekly_eng.frost > 0).mean():.1%}")

what the aggregated flags look like:
      pour_blocked_rain  frost
mean               0.35   0.97
50%                0.00   0.00
max                4.00   7.00

weeks with at least one rained-off day: 30.1%
weeks with at least one frost day:       39.0%

## Split

In [31]:
de = weekly_eng["date"]
train_e = weekly_eng[de <= TRAIN_END]
val_e = weekly_eng[(de > TRAIN_END) & (de <= VAL_END)]
test_e = weekly_eng[de > VAL_END]

val_e = val_e.groupby("site_id").head(HORIZON_WEEKS).reset_index(drop=True)
test_e = test_e.groupby("site_id").head(HORIZON_WEEKS).reset_index(drop=True)

for name, part in [("train", train_e), ("val", val_e), ("test", test_e)]:
    print(f"{name:5s} {len(part):5,} rows  {part.date.min().date()} -> {part.date.max().date()}"
          f"  ({part.groupby('site_id').size().mean():.0f} weeks per site)")

train 3,900 rows  2022-01-09 -> 2024-06-30  (130 weeks per site)
val     240 rows  2024-07-07 -> 2024-08-25  (8 weeks per site)
test    240 rows  2024-10-06 -> 2024-11-24  (8 weeks per site)

## Order selection

In [32]:
aic_e = {}
for o in GRID:
    scores = []
    for site in sorted(train_e.site_id.unique())[:5]:
        g = train_e[train_e.site_id == site].set_index("date").asfreq("W")
        try:
            scores.append(SARIMAX(g[TARGET], exog=g[EXOG_ENG], order=o,
                                  seasonal_order=(0, 0, 0, 0)).fit(disp=False).aic)
        except Exception:
            pass
    aic_e[str(o)] = np.mean(scores) if scores else np.nan

aic_e = pd.Series(aic_e).sort_values()
print(aic_e.round(1).to_string())
ORDER_E = eval(aic_e.index[0])
print("\nselected:", ORDER_E)

(1, 0, 0)    904.9
(0, 0, 1)    904.9
(1, 0, 1)    906.7
(2, 0, 1)    908.4
(2, 0, 2)    909.2

selected: (1, 0, 0)

## Train the model

In [33]:
y_train_e = train_e[train_e.site_id == SITE].set_index("date").asfreq("W")[TARGET]
x_train_e = train_e[train_e.site_id == SITE].set_index("date").asfreq("W")[EXOG_ENG]
y_val_e = val_e[val_e.site_id == SITE].set_index("date").asfreq("W")[TARGET]
x_val_e = val_e[val_e.site_id == SITE].set_index("date").asfreq("W")[EXOG_ENG]

print(f"{SITE}: train {len(y_train_e)} weeks, val {len(y_val_e)} weeks, "
      f"{x_train_e.shape[1]} regressors")

SITE_001: train 130 weeks, val 8 weeks, 12 regressors

In [34]:
model_e = SARIMAX(
    y_train_e,
    exog=x_train_e,
    order=ORDER_E,
    seasonal_order=(0, 0, 0, 0),
    enforce_stationarity=True,
)

results_e = model_e.fit(disp=False)
results_e.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  130
Model:               SARIMAX(1, 0, 0)   Log Likelihood                -612.868
Date:                Mon, 10 Aug 2026   AIC                           1253.736
Time:                        15:42:01   BIC                           1293.882
Sample:                    01-09-2022   HQIC                          1270.049
                         - 06-30-2024
Covariance Type:                  opg
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
planned_pour_tonnes          0.2718      0.080      3.404      0.001       0.115       0.428
planned_pour_next_7          0.2813      0.126      2.237      0.025       0.035       0.528
planned_pour_next_14        -0.0245      0.082     -0.301      0.763      -0.184       0.135
pour_blocked_rain          -21.7070      6.821     -3.183      0.001     -35.075      -8.339
frost                       -4.7870      3.194     -1.499      0.134     -11.048       1.474
rain_mm                      2.3090      1.876      1.231      0.218      -1.368       5.986
avg_temp_c                  -0.3718      0.526     -0.707      0.480      -1.403       0.659
opening_inventory_tonnes     0.9037      0.512      1.764      0.078      -0.100       1.907
inventory_vs_capacity        0.0020      0.001      1.768      0.077      -0.000       0.004
headroom_tonnes              0.1146      0.096      1.199      0.230      -0.073       0.302
cover_days_7                 2.0638     11.493      0.180      0.857     -20.463      24.590
days_since_planned_pour     28.0948     35.728      0.786      0.432     -41.931      98.121
ar.L1                       -0.0998      0.109     -0.914      0.361      -0.314       0.114
sigma2                     728.8974     98.450      7.404      0.000     535.940     921.855
===================================================================================
Ljung-Box (L1) (Q):                   0.03   Jarque-Bera (JB):                 0.28
Prob(Q):                              0.86   Prob(JB):                         0.87
Heteroskedasticity (H):               1.23   Skew:                            -0.05
Prob(H) (two-sided):                  0.50   Kurtosis:                         2.80
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
[2] Covariance matrix is singular or near-singular, with condition number 1.08e+22. Standard errors may be unstable.
"""

## Predict

In [35]:
y_pred_e = results_e.predict(start=y_val_e.index[0], end=y_val_e.index[-1], exog=x_val_e)
y_pred_e = y_pred_e.clip(lower=0)

print(f"{SITE}")
print(f"  MAPE {mean_absolute_percentage_error(y_val_e, y_pred_e)*100:.1f}%")
print(f"  RMSE {np.sqrt(mean_squared_error(y_val_e, y_pred_e)):.3f} t")
y_pred_e

SITE_001
  MAPE 10.6%
  RMSE 24.728 t

2024-07-07    213.460265
2024-07-14    219.798244
2024-07-21    206.850505
2024-07-28    199.071575
2024-08-04    225.008492
2024-08-11    270.050055
2024-08-18    211.465687
2024-08-25    180.011473
Freq: W-SUN, Name: predicted_mean, dtype: float64

## Fit all 30 sites

In [36]:
models_e, preds_e = {}, []

for site, g_tr in train_e.groupby("site_id"):
    g_tr = g_tr.set_index("date").asfreq("W")
    g_va = val_e[val_e.site_id == site].sort_values("date").set_index("date").asfreq("W")

    try:
        res = SARIMAX(
            g_tr[TARGET],
            exog=g_tr[EXOG_ENG],
            order=ORDER_E,
            seasonal_order=(0, 0, 0, 0),
            enforce_stationarity=True,
        ).fit(disp=False)
        pred = res.predict(start=g_va.index[0], end=g_va.index[-1],
                           exog=g_va[EXOG_ENG]).clip(lower=0)
    except Exception:
        res, pred = None, pd.Series(np.nan, index=g_va.index)

    models_e[site] = res
    preds_e.append(pd.DataFrame({"date": g_va.index, "site_id": site,
                                 "actual": g_va[TARGET].values, "pred": pred.values}))

fc_e = pd.concat(preds_e, ignore_index=True).dropna(subset=["pred"])
conv_e = sum(m is not None for m in models_e.values())
print(f"sites: {len(models_e)} | converged: {conv_e} | failed: {len(models_e) - conv_e}")
print(f"{len(fc_e):,} predictions | {fc_e.date.nunique()} weeks x {fc_e.site_id.nunique()} sites")

sites: 30 | converged: 30 | failed: 0
240 predictions | 8 weeks x 30 sites

## Weekly error, per calendar week across all sites

In [37]:
fc_e["abs_err"] = (fc_e.actual - fc_e.pred).abs()
fc_e["sq_err"] = (fc_e.actual - fc_e.pred) ** 2
fc_e["pct_err"] = np.where(fc_e.actual != 0, fc_e.abs_err / fc_e.actual, np.nan)

per_week_e = pd.DataFrame({
    "n_sites": fc_e.groupby("date").size(),
    "mean_actual": fc_e.groupby("date").actual.mean(),
    "mean_pred": fc_e.groupby("date").pred.mean(),
    "MAPE": fc_e.groupby("date").pct_err.mean(),
    "RMSE": fc_e.groupby("date").sq_err.mean() ** 0.5,
})

print(f"{len(per_week_e)} weeks | MAPE best {per_week_e.MAPE.min():.1%} | "
      f"median {per_week_e.MAPE.median():.1%} | worst {per_week_e.MAPE.max():.1%}")
per_week_e.round(4)

8 weeks | MAPE best 5.0% | median 8.5% | worst 14.1%

            n_sites  mean_actual  mean_pred    MAPE     RMSE
date
2024-07-07       30     174.7333   171.3840  0.0907  27.5001
2024-07-14       30     175.2223   173.9976  0.0848  25.2614
2024-07-21       30     169.4383   166.8011  0.0504  15.2719
2024-07-28       30     157.9543   167.8434  0.0878  23.4986
2024-08-04       30     160.8960   166.0164  0.0620  17.7982
2024-08-11       30     162.0863   169.7142  0.0858  23.1448
2024-08-18       30     164.8863   176.7268  0.1412  39.3040
2024-08-25       30     163.2863   163.5896  0.0642  17.3290

## Weekly error, per site

In [38]:
per_site_e = pd.DataFrame({
    "n_weeks": fc_e.groupby("site_id").size(),
    "mean_actual": fc_e.groupby("site_id").actual.mean(),
    "MAPE": fc_e.groupby("site_id").pct_err.mean(),
    "RMSE": fc_e.groupby("site_id").sq_err.mean() ** 0.5,
}).sort_values("MAPE", ascending=False)

print(f"MAPE across sites: best {per_site_e.MAPE.min():.1%} | "
      f"median {per_site_e.MAPE.median():.1%} | worst {per_site_e.MAPE.max():.1%}")
per_site_e.round(4)

MAPE across sites: best 0.6% | median 8.0% | worst 22.1%

          n_weeks  mean_actual    MAPE     RMSE
site_id
SITE_008        8     193.2875  0.2213  43.3462
SITE_014        8     196.0475  0.2069  55.8308
SITE_016        8     201.5688  0.1982  36.8533
SITE_028        8     170.3600  0.1885  30.0115
SITE_006        8     180.9462  0.1715  36.8392
SITE_020        8     199.9950  0.1171  28.5049
SITE_030        8     201.3225  0.1116  29.8161
SITE_010        8     205.2512  0.1086  25.7987
SITE_001        8     199.2613  0.1056  24.7276
SITE_007        8     214.1362  0.1030  31.0020
SITE_003        8     203.9312  0.1025  29.0430
SITE_005        8     209.9338  0.0978  29.8757
SITE_017        8     214.8512  0.0963  26.0627
SITE_011        8     217.6175  0.0851  20.7743
SITE_022        8     198.7338  0.0839  20.1684
SITE_025        8     224.9138  0.0768  27.5331
SITE_026        8     238.9738  0.0724  20.2233
SITE_024        8     192.5338  0.0722  19.2611
SITE_021        8     213.8212  0.0718  18.1658
SITE_018        8     205.8050  0.0716  20.4811
SITE_013        8     192.2850  0.0445  13.6028
SITE_023        8      74.5350  0.0186   2.0997
SITE_004        8      74.5112  0.0155   1.6287
SITE_019        8      73.7075  0.0112   0.8634
SITE_027        8      84.7362  0.0093   1.0528
SITE_012        8      81.0862  0.0088   0.8125
SITE_015        8      84.0000  0.0085   1.0000
SITE_002        8      80.7587  0.0083   0.9222
SITE_009        8      78.8438  0.0078   0.7539
SITE_029        8      74.1325  0.0057   0.5685

## All experiments compared

In [39]:
final = pd.concat([
    comparison,
    pd.DataFrame([{**score(fc_e.actual, fc_e.pred),
                   "model": "SARIMAX (engineered, weekly)"}]).set_index("model")[
        ["MAPE", "RMSE", "WAPE", "MAE", "bias"]],
])
final.round(4)

                                MAPE     RMSE    WAPE      MAE     bias
model
baseline: planned_pour        0.3372  14.4142  0.3189   7.4622   7.4622
baseline: train mean          0.7077  16.6324  0.6094  14.2586   0.3923
SARIMAX (cleaned data)        0.2227   8.6144  0.2464   5.7660  -0.0270
planned_pour (weekly)         0.2698  73.4089  0.3004  49.8817  49.8817
SARIMAX (weekly)              0.0977  27.6937  0.1063  17.6516  -0.2871
SARIMAX (engineered, weekly)  0.0834  24.6915  0.0906  15.0458   3.4462

In [40]:
weekly_only = final.loc[["planned_pour (weekly)", "SARIMAX (weekly)",
                         "SARIMAX (engineered, weekly)"]]
weekly_only.assign(**{
    "MAPE vs raw-feature model": (
        weekly_only.MAPE / final.loc["SARIMAX (weekly)", "MAPE"] - 1
    ).map(lambda x: f"{x:+.1%}"),
    "meets MAPE <= 15%": weekly_only.MAPE.le(0.15).map({True: "yes", False: "no"}),
}).round(4)

                                MAPE     RMSE    WAPE      MAE     bias MAPE vs raw-feature model meets MAPE <= 15%
model
planned_pour (weekly)         0.2698  73.4089  0.3004  49.8817  49.8817                   +176.2%                no
SARIMAX (weekly)              0.0977  27.6937  0.1063  17.6516  -0.2871                     +0.0%               yes
SARIMAX (engineered, weekly)  0.0834  24.6915  0.0906  15.0458   3.4462                    -14.7%               yes

## Notes

- Cleaned dataset only, no engineered features.
- `deliveries_tonnes`, `closing_inventory_tonnes` and `silo_capacity` are excluded
  from the regressors. The first two satisfy
  `consumed = opening + deliveries - closing` exactly, so including them lets the
  model reproduce the target instead of forecasting it; the third is constant
  within a site and makes the covariance matrix singular.
- MAPE is computed on non-zero actuals; the raw sklearn value is in section 7.
- Weather regressors use actual validation values, which flatters the result.
- The Oct-Dec 2024 test split is untouched.

# Global Machine Learning Models
## Random Forest Regressor

In [41]:
print(clean.columns.tolist())

['date', 'site_id', 'cement_type', 'planned_pour_tonnes', 'consumed_tonnes', 'opening_inventory_tonnes', 'deliveries_tonnes', 'closing_inventory_tonnes', 'rain_mm', 'avg_temp_c', 'silo_capacity', 'region', 'behavior', 'received_tonnes', 'rejected_delivery_tonnes', 'served_tonnes', 'induced_shortfall', 'was_constrained', 'unmet_tonnes', 'silo_utilisation', 'cover_days', 'y']

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

## Prepare Features and Target

The machine learning model is trained using the pooled dataset across all sites. Predictor variables include operational, weather, inventory, and site-level characteristics that are available before or at the time a forecast is made.

The target variable is **y**, representing cement demand.

In [43]:
feature_cols = [
    "planned_pour_tonnes",
    "opening_inventory_tonnes",
    "deliveries_tonnes",
    "rain_mm",
    "avg_temp_c",
    "silo_capacity",
    "cover_days",
    "silo_utilisation",
    "site_id",
    "cement_type",
    "region",
    "behavior",
]

X_train = train[feature_cols]
y_train = train[TARGET]

X_val = val[feature_cols]
y_val = val[TARGET]

X_test = test[feature_cols]
y_test = test[TARGET]

print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(27360, 12)
(2760, 12)
(2760, 12)

## Data Preprocessing

The dataset contains a mixture of numerical and categorical features. To prepare the data for machine learning, numerical variables are imputed using the median, while categorical variables are imputed using the most frequent category and encoded using one-hot encoding.

These preprocessing steps are combined into a single pipeline to ensure the same transformations are consistently applied during both training and prediction.

In [44]:
categorical_features = [
    "site_id",
    "cement_type",
    "region",
    "behavior",
]

numerical_features = [
    col for col in feature_cols if col not in categorical_features
]

preprocessor = ColumnTransformer(
    transformers=[
        ( "num",SimpleImputer(strategy="median"),
            numerical_features, ),
            
        ( "cat",Pipeline([ ("imputer", SimpleImputer(strategy="most_frequent")),
                ("encoder", OneHotEncoder(handle_unknown="ignore")),]),
            categorical_features, ),])

print("Numerical Features:", numerical_features)
print("Categorical Features:", categorical_features)

Numerical Features: ['planned_pour_tonnes', 'opening_inventory_tonnes', 'deliveries_tonnes', 'rain_mm', 'avg_temp_c', 'silo_capacity', 'cover_days', 'silo_utilisation']
Categorical Features: ['site_id', 'cement_type', 'region', 'behavior']

## Random Forest Model Development

A Random Forest Regressor is trained using the preprocessed dataset. Random Forest is an ensemble learning algorithm that combines multiple decision trees to improve predictive performance and reduce overfitting. The model is trained using the pooled dataset across all sites and will be evaluated on the validation set before comparison with the SARIMAX baseline.

In [45]:
rf_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model",RandomForestRegressor(
                n_estimators=200,
                max_depth=15,
                min_samples_split=5,
                min_samples_leaf=2,
                random_state=42,
                n_jobs=-1,),),])

print("Training Random Forest model...")

rf_pipeline.fit(X_train, y_train)

print("Training completed.")

Training Random Forest model...

Training completed.

## Model Validation

The trained Random Forest model is evaluated using the validation dataset. Performance is measured using Root Mean Squared Error (RMSE), Mean Absolute Error (MAE), and Mean Absolute Percentage Error (MAPE). These metrics provide an objective basis for comparing the machine learning model with the SARIMAX baseline.

In [46]:
from mig_cement.models.evaluate import evaluate

# Validation predictions
y_pred = rf_pipeline.predict(X_val)

# Evaluate
rf_metrics = evaluate(
    y_true=y_val,
    y_pred=y_pred,
    y_train=y_train,)

print("=" * 60)
print("Random Forest Validation Results")
print("=" * 60)

for metric, value in rf_metrics.items():
    print(f"{metric:<18}: {value:.4f}")

============================================================
Random Forest Validation Results
============================================================
WAPE              : 0.0098
RMSE              : 1.0786
MAE               : 0.2292
bias              : 0.0239
MAPE_nonzero      : 0.0083
pct_zero_actual   : 0.1199
MASE              : 0.0153

## Test Set Evaluation

After validating the Random Forest model, its performance is assessed on the held-out test dataset. The test set was not used during model training or model selection, providing an unbiased estimate of the model's generalisation performance.

In [47]:
# Predict on the test set
y_test_pred = rf_pipeline.predict(X_test)

# Evaluate on the test set
rf_test_metrics = evaluate(
    y_true=y_test,
    y_pred=y_test_pred,
    y_train=y_train,)

print("=" * 60)
print("Random Forest Test Results")
print("=" * 60)

for metric, value in rf_test_metrics.items():
    print(f"{metric:<18}: {value:.4f}")

============================================================
Random Forest Test Results
============================================================
WAPE              : 0.0100
RMSE              : 1.4575
MAE               : 0.2339
bias              : 0.0026
MAPE_nonzero      : 0.0079
pct_zero_actual   : 0.1279
MASE              : 0.0156

## Hyperparameter Tuning for Random Forest

The baseline Random Forest model is further optimised using hyperparameter tuning. Randomized Search is employed to explore a range of parameter combinations while keeping the computational cost manageable. The objective is to identify the model configuration that produces the best validation performance.

In [48]:
from sklearn.model_selection import RandomizedSearchCV

param_dist = {
    "model__n_estimators": [200, 300, 500],
    "model__max_depth": [10, 15, 20, None],
    "model__min_samples_split": [2, 5, 10],
    "model__min_samples_leaf": [1, 2, 4],
    "model__max_features": ["sqrt", "log2"],}

In [49]:
rf_search = RandomizedSearchCV(
    estimator=rf_pipeline,
    param_distributions=param_dist,
    n_iter=15,
    cv=3,
    scoring="neg_root_mean_squared_error",
    random_state=42,
    n_jobs=-1,
    verbose=2,
)

print("Tuning Random Forest...")

rf_search.fit(X_train, y_train)

print("Done.")

print("Best Parameters")
print(rf_search.best_params_)

print("\nBest CV Score")
print(rf_search.best_score_)

Tuning Random Forest...
Fitting 3 folds for each of 15 candidates, totalling 45 fits
Done.
Best Parameters
{'model__n_estimators': 200, 'model__min_samples_split': 5, 'model__min_samples_leaf': 1, 'model__max_features': 'sqrt', 'model__max_depth': 20}

Best CV Score
-2.7399734190969767

### Validation Performance

In [50]:
best_rf = rf_search.best_estimator_

y_pred = best_rf.predict(X_val)

best_rf_metrics = evaluate(
    y_true=y_val,
    y_pred=y_pred,
    y_train=y_train,
)

print("=" * 60)
print("Tuned Random Forest Validation Results")
print("=" * 60)

for metric, value in best_rf_metrics.items():
    print(f"{metric:<18}: {value:.4f}")

============================================================
Tuned Random Forest Validation Results
============================================================
WAPE              : 0.0679
RMSE              : 2.6827
MAE               : 1.5881
bias              : 0.0412
MAPE_nonzero      : 0.0623
pct_zero_actual   : 0.1199
MASE              : 0.1057

### Test parformance

In [51]:
y_test_pred = best_rf.predict(X_test)

best_rf_test_metrics = evaluate(
    y_true=y_test,
    y_pred=y_test_pred,
    y_train=y_train,
)

print("=" * 60)
print("Tuned Random Forest Test Results")
print("=" * 60)

for metric, value in best_rf_test_metrics.items():
    print(f"{metric:<18}: {value:.4f}")

============================================================
Tuned Random Forest Test Results
============================================================
WAPE              : 0.0694
RMSE              : 2.7212
MAE               : 1.6191
bias              : 0.0800
MAPE_nonzero      : 0.0646
pct_zero_actual   : 0.1279
MASE              : 0.1078

## Model Selection

Hyperparameter tuning was performed using RandomizedSearchCV to optimise the Random Forest model. However, the tuned model did not outperform the baseline Random Forest on the validation and test datasets. Therefore, the baseline Random Forest model was retained for subsequent comparisons with other machine learning models.

## LightGBM Model Development

LightGBM is a gradient boosting algorithm designed for high performance on structured datasets. Unlike Random Forest, which builds trees independently, LightGBM constructs trees sequentially, allowing each new tree to correct the errors of the previous ones.

The model is trained using the same preprocessing pipeline and time-based train, validation, and test split as the Random Forest model to ensure a fair comparison.

In [52]:
from lightgbm import LGBMRegressor

lgbm_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ( "model",LGBMRegressor(
                n_estimators=300,
                learning_rate=0.05,
                num_leaves=31,
                max_depth=10,
                subsample=0.8,
                colsample_bytree=0.8,
                random_state=42,
                verbosity=-1,),  ), ])

print("Training LightGBM model...")

lgbm_pipeline.fit(X_train, y_train)

print("LightGBM training completed.")

Training LightGBM model...
LightGBM training completed.

## LightGBM Validation

The trained LightGBM model is evaluated using the validation dataset. The same evaluation metrics used for the Random Forest model are applied to ensure a consistent comparison between the machine learning models.

In [53]:
y_pred_lgbm = lgbm_pipeline.predict(X_val)

lgbm_val_metrics = evaluate(
    y_true=y_val,
    y_pred=y_pred_lgbm,
    y_train=y_train,)

print("=" * 60)
print("LightGBM Validation Results")
print("=" * 60)

for metric, value in lgbm_val_metrics.items():
    print(f"{metric:<18}: {value:.4f}")

============================================================
LightGBM Validation Results
============================================================
WAPE              : 0.0199
RMSE              : 0.9819
MAE               : 0.4667
bias              : 0.0073
MAPE_nonzero      : 0.0197
pct_zero_actual   : 0.1199
MASE              : 0.0311

## LightGBM Test Evaluation

The selected LightGBM model is evaluated on the held-out test dataset to assess its ability to generalise to unseen observations. This provides a direct comparison with the Random Forest and SARIMAX models.

In [54]:
y_test_pred_lgbm = lgbm_pipeline.predict(X_test)

lgbm_test_metrics = evaluate(
    y_true=y_test,
    y_pred=y_test_pred_lgbm,
    y_train=y_train,
)

print("=" * 60)
print("LightGBM Test Results")
print("=" * 60)

for metric, value in lgbm_test_metrics.items():
    print(f"{metric:<18}: {value:.4f}")

============================================================
LightGBM Test Results
============================================================
WAPE              : 0.0217
RMSE              : 1.3855
MAE               : 0.5059
bias              : 0.0074
MAPE_nonzero      : 0.0206
pct_zero_actual   : 0.1279
MASE              : 0.0337

## 5.1 Weekly Data Aggregation

Because the forecasting objective is an eight-week horizon, the daily cleaned dataset is aggregated to weekly observations. The aggregation is performed separately for each site and cement type to preserve the individual demand series.

Flow variables such as cement consumption, planned pours, and deliveries are summed over each week, while state and environmental variables are aggregated using appropriate summary statistics.

In [55]:
# Weekly Data Aggregation
# ============================================

import pandas as pd
import numpy as np

# Make a copy so the original daily dataset remains unchanged
weekly = clean.copy()

# Ensure date is in datetime format
weekly["date"] = pd.to_datetime(weekly["date"])

# Create a week-start column
# Monday is used as the start of the forecasting week
weekly["week"] = weekly["date"].dt.to_period("W-SUN").dt.start_time

# Aggregate daily observations to weekly level
weekly = (weekly.groupby(["week", "site_id", "cement_type", "region", "behavior"],
        as_index=False).agg(
# Target and flow variables → SUM
        consumed_tonnes=("consumed_tonnes", "sum"),
        planned_pour_tonnes=("planned_pour_tonnes", "sum"),
        deliveries_tonnes=("deliveries_tonnes", "sum"),
        rain_mm=("rain_mm", "sum"),

        # State variables → FIRST/LAST
        opening_inventory_tonnes=("opening_inventory_tonnes", "first"),
        silo_capacity=("silo_capacity", "last"),

        # Environmental / utilisation variables → MEAN
        avg_temp_c=("avg_temp_c", "mean"),
        cover_days=("cover_days", "mean"),
        silo_utilisation=("silo_utilisation", "mean"),))

# Sort chronologically
weekly = weekly.sort_values(
    ["site_id", "cement_type", "week"]
).reset_index(drop=True)

print("Weekly dataset shape:", weekly.shape)

print("\nDate range:")
print(weekly["week"].min(), "to", weekly["week"].max())

print("\nNumber of sites:", weekly["site_id"].nunique())
print("Number of cement types:", weekly["cement_type"].nunique())

print("\nWeekly dataset preview:")
display(weekly.head())

Weekly dataset shape: (13337, 14)

Date range:
2021-12-27 00:00:00 to 2024-12-30 00:00:00

Number of sites: 30
Number of cement types: 3

Weekly dataset preview:

,week,site_id,cement_type,region,behavior,consumed_tonnes,planned_pour_tonnes,deliveries_tonnes,rain_mm,opening_inventory_tonnes,silo_capacity,avg_temp_c,cover_days,silo_utilisation
0,2021-12-27,SITE_001,CEM_I,North,aggressive,45.26,45.26,19.97,3.23,63.85,448,14.2800,1.410738,0.086071
1,2022-01-03,SITE_001,CEM_I,North,aggressive,101.04,108.88,121.00,12.52,47.06,448,15.3600,0.610361,0.045279
2,2022-01-10,SITE_001,CEM_I,North,aggressive,80.42,89.89,29.99,4.68,44.66,448,14.5700,0.838604,0.018605
3,2022-01-24,SITE_001,CEM_I,North,aggressive,126.46,131.07,122.22,23.55,7.22,448,14.2300,0.078625,0.004174
4,2022-01-31,SITE_001,CEM_I,North,aggressive,102.18,158.33,98.59,21.11,3.59,448,16.7475,0.153731,0.006200

## 5.2 Weekly Data Quality Check

Before feature engineering and model training, the weekly dataset is checked for missing values, missing weekly observations, duplicate site-cement-week combinations, and the number of observations available for each demand series.

In [56]:
# Weekly Data Quality Checks
# ============================================

# 1. Missing values
print("=" * 60)
print("Missing Values")
print("=" * 60)

missing = weekly.isna().sum()
missing = missing[missing > 0].sort_values(ascending=False)

if len(missing) > 0:
    print(missing)
else:
    print("No missing values found.")


# 2. Check for duplicate site-cement-week combinations
print("\n" + "=" * 60)
print("Duplicate Weekly Observations")
print("=" * 60)

duplicates = weekly.duplicated(
    subset=["week", "site_id", "cement_type"]
).sum()

print("Duplicate rows:", duplicates)


# 3. Number of observations per series
print("\n" + "=" * 60)
print("Observations Per Site-Cement Series")
print("=" * 60)

series_counts = (
    weekly
    .groupby(["site_id", "cement_type"])
    .size()
    .describe()
)

print(series_counts)


# 4. Check missing weeks within each site-cement series
print("\n" + "=" * 60)
print("Missing Weekly Observations")
print("=" * 60)

weekly["week"] = pd.to_datetime(weekly["week"])

missing_week_records = []

for (site, cement), group in weekly.groupby(
    ["site_id", "cement_type"]
):
    
    dates = group["week"].sort_values()
    
    expected_weeks = pd.date_range(
        start=dates.min(),
        end=dates.max(),
        freq="7D"
    )
    
    actual_weeks = pd.DatetimeIndex(dates.unique())
    
    missing_weeks = expected_weeks.difference(actual_weeks)
    
    if len(missing_weeks) > 0:
        missing_week_records.append({
            "site_id": site,
            "cement_type": cement,
            "missing_weeks": len(missing_weeks),
            "first_missing_week": missing_weeks.min(),
            "last_missing_week": missing_weeks.max()
        })


missing_week_df = pd.DataFrame(missing_week_records)

if missing_week_df.empty:
    print("No missing weeks detected within the series.")
else:
    print(
        f"Series with missing weeks: "
        f"{len(missing_week_df)}"
    )
    
    display(
        missing_week_df.head(20)
    )

============================================================
Missing Values
============================================================
cover_days    486
dtype: int64

============================================================
Duplicate Weekly Observations
============================================================
Duplicate rows: 0

============================================================
Observations Per Site-Cement Series
============================================================
count     90.000000
mean     148.188889
std        2.608949
min      140.000000
25%      146.000000
50%      148.000000
75%      150.000000
max      153.000000
dtype: float64

============================================================
Missing Weekly Observations
============================================================
Series with missing weeks: 90

     site_id cement_type  missing_weeks first_missing_week last_missing_week
0   SITE_001       CEM_I             11         2022-01-17        2024-06-17
1   SITE_001      CEM_II              7         2022-02-21        2024-09-30
2   SITE_001     CEM_III             14         2022-02-07        2024-10-07
3   SITE_002       CEM_I             10         2022-01-03        2024-09-02
4   SITE_002      CEM_II             10         2022-02-07        2024-12-09
5   SITE_002     CEM_III              8         2022-07-11        2024-12-16
6   SITE_003       CEM_I              4         2022-08-01        2024-07-22
7   SITE_003      CEM_II              7         2022-03-21        2023-12-11
8   SITE_003     CEM_III             13         2022-01-10        2024-01-29
9   SITE_004       CEM_I              6         2022-10-10        2024-12-09
10  SITE_004      CEM_II              7         2022-01-24        2024-10-14
11  SITE_004     CEM_III             16         2022-05-09        2024-11-18
12  SITE_005       CEM_I             10         2022-04-04        2024-11-11
13  SITE_005      CEM_II             10         2022-03-07        2024-08-05
14  SITE_005     CEM_III              9         2022-02-28        2024-10-14
15  SITE_006       CEM_I             15         2022-01-24        2024-10-21
16  SITE_006      CEM_II              9         2022-01-17        2024-11-18
17  SITE_006     CEM_III              7         2022-05-30        2024-11-04
18  SITE_007       CEM_I              5         2022-04-11        2024-04-15
19  SITE_007      CEM_II             10         2022-01-31        2024-12-02