# Step 4 - Model Development

**Baseline: SARIMAX with exogenous regressors.**

Cleaned dataset only - no engineered features.

Metrics are MAPE and RMSE per the brief, with WAPE alongside because MAPE is
undefined on zero-consumption days (12.2% of rows). Selection is on the validation
split; the test period is not touched.

In [104]:
import sys
from pathlib import Path

# Project root
PROJECT_ROOT = Path.cwd().parent

# Add src folder to Python path
sys.path.insert(0, str(PROJECT_ROOT / "src"))

print("Project Root:", PROJECT_ROOT)

Project Root: c:\Datascience_Projects\MIG_Cement_Demand_Forecasting

In [105]:
import warnings

import numpy as np
import pandas as pd
from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.tsa.stattools import adfuller

from mig_cement.config import settings

warnings.filterwarnings("ignore")
pd.set_option("display.width", 170)
pd.set_option("display.max_columns", 30)

TRAIN_END, VAL_END = "2024-06-30", "2024-09-30"
TARGET = "y"
HORIZON_WEEKS = 8   # the forecast horizon the brief specifies

## 1. Load the cleaned dataset

In [106]:
clean = pd.read_parquet(settings.interim_dir / "operations_clean.parquet")
clean["date"] = pd.to_datetime(clean["date"])
clean = clean.sort_values(["site_id", "date"]).reset_index(drop=True)

print("shape:", clean.shape)
print("sites:", clean.site_id.nunique(), "| dates:", clean.date.nunique())
print("range:", clean.date.min().date(), "->", clean.date.max().date())

shape: (32880, 22)
sites: 30 | dates: 1096
range: 2022-01-01 -> 2024-12-31

## 2. Handle NaNs

Rows with NaN are removed, scoped to the columns this model uses.

A blanket `dropna()` would be a trap: `cover_days` is NaN exactly where
`consumed_tonnes == 0`, so it silently deletes every zero-consumption day - the
rain-blocked pours and stockouts, which are the hard cases.

In [107]:
print("NaN counts:")
print(clean.isna().sum()[lambda s: s > 0].to_string())
print("\nblanket dropna would give:", clean.dropna().shape,
      f"({100*(1-len(clean.dropna())/len(clean)):.1f}% lost)")
print("  zero-y rows before:", int((clean[TARGET] == 0).sum()),
      "| after:", int((clean.dropna()[TARGET] == 0).sum()))

NaN counts:
cover_days    4003

blanket dropna would give: (28877, 22) (12.2% lost)
  zero-y rows before: 4003 | after: 0

In [108]:
EXOG = ["planned_pour_tonnes", "rain_mm", "avg_temp_c", "opening_inventory_tonnes"]

before = len(clean)
clean = clean.dropna(subset=[TARGET] + EXOG).reset_index(drop=True)
print(f"rows: {before:,} -> {len(clean):,}")
print(f"zero-y rows retained: {int((clean[TARGET] == 0).sum()):,} "
      f"({(clean[TARGET] == 0).mean():.1%})")

rows: 32,880 -> 32,880
zero-y rows retained: 4,003 (12.2%)

### Why these four regressors

Of the 22 columns in the cleaned panel, most cannot be used:

- **target-derived / leaky**: `consumed_tonnes`, `served_tonnes`,
  `closing_inventory_tonnes`, `cover_days`, `silo_utilisation`, `was_constrained`,
  `unmet_tonnes`, `induced_shortfall`
- **not knowable at forecast time**: `deliveries_tonnes`, `received_tonnes`,
  `rejected_delivery_tonnes`
- **constant within each site**: `silo_capacity`, `region`, `behavior` - models are
  fitted per site, so these have no within-series variance and are collinear with
  the intercept
- **keys**: `date`, `site_id`, `cement_type`

## 3. Train / validation / test split

Chronological. The test period is held back.

In [109]:
d = clean["date"]
train = clean[d <= TRAIN_END]
val = clean[(d > TRAIN_END) & (d <= VAL_END)]
test = clean[d > VAL_END]

for name, part in [("train", train), ("val", val), ("test", test)]:
    print(f"{name:6s} {len(part):6,} rows  {part.date.min().date()} -> {part.date.max().date()}")

train  27,360 rows  2022-01-01 -> 2024-06-30
val     2,760 rows  2024-07-01 -> 2024-09-30
test    2,760 rows  2024-10-01 -> 2024-12-31

## 4. Model configuration

`d = 0` because the series are stationary. `seasonal_order = (0,0,0,0)` because
Step 3 tested weekly, monthly and annual seasonality per region against a shuffled
null and found none - seasonal terms would fit noise.

In [110]:
adf = pd.Series({s: adfuller(g[TARGET])[1] for s, g in clean.groupby("site_id")})
print(f"ADF p-values across {len(adf)} sites: max = {adf.max():.2e}")
print(f"sites rejecting a unit root at 1%: {(adf < 0.01).sum()} / {len(adf)}")
print("\n-> d = 0")

ADF p-values across 30 sites: max = 3.61e-17
sites rejecting a unit root at 1%: 30 / 30

-> d = 0

In [111]:
# order chosen by mean AIC across a sample of sites
GRID = [(1, 0, 0), (0, 0, 1), (1, 0, 1), (2, 0, 1), (2, 0, 2)]
aic = {}
for o in GRID:
    scores = []
    for site in sorted(train.site_id.unique())[:5]:
        g = train[train.site_id == site].set_index("date")
        try:
            scores.append(SARIMAX(g[TARGET], exog=g[EXOG], order=o,
                                  seasonal_order=(0, 0, 0, 0)).fit(disp=False).aic)
        except Exception:
            pass
    aic[str(o)] = np.mean(scores)

aic = pd.Series(aic).sort_values()
print(aic.round(1).to_string())
ORDER = (2, 0, 2)
print("\nselected:", ORDER)

(2, 0, 2)    4979.0
(2, 0, 1)    4984.3
(1, 0, 1)    4984.7
(1, 0, 0)    4985.9
(0, 0, 1)    4986.2

selected: (2, 0, 2)

## 5. Train the model

Fitted on one site first, in the plainest form.

In [112]:
SITE = "SITE_001"

y_train = train[train.site_id == SITE].set_index("date")[TARGET]
x_train = train[train.site_id == SITE].set_index("date")[EXOG]
y_val = val[val.site_id == SITE].set_index("date")[TARGET]
x_val = val[val.site_id == SITE].set_index("date")[EXOG]

print(f"{SITE}: train {y_train.shape[0]} rows, val {y_val.shape[0]} rows, "
      f"{x_train.shape[1]} exogenous regressors")

SITE_001: train 912 rows, val 92 rows, 4 exogenous regressors

In [113]:
model = SARIMAX(
    y_train,
    exog=x_train,
    order=ORDER,
    seasonal_order=(0, 0, 0, 0),
    enforce_stationarity=True,
)

results = model.fit(disp=False)
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  912
Model:               SARIMAX(2, 0, 2)   Log Likelihood               -3488.122
Date:                Thu, 13 Aug 2026   AIC                           6994.243
Time:                        10:04:01   BIC                           7037.584
Sample:                    01-01-2022   HQIC                          7010.789
                         - 06-30-2024
Covariance Type:                  opg
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
planned_pour_tonnes          0.6497      0.017     37.579      0.000       0.616       0.684
rain_mm                     -0.7637      0.054    -14.243      0.000      -0.869      -0.659
avg_temp_c                   0.1878      0.047      3.965      0.000       0.095       0.281
opening_inventory_tonnes     0.2729      0.020     13.435      0.000       0.233       0.313
ar.L1                        0.5999      1.215      0.494      0.622      -1.782       2.982
ar.L2                        0.2454      1.007      0.244      0.807      -1.729       2.220
ma.L1                       -0.5354      1.209     -0.443      0.658      -2.906       1.835
ma.L2                       -0.2605      0.941     -0.277      0.782      -2.104       1.583
sigma2                     123.0751      7.080     17.385      0.000     109.199     136.951
===================================================================================
Ljung-Box (L1) (Q):                   0.03   Jarque-Bera (JB):                60.36
Prob(Q):                              0.86   Prob(JB):                         0.00
Heteroskedasticity (H):               1.03   Skew:                            -0.63
Prob(H) (two-sided):                  0.82   Kurtosis:                         2.96
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

`enforce_stationarity=True` is deliberate. With it set to `False`, an unstable
AR root produced forecasts that diverged across the 92-day validation window -
one site reached an RMSE of 1.96e20. The series are stationary, so the constraint
costs nothing.

## 6. Predict

`y_val` / `X_val` below are the **validation** window (Jul-Sep 2024).
Oct-Dec 2024 stays held back and is not touched in this notebook.

In [114]:
y_pred = results.predict(start=y_val.index[0], end=y_val.index[-1], exog=x_val)
y_pred = y_pred.clip(lower=0)
y_pred

2024-07-01    29.360996
2024-07-02    22.726810
2024-07-03    36.481619
2024-07-04    32.125151
2024-07-05    39.116897
                ...
2024-09-26    36.900509
2024-09-27    34.793300
2024-09-28    29.244128
2024-09-29    39.149687
2024-09-30    37.968417
Freq: D, Name: predicted_mean, Length: 92, dtype: float64

## 7. Metrics

`sklearn.metrics.mean_absolute_percentage_error` returns a **fraction, not a
percentage** - a returned value of 15 means 1500%, not 15%.

It is also undefined when the actual is zero. 12.2% of site-days have no pour, and
on those rows sklearn divides by a tiny epsilon, so a handful of rows can dominate
the whole average. MAPE is therefore computed on non-zero actuals only, with the
raw sklearn figure shown alongside so the gap is visible.

In [115]:
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error

nz = y_val != 0

mape_raw = mean_absolute_percentage_error(y_val, y_pred)
mape_nonzero = mean_absolute_percentage_error(y_val[nz], y_pred[nz])
rmse = np.sqrt(mean_squared_error(y_val, y_pred))

print(f"{SITE}")
print(f"  zero-actual days      {int((~nz).sum())} of {len(y_val)}")
print(f"  MAPE (sklearn raw)    {mape_raw:.4f}  = {mape_raw*100:,.0f}%")
print(f"  MAPE (non-zero only)  {mape_nonzero:.4f}  = {mape_nonzero*100:.1f}%")
print(f"  RMSE                  {rmse:.3f} t")

SITE_001
  zero-actual days      16 of 92
  MAPE (sklearn raw)    9531940421263326.0000  = 953,194,042,126,332,544%
  MAPE (non-zero only)  0.2595  = 26.0%
  RMSE                  10.755 t

## 8. Fit all 30 sites and predict

In [116]:
models, preds = {}, []

for site, g_tr in train.groupby("site_id"):
    g_tr = g_tr.set_index("date")
    g_te = val[val.site_id == site].sort_values("date").set_index("date")

    y_tr, X_tr = g_tr[TARGET], g_tr[EXOG]
    y_te, X_te = g_te[TARGET], g_te[EXOG]

    try:
        res = SARIMAX(
            y_tr,
            exog=X_tr,
            order=ORDER,
            seasonal_order=(0, 0, 0, 0),
            enforce_stationarity=True,
        ).fit(disp=False)
        pred = res.predict(start=y_te.index[0], end=y_te.index[-1], exog=X_te).clip(lower=0)
    except Exception:
        res, pred = None, pd.Series(np.nan, index=y_te.index)

    models[site] = res
    preds.append(pd.DataFrame({"date": y_te.index, "site_id": site,
                               "actual": y_te.values, "pred": pred.values}))

fc = pd.concat(preds, ignore_index=True).dropna(subset=["pred"])
converged = sum(m is not None for m in models.values())
print(f"sites: {len(models)} | converged: {converged} | failed: {len(models) - converged}")
print(f"{len(fc):,} predictions | {fc.date.nunique()} dates x {fc.site_id.nunique()} sites")

sites: 30 | converged: 30 | failed: 0
2,760 predictions | 92 dates x 30 sites

## 9. Daily error, per site

One row per site-day: absolute error, squared error, and percentage error where the
actual is non-zero.

In [117]:
fc["abs_err"] = (fc.actual - fc.pred).abs()
fc["sq_err"] = (fc.actual - fc.pred) ** 2
fc["pct_err"] = np.where(fc.actual != 0, fc.abs_err / fc.actual, np.nan)

print(f"{len(fc):,} site-days | {fc.pct_err.isna().sum():,} with zero actual (no MAPE)")
fc.head(10).round(3)

2,760 site-days | 331 with zero actual (no MAPE)

        date   site_id  actual    pred  abs_err   sq_err  pct_err
0 2024-07-01  SITE_001   26.75  29.361    2.611    6.817    0.098
1 2024-07-02  SITE_001   22.51  22.727    0.217    0.047    0.010
2 2024-07-03  SITE_001   15.48  36.482   21.002  441.068    1.357
3 2024-07-04  SITE_001   44.07  32.125   11.945  142.679    0.271
4 2024-07-05  SITE_001   40.07  39.117    0.953    0.908    0.024
5 2024-07-06  SITE_001   30.06  17.259   12.801  163.861    0.426
6 2024-07-07  SITE_001    0.00   0.000    0.000    0.000      NaN
7 2024-07-08  SITE_001   35.45  30.025    5.425   29.426    0.153
8 2024-07-09  SITE_001   38.26  32.267    5.993   35.919    0.157
9 2024-07-10  SITE_001   14.56  33.080   18.520  342.997    1.272

In [118]:
per_site = pd.DataFrame({
    "n_days": fc.groupby("site_id").size(),
    "zero_days": fc.groupby("site_id").pct_err.apply(lambda s: int(s.isna().sum())),
    "mean_actual": fc.groupby("site_id").actual.mean(),
    "MAPE": fc.groupby("site_id").pct_err.mean(),
    "RMSE": fc.groupby("site_id").sq_err.mean() ** 0.5,
}).sort_values("MAPE", ascending=False)

print(f"MAPE across sites: best {per_site.MAPE.min():.1%} | "
      f"median {per_site.MAPE.median():.1%} | worst {per_site.MAPE.max():.1%}")
per_site.round(4)

MAPE across sites: best 6.3% | median 25.0% | worst 42.7%

          n_days  zero_days  mean_actual    MAPE     RMSE
site_id
SITE_017      92          8      28.1239  0.4273  12.5276
SITE_030      92          7      29.1316  0.3880  10.4852
SITE_025      92          7      30.8111  0.3872  11.8301
SITE_021      92          9      28.7862  0.3828  10.2464
SITE_010      92          4      30.0573  0.3704  10.6331
SITE_018      92          6      29.5473  0.3676  10.6119
SITE_008      92         13      28.3165  0.3610  10.8088
SITE_022      92          8      29.5374  0.3602  10.6751
SITE_006      92         19      25.7420  0.3145  10.8766
SITE_016      92         23      25.3807  0.2977  12.3412
SITE_003      92         10      29.9430  0.2887   9.8031
SITE_020      92          9      29.5273  0.2606   9.6457
SITE_001      92         16      29.0104  0.2595  10.7549
SITE_011      92          4      30.4378  0.2593  10.0182
SITE_007      92         12      30.3996  0.2559  10.3240
SITE_014      92         22      27.1127  0.2446  10.9871
SITE_005      92         15      30.7698  0.2241  11.0001
SITE_028      92         25      25.4123  0.1615   5.8184
SITE_026      92         20      32.3905  0.1598   7.2808
SITE_024      92         28      25.8827  0.1452  10.1078
SITE_013      92         25      26.3252  0.1388   5.9570
SITE_015      92          3      11.3630  0.0759   1.0118
SITE_012      92          6      10.9359  0.0758   1.0008
SITE_004      92          3      10.5129  0.0757   0.9750
SITE_002      92          3      11.4060  0.0749   0.9148
SITE_019      92          8      10.7532  0.0743   1.0113
SITE_023      92          5      10.6533  0.0740   1.0021
SITE_009      92          3      11.0623  0.0739   0.9871
SITE_029      92          7      11.0157  0.0671   0.9145
SITE_027      92          3      11.6418  0.0627   0.9461

## 10. Daily error, per calendar date across all sites

In [119]:
per_day = pd.DataFrame({
    "n_sites": fc.groupby("date").size(),
    "zero_sites": fc.groupby("date").pct_err.apply(lambda s: int(s.isna().sum())),
    "mean_actual": fc.groupby("date").actual.mean(),
    "mean_pred": fc.groupby("date").pred.mean(),
    "MAPE": fc.groupby("date").pct_err.mean(),
    "RMSE": fc.groupby("date").sq_err.mean() ** 0.5,
})

print(f"{len(per_day)} days | MAPE best {per_day.MAPE.min():.1%} | "
      f"median {per_day.MAPE.median():.1%} | worst {per_day.MAPE.max():.1%}")
per_day.round(4)

92 days | MAPE best 12.7% | median 21.8% | worst 42.6%

            n_sites  zero_sites  mean_actual  mean_pred    MAPE     RMSE
date
2024-07-01       30           4      25.9203    24.6190  0.1826   7.8753
2024-07-02       30           5      21.3010    22.6529  0.2182   7.1798
2024-07-03       30           4      24.4493    22.6030  0.1624   7.1555
2024-07-04       30           3      26.7497    24.0066  0.1562   7.4605
2024-07-05       30           4      22.8220    21.0926  0.2011   8.5421
...             ...         ...          ...        ...     ...      ...
2024-09-26       30           1      25.2933    23.3557  0.2445   8.4090
2024-09-27       30           4      18.4490    20.0329  0.3022   7.4002
2024-09-28       30           7      16.0650    20.4922  0.3233  10.4130
2024-09-29       30           2      26.2260    26.0990  0.2411   9.1942
2024-09-30       30           8      16.6353    17.9388  0.2768   7.9152

[92 rows x 6 columns]

In [120]:
per_day_h = per_day.reset_index()
per_day_h["horizon_day"] = np.arange(1, len(per_day_h) + 1)
per_day_h["week"] = ((per_day_h.horizon_day - 1) // 7) + 1

by_week = per_day_h.groupby("week").agg(
    days=("horizon_day", "size"), MAPE=("MAPE", "mean"), RMSE=("RMSE", "mean")).head(8)
print("error by forecast week (the 8-week horizon in the brief):")
by_week.round(4)

error by forecast week (the 8-week horizon in the brief):

      days    MAPE    RMSE
week
1        7  0.1807  7.3374
2        7  0.2165  7.7270
3        7  0.2028  7.7250
4        7  0.2224  9.0562
5        7  0.2305  8.7375
6        7  0.2288  8.9342
7        7  0.2778  9.8989
8        7  0.2115  8.2270

## 11. Overall, against baselines

In [121]:
def score(y_true, y_pred_):
    y_true, y_pred_ = np.asarray(y_true, float), np.asarray(y_pred_, float)
    nzm = y_true != 0
    return {
        "MAPE": mean_absolute_percentage_error(y_true[nzm], y_pred_[nzm]),
        "RMSE": np.sqrt(mean_squared_error(y_true, y_pred_)),
        "WAPE": np.abs(y_true - y_pred_).sum() / np.abs(y_true).sum(),
        "MAE": np.abs(y_true - y_pred_).mean(),
        "bias": (y_pred_ - y_true).mean(),
    }


rows = [
    {**score(val[TARGET], val["planned_pour_tonnes"]), "model": "baseline: planned_pour"},
    {**score(val[TARGET], np.full(len(val), train[TARGET].mean())), "model": "baseline: train mean"},
    {**score(fc.actual, fc.pred), "model": "SARIMAX (cleaned data)"},
]
results_tbl = pd.DataFrame(rows).set_index("model")[["MAPE", "RMSE", "WAPE", "MAE", "bias"]]
results_tbl.round(4)

                          MAPE     RMSE    WAPE      MAE    bias
model
baseline: planned_pour  0.3372  14.4142  0.3189   7.4622  7.4622
baseline: train mean    0.7077  16.6324  0.6094  14.2586  0.3923
SARIMAX (cleaned data)  0.2227   8.6128  0.2464   5.7653 -0.0305

---

# Experiment 2 - Weekly Aggregation

Same cleaned dataset, same regressors, same model. The only change is the grain:
each site-day is aggregated to a site-week.

Consumption and planned pour are **summed**, weather is **averaged**, and opening
inventory takes the **first** value of the week.

In [122]:
AGG = {
    "y": "sum",
    "planned_pour_tonnes": "sum",
    "rain_mm": "mean",
    "avg_temp_c": "mean",
    "opening_inventory_tonnes": "first",
}

grp = clean.set_index("date").groupby("site_id").resample("W")
weekly = grp.agg(AGG).reset_index()
weekly["n_days"] = grp.size().values

# Drop partial weeks. resample("W") opens and closes the series with buckets that
# hold fewer than 7 days - the final one covers only 30-31 Dec, and averages 49.5 t
# against 162.6 t for a full week. Left in, it reads as a demand collapse.
partial = weekly.n_days < 7
print(f"partial weeks dropped: {partial.sum()} of {len(weekly)}")
print(weekly.loc[partial, ["date", "n_days", "y"]].groupby("date")
             .agg(sites=("n_days", "size"), days=("n_days", "first"),
                  mean_y=("y", "mean")).round(1).to_string())

weekly = (weekly[~partial]
          .drop(columns="n_days")
          .dropna(subset=["y"])
          .sort_values(["site_id", "date"])
          .reset_index(drop=True))

print("\ndaily :", clean.shape, "| mean y", round(clean.y.mean(), 2), "t",
      "| zero rows", f"{(clean.y == 0).mean():.1%}")
print("weekly:", weekly.shape, "| mean y", round(weekly.y.mean(), 2), "t",
      "| zero rows", f"{(weekly.y == 0).mean():.1%}")
weekly.head()

partial weeks dropped: 60 of 4740
            sites  days  mean_y
date
2022-01-02     30     2    60.8
2025-01-05     30     2    49.5

daily : (32880, 22) | mean y 23.72 t | zero rows 12.2%
weekly: (4680, 7) | mean y 165.94 t | zero rows 0.0%

    site_id       date       y  planned_pour_tonnes   rain_mm  avg_temp_c  opening_inventory_tonnes
0  SITE_001 2022-01-09  208.96               234.47  2.734286   13.060000                     38.56
1  SITE_001 2022-01-16  269.66               286.58  3.372857   11.337143                     34.38
2  SITE_001 2022-01-23  235.01               346.98  3.258571   12.935714                      4.95
3  SITE_001 2022-01-30  235.11               341.55  7.021429   12.470000                      7.22
4  SITE_001 2022-02-06  196.26               307.16  4.274286   17.685714                      3.59

Aggregation removes the zero-consumption problem entirely: no site goes a full
week without pouring, so MAPE becomes well-defined on every row.

## Split

In [123]:
dw = weekly["date"]
train_w = weekly[dw <= TRAIN_END]
val_w = weekly[(dw > TRAIN_END) & (dw <= VAL_END)]
test_w = weekly[dw > VAL_END]

# The brief asks for forecasts up to 8 weeks ahead, so scoring is capped at that
# horizon. Beyond it the model is being judged on something it does not promise.
val_w = val_w.groupby("site_id").head(HORIZON_WEEKS).reset_index(drop=True)
test_w = test_w.groupby("site_id").head(HORIZON_WEEKS).reset_index(drop=True)

for name, part in [("train", train_w), ("val", val_w), ("test", test_w)]:
    print(f"{name:6s} {len(part):5,} rows  {part.date.min().date()} -> {part.date.max().date()}"
          f"  ({part.groupby('site_id').size().mean():.0f} weeks per site)")

train  3,900 rows  2022-01-09 -> 2024-06-30  (130 weeks per site)
val      240 rows  2024-07-07 -> 2024-08-25  (8 weeks per site)
test     240 rows  2024-10-06 -> 2024-11-24  (8 weeks per site)

## Order selection

In [124]:
aic_w = {}
for o in GRID:
    scores = []
    for site in sorted(train_w.site_id.unique())[:5]:
        g = train_w[train_w.site_id == site].set_index("date").asfreq("W")
        try:
            scores.append(SARIMAX(g[TARGET], exog=g[EXOG], order=o,
                                  seasonal_order=(0, 0, 0, 0)).fit(disp=False).aic)
        except Exception:
            pass
    aic_w[str(o)] = np.mean(scores) if scores else np.nan

aic_w = pd.Series(aic_w).sort_values()
print(aic_w.round(1).to_string())
ORDER_W = eval(aic_w.index[0])
print("\nselected:", ORDER_W)

(2, 0, 2)     991.7
(1, 0, 1)     992.7
(1, 0, 0)     995.1
(0, 0, 1)     997.4
(2, 0, 1)    1210.6

selected: (2, 0, 2)

## Train the model

In [125]:
y_train_w = train_w[train_w.site_id == SITE].set_index("date").asfreq("W")[TARGET]
x_train_w = train_w[train_w.site_id == SITE].set_index("date").asfreq("W")[EXOG]
y_val_w = val_w[val_w.site_id == SITE].set_index("date").asfreq("W")[TARGET]
x_val_w = val_w[val_w.site_id == SITE].set_index("date").asfreq("W")[EXOG]

print(f"{SITE}: train {len(y_train_w)} weeks, val {len(y_val_w)} weeks")

SITE_001: train 130 weeks, val 8 weeks

In [126]:
model_w = SARIMAX(
    y_train_w,
    exog=x_train_w,
    order=ORDER_W,
    seasonal_order=(0, 0, 0, 0),
    enforce_stationarity=True,
)

results_w = model_w.fit(disp=False)
results_w.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  130
Model:               SARIMAX(2, 0, 2)   Log Likelihood                -631.375
Date:                Thu, 13 Aug 2026   AIC                           1280.749
Time:                        10:04:19   BIC                           1306.557
Sample:                    01-09-2022   HQIC                          1291.236
                         - 06-30-2024
Covariance Type:                  opg
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
planned_pour_tonnes          0.6489      0.027     23.948      0.000       0.596       0.702
rain_mm                     -0.9474      1.272     -0.745      0.456      -3.440       1.545
avg_temp_c                   0.4891      0.386      1.268      0.205      -0.267       1.245
opening_inventory_tonnes     1.0736      0.119      9.011      0.000       0.840       1.307
ar.L1                        0.8702      0.076     11.401      0.000       0.721       1.020
ar.L2                       -0.7914      0.083     -9.521      0.000      -0.954      -0.629
ma.L1                       -1.0580      0.946     -1.118      0.264      -2.913       0.797
ma.L2                        0.9988      1.788      0.558      0.577      -2.506       4.504
sigma2                     932.1953   1625.194      0.574      0.566   -2253.126    4117.517
===================================================================================
Ljung-Box (L1) (Q):                   0.25   Jarque-Bera (JB):                 1.10
Prob(Q):                              0.62   Prob(JB):                         0.58
Heteroskedasticity (H):               1.06   Skew:                            -0.21
Prob(H) (two-sided):                  0.85   Kurtosis:                         2.86
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

## Predict

In [127]:
y_pred_w = results_w.predict(start=y_val_w.index[0], end=y_val_w.index[-1], exog=x_val_w)
y_pred_w = y_pred_w.clip(lower=0)

print(f"{SITE}")
print(f"  MAPE {mean_absolute_percentage_error(y_val_w, y_pred_w):.4f}"
      f"  = {mean_absolute_percentage_error(y_val_w, y_pred_w)*100:.1f}%")
print(f"  RMSE {np.sqrt(mean_squared_error(y_val_w, y_pred_w)):.3f} t")
y_pred_w

SITE_001
  MAPE 0.1385  = 13.9%
  RMSE 33.858 t

2024-07-07    179.706317
2024-07-14    238.815687
2024-07-21    159.548932
2024-07-28    224.110057
2024-08-04    239.907993
2024-08-11    259.231339
2024-08-18    221.272593
2024-08-25    174.498050
Freq: W-SUN, Name: predicted_mean, dtype: float64

## Fit all 30 sites

In [128]:
models_w, preds_w = {}, []

for site, g_tr in train_w.groupby("site_id"):
    g_tr = g_tr.set_index("date").asfreq("W")
    g_te = val_w[val_w.site_id == site].sort_values("date").set_index("date").asfreq("W")

    try:
        res = SARIMAX(
            g_tr[TARGET],
            exog=g_tr[EXOG],
            order=ORDER_W,
            seasonal_order=(0, 0, 0, 0),
            enforce_stationarity=True,
        ).fit(disp=False)
        pred = res.predict(start=g_te.index[0], end=g_te.index[-1],
                           exog=g_te[EXOG]).clip(lower=0)
    except Exception:
        res, pred = None, pd.Series(np.nan, index=g_te.index)

    models_w[site] = res
    preds_w.append(pd.DataFrame({"date": g_te.index, "site_id": site,
                                 "actual": g_te[TARGET].values, "pred": pred.values}))

fc_w = pd.concat(preds_w, ignore_index=True).dropna(subset=["pred"])
converged_w = sum(m is not None for m in models_w.values())
print(f"sites: {len(models_w)} | converged: {converged_w} | failed: {len(models_w) - converged_w}")
print(f"{len(fc_w):,} predictions | {fc_w.date.nunique()} weeks x {fc_w.site_id.nunique()} sites")

sites: 30 | converged: 30 | failed: 0
240 predictions | 8 weeks x 30 sites

## Weekly error, per calendar week across all sites

In [129]:
fc_w["abs_err"] = (fc_w.actual - fc_w.pred).abs()
fc_w["sq_err"] = (fc_w.actual - fc_w.pred) ** 2
fc_w["pct_err"] = np.where(fc_w.actual != 0, fc_w.abs_err / fc_w.actual, np.nan)

per_week = pd.DataFrame({
    "n_sites": fc_w.groupby("date").size(),
    "zero_sites": fc_w.groupby("date").pct_err.apply(lambda s: int(s.isna().sum())),
    "mean_actual": fc_w.groupby("date").actual.mean(),
    "mean_pred": fc_w.groupby("date").pred.mean(),
    "MAPE": fc_w.groupby("date").pct_err.mean(),
    "RMSE": fc_w.groupby("date").sq_err.mean() ** 0.5,
})

print(f"{len(per_week)} weeks | MAPE best {per_week.MAPE.min():.1%} | "
      f"median {per_week.MAPE.median():.1%} | worst {per_week.MAPE.max():.1%}")
per_week.round(4)

8 weeks | MAPE best 7.3% | median 8.8% | worst 16.5%

            n_sites  zero_sites  mean_actual  mean_pred    MAPE     RMSE
date
2024-07-07       30           0     174.7333   166.0498  0.0796  24.9654
2024-07-14       30           0     175.2223   170.1783  0.1083  29.3001
2024-07-21       30           0     169.4383   160.0953  0.0841  20.3775
2024-07-28       30           0     157.9543   165.6577  0.1068  25.7499
2024-08-04       30           0     160.8960   162.2682  0.0725  18.0868
2024-08-11       30           0     162.0863   165.1459  0.0912  24.3033
2024-08-18       30           0     164.8863   178.1612  0.1646  46.5315
2024-08-25       30           0     163.2863   158.3180  0.0751  22.1114

## Weekly error, per site

In [130]:
per_site_w = pd.DataFrame({
    "n_weeks": fc_w.groupby("site_id").size(),
    "mean_actual": fc_w.groupby("site_id").actual.mean(),
    "MAPE": fc_w.groupby("site_id").pct_err.mean(),
    "RMSE": fc_w.groupby("site_id").sq_err.mean() ** 0.5,
}).sort_values("MAPE", ascending=False)

print(f"MAPE across sites: best {per_site_w.MAPE.min():.1%} | "
      f"median {per_site_w.MAPE.median():.1%} | worst {per_site_w.MAPE.max():.1%}")
per_site_w.round(4)

MAPE across sites: best 1.8% | median 9.5% | worst 25.9%

          n_weeks  mean_actual    MAPE     RMSE
site_id
SITE_008        8     193.2875  0.2587  49.7993
SITE_014        8     196.0475  0.2529  67.9911
SITE_016        8     201.5688  0.1845  33.3126
SITE_006        8     180.9462  0.1526  31.4631
SITE_021        8     213.8212  0.1471  33.3390
SITE_001        8     199.2613  0.1385  33.8575
SITE_007        8     214.1362  0.1375  41.7515
SITE_003        8     203.9312  0.1310  32.8341
SITE_020        8     199.9950  0.1299  30.7577
SITE_010        8     205.2512  0.1275  28.8183
SITE_030        8     201.3225  0.1249  29.9700
SITE_011        8     217.6175  0.1109  33.3272
SITE_025        8     224.9138  0.1051  36.0406
SITE_018        8     205.8050  0.1025  25.8953
SITE_022        8     198.7338  0.0985  23.3913
SITE_026        8     238.9738  0.0911  25.0983
SITE_013        8     192.2850  0.0879  18.5788
SITE_017        8     214.8512  0.0861  19.6690
SITE_028        8     170.3600  0.0843  15.2652
SITE_005        8     209.9338  0.0745  19.0298
SITE_024        8     192.5338  0.0740  20.1421
SITE_012        8      81.0862  0.0331   2.7599
SITE_023        8      74.5350  0.0313   2.4599
SITE_015        8      84.0000  0.0304   2.9849
SITE_009        8      78.8438  0.0260   2.2889
SITE_019        8      73.7075  0.0245   1.8114
SITE_004        8      74.5112  0.0242   2.0434
SITE_029        8      74.1325  0.0226   1.9176
SITE_002        8      80.7587  0.0225   2.2577
SITE_027        8      84.7362  0.0185   2.0787

## Daily vs weekly

In [131]:
rows_w = [
    {**score(val_w[TARGET], val_w["planned_pour_tonnes"]), "model": "planned_pour (weekly)"},
    {**score(fc_w.actual, fc_w.pred), "model": "SARIMAX (weekly)"},
]
comparison = pd.concat([results_tbl, pd.DataFrame(rows_w).set_index("model")[
    ["MAPE", "RMSE", "WAPE", "MAE", "bias"]]])
comparison.round(4)

                          MAPE     RMSE    WAPE      MAE     bias
model
baseline: planned_pour  0.3372  14.4142  0.3189   7.4622   7.4622
baseline: train mean    0.7077  16.6324  0.6094  14.2586   0.3923
SARIMAX (cleaned data)  0.2227   8.6128  0.2464   5.7653  -0.0305
planned_pour (weekly)   0.2698  73.4089  0.3004  49.8817  49.8817
SARIMAX (weekly)        0.0978  27.6856  0.1064  17.6734  -0.3286

**RMSE is not comparable across grains.** A weekly total is roughly seven times a
daily value, so its RMSE is larger by construction - that is arithmetic, not a
worse model. MAPE and WAPE are scale-relative and can be compared.

Aggregation also makes the problem mechanically easier: day-to-day noise cancels
when summed, and the 12.2% of zero-pour days disappear. A lower weekly MAPE is
therefore partly a real gain in usable accuracy and partly an easier question. The
figure that carries meaning is the **gap between SARIMAX and `planned_pour` at each
grain**, since both face the same conditions.

Weekly is also the grain MIG actually reorders on, which is the practical argument
for it regardless of the arithmetic.

---

# Experiment 3 - Engineered Features, Weekly Aggregation

Weekly grain again, but with the engineered features from notebook 03 as regressors
instead of the four raw columns.

Aggregation is per feature type rather than one blanket rule - summing a flag and
summing a tonnage mean different things:

| feature | rule | meaning at weekly grain |
|---|---|---|
| `planned_pour_tonnes` | sum | tonnes scheduled that week |
| `planned_pour_next_7/14` | last | schedule looking forward from week end |
| `pour_blocked_rain` | **sum** | days lost to rain that week |
| `frost` | **sum** | frost days that week |
| `rain_mm`, `avg_temp_c` | mean | average conditions |
| `opening_inventory_tonnes`, `inventory_vs_capacity`, `headroom_tonnes` | first | position entering the week |
| `cover_days_7`, `days_since_planned_pour` | first | state entering the week |

`pour_blocked_rain` is the interesting one: as a daily 0/1 flag it marks a single
lost day, but summed it becomes "how many pour days this week were rained off",
which is a genuinely different and more useful quantity.

Target lags and rolling means are **excluded**. SARIMAX already models the
autoregressive structure through its AR terms, so passing lagged target values as
exogenous regressors double-counts them and destabilises the fit.

In [132]:
feats = pd.read_parquet(settings.processed_dir / "operations_feature_engineered.parquet")
feats["date"] = pd.to_datetime(feats["date"])
feats = feats.sort_values(["site_id", "date"]).reset_index(drop=True)
print("engineered daily matrix:", feats.shape)

AGG_ENG = {
    "y": "sum",
    "planned_pour_tonnes": "sum",
    "planned_pour_next_7": "last",
    "planned_pour_next_14": "last",
    "pour_blocked_rain": "sum",
    "frost": "sum",
    "rain_mm": "mean",
    "avg_temp_c": "mean",
    "opening_inventory_tonnes": "first",
    "inventory_vs_capacity": "first",
    "headroom_tonnes": "first",
    "cover_days_7": "first",
    "days_since_planned_pour": "first",
}

grp_e = feats.set_index("date").groupby("site_id").resample("W")
weekly_eng = grp_e.agg(AGG_ENG).reset_index()
weekly_eng["n_days"] = grp_e.size().values

EXOG_ENG = [c for c in AGG_ENG if c != "y"]

before = len(weekly_eng)
partial_e = weekly_eng.n_days < 7
weekly_eng = (weekly_eng[~partial_e]
              .drop(columns="n_days")
              .dropna(subset=["y"] + EXOG_ENG)
              .sort_values(["site_id", "date"])
              .reset_index(drop=True))
print(f"partial weeks dropped: {partial_e.sum()}")
print(f"weekly engineered: {before:,} -> {len(weekly_eng):,} rows")
print(f"{len(EXOG_ENG)} regressors (weekly used 4)")
weekly_eng.head()

engineered daily matrix: (32880, 44)
partial weeks dropped: 60
weekly engineered: 4,740 -> 4,680 rows
12 regressors (weekly used 4)

,site_id,date,y,planned_pour_tonnes,planned_pour_next_7,planned_pour_next_14,pour_blocked_rain,frost,rain_mm,avg_temp_c,opening_inventory_tonnes,inventory_vs_capacity,headroom_tonnes,cover_days_7,days_since_planned_pour
0,SITE_001,2022-01-09,208.96,234.47,248.84,593.06,0,0,2.734286,13.060000,38.56,0.086071,409.44,0.388400,0.0
1,SITE_001,2022-01-16,269.66,286.58,344.22,687.46,0,1,3.372857,11.337143,34.38,0.076741,413.62,1.151704,0.0
2,SITE_001,2022-01-23,235.01,346.98,343.24,646.20,0,0,3.258571,12.935714,4.95,0.011049,443.05,0.128495,0.0
3,SITE_001,2022-01-30,235.11,341.55,302.96,619.21,0,0,7.021429,12.470000,7.22,0.016116,440.78,0.215055,0.0
4,SITE_001,2022-02-06,196.26,307.16,316.25,600.74,0,0,4.274286,17.685714,3.59,0.008013,444.41,0.106886,0.0

In [133]:
print("what the aggregated flags look like:")
print(weekly_eng[["pour_blocked_rain", "frost"]].describe().loc[
    ["mean", "50%", "max"]].round(2).to_string())
print(f"\nweeks with at least one rained-off day: "
      f"{(weekly_eng.pour_blocked_rain > 0).mean():.1%}")
print(f"weeks with at least one frost day:       {(weekly_eng.frost > 0).mean():.1%}")

what the aggregated flags look like:
      pour_blocked_rain  frost
mean               0.35   0.97
50%                0.00   0.00
max                4.00   7.00

weeks with at least one rained-off day: 30.1%
weeks with at least one frost day:       39.0%

## Split

In [134]:
de = weekly_eng["date"]
train_e = weekly_eng[de <= TRAIN_END]
val_e = weekly_eng[(de > TRAIN_END) & (de <= VAL_END)]
test_e = weekly_eng[de > VAL_END]

val_e = val_e.groupby("site_id").head(HORIZON_WEEKS).reset_index(drop=True)
test_e = test_e.groupby("site_id").head(HORIZON_WEEKS).reset_index(drop=True)

for name, part in [("train", train_e), ("val", val_e), ("test", test_e)]:
    print(f"{name:5s} {len(part):5,} rows  {part.date.min().date()} -> {part.date.max().date()}"
          f"  ({part.groupby('site_id').size().mean():.0f} weeks per site)")

train 3,900 rows  2022-01-09 -> 2024-06-30  (130 weeks per site)
val     240 rows  2024-07-07 -> 2024-08-25  (8 weeks per site)
test    240 rows  2024-10-06 -> 2024-11-24  (8 weeks per site)

## Order selection

In [135]:
aic_e = {}
for o in GRID:
    scores = []
    for site in sorted(train_e.site_id.unique())[:5]:
        g = train_e[train_e.site_id == site].set_index("date").asfreq("W")
        try:
            scores.append(SARIMAX(g[TARGET], exog=g[EXOG_ENG], order=o,
                                  seasonal_order=(0, 0, 0, 0)).fit(disp=False).aic)
        except Exception:
            pass
    aic_e[str(o)] = np.mean(scores) if scores else np.nan

aic_e = pd.Series(aic_e).sort_values()
print(aic_e.round(1).to_string())
ORDER_E = eval(aic_e.index[0])
print("\nselected:", ORDER_E)

(1, 0, 0)    904.9
(0, 0, 1)    904.9
(1, 0, 1)    906.7
(2, 0, 1)    908.4
(2, 0, 2)    909.1

selected: (1, 0, 0)

## Train the model

In [136]:
y_train_e = train_e[train_e.site_id == SITE].set_index("date").asfreq("W")[TARGET]
x_train_e = train_e[train_e.site_id == SITE].set_index("date").asfreq("W")[EXOG_ENG]
y_val_e = val_e[val_e.site_id == SITE].set_index("date").asfreq("W")[TARGET]
x_val_e = val_e[val_e.site_id == SITE].set_index("date").asfreq("W")[EXOG_ENG]

print(f"{SITE}: train {len(y_train_e)} weeks, val {len(y_val_e)} weeks, "
      f"{x_train_e.shape[1]} regressors")

SITE_001: train 130 weeks, val 8 weeks, 12 regressors

In [137]:
model_e = SARIMAX(
    y_train_e,
    exog=x_train_e,
    order=ORDER_E,
    seasonal_order=(0, 0, 0, 0),
    enforce_stationarity=True,
)

results_e = model_e.fit(disp=False)
results_e.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  130
Model:               SARIMAX(1, 0, 0)   Log Likelihood                -612.851
Date:                Thu, 13 Aug 2026   AIC                           1253.701
Time:                        10:04:31   BIC                           1293.847
Sample:                    01-09-2022   HQIC                          1270.014
                         - 06-30-2024
Covariance Type:                  opg
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
planned_pour_tonnes          0.2736      0.079      3.471      0.001       0.119       0.428
planned_pour_next_7          0.2846      0.124      2.296      0.022       0.042       0.527
planned_pour_next_14        -0.0258      0.080     -0.322      0.748      -0.183       0.131
pour_blocked_rain          -21.9364      6.703     -3.273      0.001     -35.074      -8.799
frost                       -4.9382      3.152     -1.567      0.117     -11.116       1.239
rain_mm                      2.2168      1.850      1.198      0.231      -1.410       5.844
avg_temp_c                  -0.4023      0.518     -0.776      0.438      -1.418       0.613
opening_inventory_tonnes     0.9318      0.506      1.843      0.065      -0.059       1.923
inventory_vs_capacity        0.0021      0.001      1.868      0.062      -0.000       0.004
headroom_tonnes              0.1149      0.094      1.225      0.221      -0.069       0.299
cover_days_7                 1.3714     11.409      0.120      0.904     -20.989      23.732
days_since_planned_pour     28.0348     35.009      0.801      0.423     -40.582      96.652
ar.L1                       -0.1034      0.108     -0.961      0.337      -0.314       0.107
sigma2                     717.8822     95.488      7.518      0.000     530.729     905.035
===================================================================================
Ljung-Box (L1) (Q):                   0.03   Jarque-Bera (JB):                 0.28
Prob(Q):                              0.87   Prob(JB):                         0.87
Heteroskedasticity (H):               1.24   Skew:                            -0.06
Prob(H) (two-sided):                  0.48   Kurtosis:                         2.80
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
[2] Covariance matrix is singular or near-singular, with condition number 1.42e+23. Standard errors may be unstable.
"""

## Predict

In [138]:
y_pred_e = results_e.predict(start=y_val_e.index[0], end=y_val_e.index[-1], exog=x_val_e)
y_pred_e = y_pred_e.clip(lower=0)

print(f"{SITE}")
print(f"  MAPE {mean_absolute_percentage_error(y_val_e, y_pred_e)*100:.1f}%")
print(f"  RMSE {np.sqrt(mean_squared_error(y_val_e, y_pred_e)):.3f} t")
y_pred_e

SITE_001
  MAPE 10.6%
  RMSE 24.848 t

2024-07-07    213.903540
2024-07-14    220.060381
2024-07-21    207.062832
2024-07-28    198.613912
2024-08-04    224.515011
2024-08-11    270.883056
2024-08-18    211.752612
2024-08-25    179.533710
Freq: W-SUN, Name: predicted_mean, dtype: float64

## Fit all 30 sites

In [139]:
models_e, preds_e = {}, []

for site, g_tr in train_e.groupby("site_id"):
    g_tr = g_tr.set_index("date").asfreq("W")
    g_va = val_e[val_e.site_id == site].sort_values("date").set_index("date").asfreq("W")

    try:
        res = SARIMAX(
            g_tr[TARGET],
            exog=g_tr[EXOG_ENG],
            order=ORDER_E,
            seasonal_order=(0, 0, 0, 0),
            enforce_stationarity=True,
        ).fit(disp=False)
        pred = res.predict(start=g_va.index[0], end=g_va.index[-1],
                           exog=g_va[EXOG_ENG]).clip(lower=0)
    except Exception:
        res, pred = None, pd.Series(np.nan, index=g_va.index)

    models_e[site] = res
    preds_e.append(pd.DataFrame({"date": g_va.index, "site_id": site,
                                 "actual": g_va[TARGET].values, "pred": pred.values}))

fc_e = pd.concat(preds_e, ignore_index=True).dropna(subset=["pred"])
conv_e = sum(m is not None for m in models_e.values())
print(f"sites: {len(models_e)} | converged: {conv_e} | failed: {len(models_e) - conv_e}")
print(f"{len(fc_e):,} predictions | {fc_e.date.nunique()} weeks x {fc_e.site_id.nunique()} sites")

sites: 30 | converged: 30 | failed: 0
240 predictions | 8 weeks x 30 sites

## Weekly error, per calendar week across all sites

In [140]:
fc_e["abs_err"] = (fc_e.actual - fc_e.pred).abs()
fc_e["sq_err"] = (fc_e.actual - fc_e.pred) ** 2
fc_e["pct_err"] = np.where(fc_e.actual != 0, fc_e.abs_err / fc_e.actual, np.nan)

per_week_e = pd.DataFrame({
    "n_sites": fc_e.groupby("date").size(),
    "mean_actual": fc_e.groupby("date").actual.mean(),
    "mean_pred": fc_e.groupby("date").pred.mean(),
    "MAPE": fc_e.groupby("date").pct_err.mean(),
    "RMSE": fc_e.groupby("date").sq_err.mean() ** 0.5,
})

print(f"{len(per_week_e)} weeks | MAPE best {per_week_e.MAPE.min():.1%} | "
      f"median {per_week_e.MAPE.median():.1%} | worst {per_week_e.MAPE.max():.1%}")
per_week_e.round(4)

8 weeks | MAPE best 5.1% | median 8.5% | worst 14.1%

            n_sites  mean_actual  mean_pred    MAPE     RMSE
date
2024-07-07       30     174.7333   171.3684  0.0908  27.5434
2024-07-14       30     175.2223   174.0078  0.0848  25.3198
2024-07-21       30     169.4383   166.8316  0.0506  15.3066
2024-07-28       30     157.9543   167.8049  0.0876  23.4669
2024-08-04       30     160.8960   165.9777  0.0622  17.7993
2024-08-11       30     162.0863   169.7436  0.0857  23.1437
2024-08-18       30     164.8863   176.7157  0.1411  39.2922
2024-08-25       30     163.2863   163.5309  0.0639  17.3137

## Weekly error, per site

In [141]:
per_site_e = pd.DataFrame({
    "n_weeks": fc_e.groupby("site_id").size(),
    "mean_actual": fc_e.groupby("site_id").actual.mean(),
    "MAPE": fc_e.groupby("site_id").pct_err.mean(),
    "RMSE": fc_e.groupby("site_id").sq_err.mean() ** 0.5,
}).sort_values("MAPE", ascending=False)

print(f"MAPE across sites: best {per_site_e.MAPE.min():.1%} | "
      f"median {per_site_e.MAPE.median():.1%} | worst {per_site_e.MAPE.max():.1%}")
per_site_e.round(4)

MAPE across sites: best 0.6% | median 8.0% | worst 22.1%

          n_weeks  mean_actual    MAPE     RMSE
site_id
SITE_008        8     193.2875  0.2213  43.3462
SITE_014        8     196.0475  0.2069  55.8339
SITE_016        8     201.5688  0.1976  36.7575
SITE_028        8     170.3600  0.1885  30.0937
SITE_006        8     180.9462  0.1715  36.8421
SITE_020        8     199.9950  0.1170  28.4876
SITE_030        8     201.3225  0.1118  29.8657
SITE_010        8     205.2512  0.1083  25.7862
SITE_001        8     199.2613  0.1057  24.8481
SITE_007        8     214.1362  0.1030  31.0019
SITE_003        8     203.9312  0.1024  29.1577
SITE_005        8     209.9338  0.0978  29.8757
SITE_017        8     214.8512  0.0963  26.0627
SITE_011        8     217.6175  0.0851  20.7745
SITE_022        8     198.7338  0.0839  20.1684
SITE_025        8     224.9138  0.0769  27.5487
SITE_026        8     238.9738  0.0724  20.2233
SITE_024        8     192.5338  0.0722  19.2631
SITE_021        8     213.8212  0.0718  18.1658
SITE_018        8     205.8050  0.0715  20.4661
SITE_013        8     192.2850  0.0445  13.6072
SITE_023        8      74.5350  0.0186   2.0997
SITE_004        8      74.5112  0.0155   1.6287
SITE_019        8      73.7075  0.0112   0.8634
SITE_027        8      84.7362  0.0093   1.0528
SITE_012        8      81.0862  0.0088   0.8125
SITE_015        8      84.0000  0.0085   1.0000
SITE_002        8      80.7587  0.0083   0.9222
SITE_009        8      78.8438  0.0078   0.7539
SITE_029        8      74.1325  0.0057   0.5685

## All experiments compared

In [142]:
final = pd.concat([
    comparison,
    pd.DataFrame([{**score(fc_e.actual, fc_e.pred),
                   "model": "SARIMAX (engineered, weekly)"}]).set_index("model")[
        ["MAPE", "RMSE", "WAPE", "MAE", "bias"]],
])
final.round(4)

                                MAPE     RMSE    WAPE      MAE     bias
model
baseline: planned_pour        0.3372  14.4142  0.3189   7.4622   7.4622
baseline: train mean          0.7077  16.6324  0.6094  14.2586   0.3923
SARIMAX (cleaned data)        0.2227   8.6128  0.2464   5.7653  -0.0305
planned_pour (weekly)         0.2698  73.4089  0.3004  49.8817  49.8817
SARIMAX (weekly)              0.0978  27.6856  0.1064  17.6734  -0.3286
SARIMAX (engineered, weekly)  0.0833  24.7002  0.0906  15.0413   3.4347

In [143]:
weekly_only = final.loc[["planned_pour (weekly)", "SARIMAX (weekly)",
                         "SARIMAX (engineered, weekly)"]]
weekly_only.assign(**{
    "MAPE vs raw-feature model": (
        weekly_only.MAPE / final.loc["SARIMAX (weekly)", "MAPE"] - 1
    ).map(lambda x: f"{x:+.1%}"),
    "meets MAPE <= 15%": weekly_only.MAPE.le(0.15).map({True: "yes", False: "no"}),
}).round(4)

                                MAPE     RMSE    WAPE      MAE     bias MAPE vs raw-feature model meets MAPE <= 15%
model
planned_pour (weekly)         0.2698  73.4089  0.3004  49.8817  49.8817                   +175.9%                no
SARIMAX (weekly)              0.0978  27.6856  0.1064  17.6734  -0.3286                     +0.0%               yes
SARIMAX (engineered, weekly)  0.0833  24.7002  0.0906  15.0413   3.4347                    -14.8%               yes

## Notes

- Cleaned dataset only, no engineered features.
- `deliveries_tonnes`, `closing_inventory_tonnes` and `silo_capacity` are excluded
  from the regressors. The first two satisfy
  `consumed = opening + deliveries - closing` exactly, so including them lets the
  model reproduce the target instead of forecasting it; the third is constant
  within a site and makes the covariance matrix singular.
- MAPE is computed on non-zero actuals; the raw sklearn value is in section 7.
- Weather regressors use actual validation values, which flatters the result.
- The Oct-Dec 2024 test split is untouched.

# Global Machine Learning Models
## Random Forest Regressor

In [144]:
print(clean.columns.tolist())

['date', 'site_id', 'cement_type', 'planned_pour_tonnes', 'consumed_tonnes', 'opening_inventory_tonnes', 'deliveries_tonnes', 'closing_inventory_tonnes', 'rain_mm', 'avg_temp_c', 'silo_capacity', 'region', 'behavior', 'received_tonnes', 'rejected_delivery_tonnes', 'served_tonnes', 'induced_shortfall', 'was_constrained', 'unmet_tonnes', 'silo_utilisation', 'cover_days', 'y']

In [145]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

## Prepare Features and Target

The machine learning model is trained using the pooled dataset across all sites. Predictor variables include operational, weather, inventory, and site-level characteristics that are available before or at the time a forecast is made.

The target variable is **y**, representing cement demand.

In [146]:
# Review fix: cover_days, silo_utilisation and deliveries_tonnes removed.
#
#   cover_days       = opening_inventory / consumed_tonnes  -> target recoverable
#                      as opening / cover_days (verified to 1.4e-14)
#   silo_utilisation = closing_inventory / silo_capacity    -> with silo_capacity
#                      also a feature, closing inventory is recoverable
#   deliveries_tonnes-> completes consumed = opening + deliveries - closing, and
#                      is not knowable at forecast time anyway
#
# Validation R2 with them: 0.9958. Without: 0.8765.

feature_cols = [
    "planned_pour_tonnes",
    "opening_inventory_tonnes",
    "rain_mm",
    "avg_temp_c",
    "silo_capacity",
    "site_id",
    "cement_type",
    "region",
    "behavior",
]

X_train = train[feature_cols]
y_train = train[TARGET]

X_val = val[feature_cols]
y_val = val[TARGET]

# X_test / y_test are deliberately not built here - the test split is scored once,
# in 06_Holdout_Validation.ipynb, after model selection is frozen.

print("Features:", len(feature_cols))
print("X_train:", X_train.shape)
print("X_val:  ", X_val.shape)

Features: 9
X_train: (27360, 9)
X_val:   (2760, 9)

## Data Preprocessing

The dataset contains a mixture of numerical and categorical features. To prepare the data for machine learning, numerical variables are imputed using the median, while categorical variables are imputed using the most frequent category and encoded using one-hot encoding.

These preprocessing steps are combined into a single pipeline to ensure the same transformations are consistently applied during both training and prediction.

In [147]:
categorical_features = [
    "site_id",
    "cement_type",
    "region",
    "behavior",
]

numerical_features = [
    col for col in feature_cols if col not in categorical_features
]

preprocessor = ColumnTransformer(
    transformers=[
        ( "num",SimpleImputer(strategy="median"),
            numerical_features, ),
            
        ( "cat",Pipeline([ ("imputer", SimpleImputer(strategy="most_frequent")),
                ("encoder", OneHotEncoder(handle_unknown="ignore")),]),
            categorical_features, ),])

print("Numerical Features:", numerical_features)
print("Categorical Features:", categorical_features)

Numerical Features: ['planned_pour_tonnes', 'opening_inventory_tonnes', 'rain_mm', 'avg_temp_c', 'silo_capacity']
Categorical Features: ['site_id', 'cement_type', 'region', 'behavior']

## Random Forest Model Development

A Random Forest Regressor is trained using the preprocessed dataset. Random Forest is an ensemble learning algorithm that combines multiple decision trees to improve predictive performance and reduce overfitting. The model is trained using the pooled dataset across all sites and will be evaluated on the validation set before comparison with the SARIMAX baseline.

In [148]:
rf_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model",RandomForestRegressor(
                n_estimators=200,
                max_depth=15,
                min_samples_split=5,
                min_samples_leaf=2,
                random_state=42,
                n_jobs=-1,),),])

print("Training Random Forest model...")

rf_pipeline.fit(X_train, y_train)

print("Training completed.")

Training Random Forest model...
Training completed.

## Model Validation

The trained Random Forest model is evaluated using the validation dataset. Performance is measured using Root Mean Squared Error (RMSE), Mean Absolute Error (MAE), and Mean Absolute Percentage Error (MAPE). These metrics provide an objective basis for comparing the machine learning model with the SARIMAX baseline.

In [149]:
from mig_cement.models.evaluate import evaluate

# Validation predictions
y_pred = rf_pipeline.predict(X_val)

# Evaluate
rf_metrics = evaluate(
    y_true=y_val,
    y_pred=y_pred,
    y_train=y_train,)

print("=" * 60)
print("Random Forest Validation Results")
print("=" * 60)

for metric, value in rf_metrics.items():
    print(f"{metric:<18}: {value:.4f}")

============================================================
Random Forest Validation Results
============================================================
WAPE              : 0.1280
RMSE              : 5.8735
MAE               : 2.9957
bias              : 0.1196
MAPE_nonzero      : 0.1409
pct_zero_actual   : 0.1199
MASE              : 0.1995

## Test Set Evaluation

After validating the Random Forest model, its performance is assessed on the held-out test dataset. The test set was not used during model training or model selection, providing an unbiased estimate of the model's generalisation performance.

## Hyperparameter Tuning for Random Forest

The baseline Random Forest model is further optimised using hyperparameter tuning. Randomized Search is employed to explore a range of parameter combinations while keeping the computational cost manageable. The objective is to identify the model configuration that produces the best validation performance.

In [150]:
from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit

param_dist = {
    "model__n_estimators": [200, 300, 500],
    "model__max_depth": [10, 15, 20, None],
    "model__min_samples_split": [2, 5, 10],
    "model__min_samples_leaf": [1, 2, 4],
    "model__max_features": ["sqrt", "log2"],}

In [151]:
rf_search = RandomizedSearchCV(
    estimator=rf_pipeline,
    param_distributions=param_dist,
    n_iter=15,
    cv=TimeSeriesSplit(n_splits=3),   # review fix: was cv=3 (random KFold)
    scoring="neg_root_mean_squared_error",
    random_state=42,
    n_jobs=-1,
    verbose=2,
)

print("Tuning Random Forest...")

rf_search.fit(X_train, y_train)

print("Done.")

print("Best Parameters")
print(rf_search.best_params_)

print("\nBest CV Score")
print(rf_search.best_score_)

Tuning Random Forest...
Fitting 3 folds for each of 15 candidates, totalling 45 fits
Done.
Best Parameters
{'model__n_estimators': 200, 'model__min_samples_split': 5, 'model__min_samples_leaf': 1, 'model__max_features': 'sqrt', 'model__max_depth': 20}

Best CV Score
-6.664696640673736

### Validation Performance

In [152]:
best_rf = rf_search.best_estimator_

y_pred = best_rf.predict(X_val)

best_rf_metrics = evaluate(
    y_true=y_val,
    y_pred=y_pred,
    y_train=y_train,
)

print("=" * 60)
print("Tuned Random Forest Validation Results")
print("=" * 60)

for metric, value in best_rf_metrics.items():
    print(f"{metric:<18}: {value:.4f}")

============================================================
Tuned Random Forest Validation Results
============================================================
WAPE              : 0.1803
RMSE              : 6.3363
MAE               : 4.2184
bias              : 0.2737
MAPE_nonzero      : 0.1836
pct_zero_actual   : 0.1199
MASE              : 0.2809

_Test evaluation moved to `06_Holdout_Validation.ipynb` - the test split is scored once, after model selection is frozen._

## Model Selection

Hyperparameter tuning was performed using RandomizedSearchCV with `TimeSeriesSplit`. The tuned model did not outperform the baseline Random Forest **on validation**, so the baseline Random Forest was retained for comparison against the other models.

Selection is made on validation only; the test split is untouched here.

## LightGBM Model Development

LightGBM is a gradient boosting algorithm designed for high performance on structured datasets. Unlike Random Forest, which builds trees independently, LightGBM constructs trees sequentially, allowing each new tree to correct the errors of the previous ones.

The model is trained using the same preprocessing pipeline and time-based train, validation, and test split as the Random Forest model to ensure a fair comparison.

In [153]:
from lightgbm import LGBMRegressor

lgbm_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ( "model",LGBMRegressor(
                n_estimators=300,
                learning_rate=0.05,
                num_leaves=31,
                max_depth=10,
                subsample=0.8,
                colsample_bytree=0.8,
                random_state=42,
                verbosity=-1,),  ), ])

print("Training LightGBM model...")

lgbm_pipeline.fit(X_train, y_train)

print("LightGBM training completed.")

Training LightGBM model...
LightGBM training completed.

## LightGBM Validation

The trained LightGBM model is evaluated using the validation dataset. The same evaluation metrics used for the Random Forest model are applied to ensure a consistent comparison between the machine learning models.

In [154]:
y_pred_lgbm = lgbm_pipeline.predict(X_val)

lgbm_val_metrics = evaluate(
    y_true=y_val,
    y_pred=y_pred_lgbm,
    y_train=y_train,)

print("=" * 60)
print("LightGBM Validation Results")
print("=" * 60)

for metric, value in lgbm_val_metrics.items():
    print(f"{metric:<18}: {value:.4f}")

============================================================
LightGBM Validation Results
============================================================
WAPE              : 0.1354
RMSE              : 5.8702
MAE               : 3.1674
bias              : 0.1960
MAPE_nonzero      : 0.1487
pct_zero_actual   : 0.1199
MASE              : 0.2109

## LightGBM Test Evaluation

The selected LightGBM model is evaluated on the held-out test dataset to assess its ability to generalise to unseen observations. This provides a direct comparison with the Random Forest and SARIMAX models.

## 5.1 Weekly Data Aggregation

Because the forecasting objective is an eight-week horizon, the daily cleaned dataset is aggregated to weekly observations. The aggregation is performed separately for each site and cement type to preserve the individual demand series.

Flow variables such as cement consumption, planned pours, and deliveries are summed over each week, while state and environmental variables are aggregated using appropriate summary statistics.

In [155]:
# Weekly Data Aggregation
# ============================================

import pandas as pd
import numpy as np

# Make a copy so the original daily dataset remains unchanged
weekly = clean.copy()

# Ensure date is in datetime format
weekly["date"] = pd.to_datetime(weekly["date"])

# Create a week-start column
# Monday is used as the start of the forecasting week
weekly["week"] = weekly["date"].dt.to_period("W-SUN").dt.start_time

# Aggregate daily observations to weekly level
weekly = (weekly.groupby(["week", "site_id", "cement_type", "region", "behavior"],
        as_index=False).agg(
# Target and flow variables → SUM
        consumed_tonnes=("consumed_tonnes", "sum"),
        planned_pour_tonnes=("planned_pour_tonnes", "sum"),
        deliveries_tonnes=("deliveries_tonnes", "sum"),
        rain_mm=("rain_mm", "sum"),

        # State variables → FIRST/LAST
        opening_inventory_tonnes=("opening_inventory_tonnes", "first"),
        silo_capacity=("silo_capacity", "last"),

        # Environmental / utilisation variables → MEAN
        avg_temp_c=("avg_temp_c", "mean"),
        cover_days=("cover_days", "mean"),
        silo_utilisation=("silo_utilisation", "mean"),))

# Sort chronologically
weekly = weekly.sort_values(
    ["site_id", "cement_type", "week"]
).reset_index(drop=True)

print("Weekly dataset shape:", weekly.shape)

print("\nDate range:")
print(weekly["week"].min(), "to", weekly["week"].max())

print("\nNumber of sites:", weekly["site_id"].nunique())
print("Number of cement types:", weekly["cement_type"].nunique())

print("\nWeekly dataset preview:")
display(weekly.head())

Weekly dataset shape: (13337, 14)

Date range:
2021-12-27 00:00:00 to 2024-12-30 00:00:00

Number of sites: 30
Number of cement types: 3

Weekly dataset preview:

,week,site_id,cement_type,region,behavior,consumed_tonnes,planned_pour_tonnes,deliveries_tonnes,rain_mm,opening_inventory_tonnes,silo_capacity,avg_temp_c,cover_days,silo_utilisation
0,2021-12-27,SITE_001,CEM_I,North,aggressive,45.26,45.26,19.97,3.23,63.85,448,14.2800,1.410738,0.086071
1,2022-01-03,SITE_001,CEM_I,North,aggressive,101.04,108.88,121.00,12.52,47.06,448,15.3600,0.610361,0.045279
2,2022-01-10,SITE_001,CEM_I,North,aggressive,80.42,89.89,29.99,4.68,44.66,448,14.5700,0.838604,0.018605
3,2022-01-24,SITE_001,CEM_I,North,aggressive,126.46,131.07,122.22,23.55,7.22,448,14.2300,0.078625,0.004174
4,2022-01-31,SITE_001,CEM_I,North,aggressive,102.18,158.33,98.59,21.11,3.59,448,16.7475,0.153731,0.006200

## 5.2 Weekly Data Quality Check

Before feature engineering and model training, the weekly dataset is checked for missing values, missing weekly observations, duplicate site-cement-week combinations, and the number of observations available for each demand series.

In [156]:
# Weekly Data Quality Checks
# ============================================

# 1. Missing values
print("=" * 60)
print("Missing Values")
print("=" * 60)

missing = weekly.isna().sum()
missing = missing[missing > 0].sort_values(ascending=False)

if len(missing) > 0:
    print(missing)
else:
    print("No missing values found.")


# 2. Check for duplicate site-cement-week combinations
print("\n" + "=" * 60)
print("Duplicate Weekly Observations")
print("=" * 60)

duplicates = weekly.duplicated(
    subset=["week", "site_id", "cement_type"]
).sum()

print("Duplicate rows:", duplicates)


# 3. Number of observations per series
print("\n" + "=" * 60)
print("Observations Per Site-Cement Series")
print("=" * 60)

series_counts = ( weekly
    .groupby(["site_id", "cement_type"])
    .size()
    .describe())

print(series_counts)


# 4. Check missing weeks within each site-cement series
print("\n" + "=" * 60)
print("Missing Weekly Observations")
print("=" * 60)

weekly["week"] = pd.to_datetime(weekly["week"])

missing_week_records = []

for (site, cement), group in weekly.groupby(
    ["site_id", "cement_type"]):
    
    dates = group["week"].sort_values()
    
    expected_weeks = pd.date_range(
        start=dates.min(),
        end=dates.max(),
        freq="7D")
    
    actual_weeks = pd.DatetimeIndex(dates.unique())
    
    missing_weeks = expected_weeks.difference(actual_weeks)
    
    if len(missing_weeks) > 0:
        missing_week_records.append({
            "site_id": site,
            "cement_type": cement,
            "missing_weeks": len(missing_weeks),
            "first_missing_week": missing_weeks.min(),
            "last_missing_week": missing_weeks.max() })


missing_week_df = pd.DataFrame(missing_week_records)

if missing_week_df.empty:
    print("No missing weeks detected within the series.")
else:
    print(
        f"Series with missing weeks: "
        f"{len(missing_week_df)}")
    
    display(
        missing_week_df.head(20) )

============================================================
Missing Values
============================================================
cover_days    486
dtype: int64

============================================================
Duplicate Weekly Observations
============================================================
Duplicate rows: 0

============================================================
Observations Per Site-Cement Series
============================================================
count     90.000000
mean     148.188889
std        2.608949
min      140.000000
25%      146.000000
50%      148.000000
75%      150.000000
max      153.000000
dtype: float64

============================================================
Missing Weekly Observations
============================================================
Series with missing weeks: 90

     site_id cement_type  missing_weeks first_missing_week last_missing_week
0   SITE_001       CEM_I             11         2022-01-17        2024-06-17
1   SITE_001      CEM_II              7         2022-02-21        2024-09-30
2   SITE_001     CEM_III             14         2022-02-07        2024-10-07
3   SITE_002       CEM_I             10         2022-01-03        2024-09-02
4   SITE_002      CEM_II             10         2022-02-07        2024-12-09
5   SITE_002     CEM_III              8         2022-07-11        2024-12-16
6   SITE_003       CEM_I              4         2022-08-01        2024-07-22
7   SITE_003      CEM_II              7         2022-03-21        2023-12-11
8   SITE_003     CEM_III             13         2022-01-10        2024-01-29
9   SITE_004       CEM_I              6         2022-10-10        2024-12-09
10  SITE_004      CEM_II              7         2022-01-24        2024-10-14
11  SITE_004     CEM_III             16         2022-05-09        2024-11-18
12  SITE_005       CEM_I             10         2022-04-04        2024-11-11
13  SITE_005      CEM_II             10         2022-03-07        2024-08-05
14  SITE_005     CEM_III              9         2022-02-28        2024-10-14
15  SITE_006       CEM_I             15         2022-01-24        2024-10-21
16  SITE_006      CEM_II              9         2022-01-17        2024-11-18
17  SITE_006     CEM_III              7         2022-05-30        2024-11-04
18  SITE_007       CEM_I              5         2022-04-11        2024-04-15
19  SITE_007      CEM_II             10         2022-01-31        2024-12-02

## 5.3 Investigating a Missing Week

The identified missing week is checked against the original daily dataset to determine whether the absence represents a genuine zero-activity period or missing data.

In [157]:
# Check one specific missing week

SITE_CHECK = "SITE_001"
CEMENT_CHECK = "CEM_I"
WEEK_CHECK = pd.Timestamp("2022-01-17")

check = clean[
    (clean["site_id"] == SITE_CHECK) &
    (clean["cement_type"] == CEMENT_CHECK) &
    (clean["date"] >= WEEK_CHECK) &
    (clean["date"] < WEEK_CHECK + pd.Timedelta(days=7))
]

print("Site:", SITE_CHECK)
print("Cement:", CEMENT_CHECK)
print("Week:", WEEK_CHECK.date())
print("\nNumber of daily records found:", len(check))

print("\nDaily records:")
display(check)

Site: SITE_001
Cement: CEM_I
Week: 2022-01-17

Number of daily records found: 0

Daily records:

Empty DataFrame
Columns: [date, site_id, cement_type, planned_pour_tonnes, consumed_tonnes, opening_inventory_tonnes, deliveries_tonnes, closing_inventory_tonnes, rain_mm, avg_temp_c, silo_capacity, region, behavior, received_tonnes, rejected_delivery_tonnes, served_tonnes, induced_shortfall, was_constrained, unmet_tonnes, silo_utilisation, cover_days, y]
Index: []

## 5.4 Create Complete Weekly Panel

Weeks with no recorded activity are retained in the weekly dataset so that each site-cement demand series has a continuous weekly timeline. This is important for creating lag features and forecasting an eight-week horizon.

In [158]:
# ============================================
# Create Complete Weekly Panel
# ============================================

# Make sure week is datetime
weekly["week"] = pd.to_datetime(weekly["week"])

# Create complete weekly date range
all_weeks = pd.date_range(
    start=weekly["week"].min(),
    end=weekly["week"].max(),
    freq="7D")

# Get all unique site-cement combinations
series = weekly[
    ["site_id", "cement_type", "region", "behavior"]].drop_duplicates()

# Create every possible week × site × cement combination
complete_index = pd.MultiIndex.from_product(
    [ all_weeks,
        series["site_id"].unique(),
        series["cement_type"].unique()],
    names=["week", "site_id", "cement_type"]).to_frame(index=False)

# Add region and behaviour information
series_info = series.drop_duplicates(
    ["site_id", "cement_type"])

complete_weekly = complete_index.merge(
    series_info,
    on=["site_id", "cement_type"],
    how="left")

# Merge the actual weekly observations
complete_weekly = complete_weekly.merge(
    weekly,
    on=[
        "week",
        "site_id",
        "cement_type",
        "region",
        "behavior"
    ],
    how="left")

# Sort the dataset
complete_weekly = complete_weekly.sort_values(
    ["site_id", "cement_type", "week"]
).reset_index(drop=True)

print("Original weekly rows:", len(weekly))
print("Complete weekly rows:", len(complete_weekly))

print(
    "Expected rows:",
    len(all_weeks) * len(series_info))

display(complete_weekly.head(20))

Original weekly rows: 13337
Complete weekly rows: 14220
Expected rows: 14220

,week,site_id,cement_type,region,behavior,consumed_tonnes,planned_pour_tonnes,deliveries_tonnes,rain_mm,opening_inventory_tonnes,silo_capacity,avg_temp_c,cover_days,silo_utilisation
0,2021-12-27,SITE_001,CEM_I,North,aggressive,45.26,45.26,19.97,3.23,6.385000e+01,448.0,14.280000,1.410738e+00,8.607143e-02
1,2022-01-03,SITE_001,CEM_I,North,aggressive,101.04,108.88,121.00,12.52,4.706000e+01,448.0,15.360000,6.103606e-01,4.527902e-02
2,2022-01-10,SITE_001,CEM_I,North,aggressive,80.42,89.89,29.99,4.68,4.466000e+01,448.0,14.570000,8.386042e-01,1.860491e-02
3,2022-01-17,SITE_001,CEM_I,North,aggressive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-01-24,SITE_001,CEM_I,North,aggressive,126.46,131.07,122.22,23.55,7.220000e+00,448.0,14.230000,7.862465e-02,4.174107e-03
5,2022-01-31,SITE_001,CEM_I,North,aggressive,102.18,158.33,98.59,21.11,3.590000e+00,448.0,16.747500,1.537310e-01,6.199777e-03
6,2022-02-07,SITE_001,CEM_I,North,aggressive,74.62,129.68,60.06,8.31,1.456000e+01,448.0,8.686667,9.898701e-02,4.758099e-17
7,2022-02-14,SITE_001,CEM_I,North,aggressive,41.89,91.86,39.79,9.01,2.100000e+00,448.0,20.595000,7.023411e-02,4.956353e-17
8,2022-02-21,SITE_001,CEM_I,North,aggressive,184.58,336.87,191.44,34.12,7.180000e+00,448.0,16.684286,1.603580e-01,1.044005e-02
9,2022-02-28,SITE_001,CEM_I,North,aggressive,137.74,147.61,122.43,7.74,2.131628e-14,448.0,18.196667,1.530464e-01,5.037202e-03
10,2022-03-07,SITE_001,CEM_I,North,aggressive,118.06,241.32,118.06,12.17,2.842171e-14,448.0,21.142000,1.623902e-15,6.344132e-17
11,2022-03-14,SITE_001,CEM_I,North,aggressive,30.41,30.41,37.67,2.68,2.842171e-14,448.0,26.690000,9.346172e-16,1.620536e-02
12,2022-03-21,SITE_001,CEM_I,North,aggressive,90.57,116.30,59.85,3.89,3.072000e+01,448.0,21.970000,2.851309e-01,1.586033e-17
13,2022-03-28,SITE_001,CEM_I,North,aggressive,67.20,113.55,67.20,11.46,7.105427e-15,448.0,17.196667,3.543867e-16,1.586033e-17
14,2022-04-04,SITE_001,CEM_I,North,aggressive,75.99,98.48,52.56,12.36,5.352000e+01,448.0,17.040000,5.702110e-01,3.358259e-02
15,2022-04-11,SITE_001,CEM_I,North,aggressive,67.05,101.42,67.05,12.31,0.000000e+00,448.0,13.125000,0.000000e+00,0.000000e+00
16,2022-04-18,SITE_001,CEM_I,North,aggressive,37.07,37.07,46.31,0.90,0.000000e+00,448.0,20.910000,0.000000e+00,2.062500e-02
17,2022-04-25,SITE_001,CEM_I,North,aggressive,85.87,124.62,104.42,17.38,0.000000e+00,448.0,13.213333,4.968288e-02,1.590030e-02
18,2022-05-02,SITE_001,CEM_I,North,aggressive,89.33,142.12,54.98,9.76,1.330000e+01,448.0,22.276667,5.101635e-01,1.152530e-02
19,2022-05-09,SITE_001,CEM_I,North,aggressive,74.29,116.21,79.09,34.00,1.549000e+01,448.0,20.060000,1.965784e+00,1.244048e-01

## 5.5 Handling No-Activity Weeks

Weeks with no recorded activity for a site-cement combination are represented explicitly in the weekly panel. Demand and operational flow variables are set to zero for these periods, while environmental and inventory-related variables are handled separately rather than being replaced indiscriminately with zero.

In [159]:
# ============================================
# Diagnose Newly Created No-Activity Weeks
# ============================================

# Identify rows where no weekly observation existed
no_activity = complete_weekly["consumed_tonnes"].isna()

print("No-activity weekly rows:", no_activity.sum())

print("\nPercentage of weekly panel:")
print(f"{no_activity.mean() * 100:.2f}%")

print("\nNo-activity rows by site:")
display(
    complete_weekly.loc[no_activity]
    .groupby("site_id")
    .size()
    .sort_values(ascending=False)
    .head(10))

print("\nNo-activity rows by cement type:")
display(
    complete_weekly.loc[no_activity]
    .groupby("cement_type")
    .size()
    .sort_values(ascending=False))

No-activity weekly rows: 883

Percentage of weekly panel:
6.21%

No-activity rows by site:

site_id
SITE_001    35
SITE_025    35
SITE_017    34
SITE_022    33
SITE_009    33
SITE_006    33
SITE_019    32
SITE_007    32
SITE_016    32
SITE_028    31
dtype: int64

No-activity rows by cement type:

cement_type
CEM_III    316
CEM_I      298
CEM_II     269
dtype: int64

## 5.6 Handling Zero-Activity Weeks

Weekly observations with no recorded activity for a site-cement combination are retained in the forecasting panel. Since no operational record exists for these periods, consumption, planned pour and deliveries are treated as zero. Environmental and inventory variables are not assigned zero values because their absence does not imply zero environmental conditions or zero inventory.

In [160]:
# ============================================
# Fill Zero-Activity Flow Variables
# ============================================

zero_activity_cols = [
    "consumed_tonnes",
    "planned_pour_tonnes",
    "deliveries_tonnes",]

for col in zero_activity_cols:
    complete_weekly[col] = complete_weekly[col].fillna(0)

print("Remaining missing values:")
print(
    complete_weekly.isna().sum()
    .sort_values(ascending=False))

Remaining missing values:
cover_days                  1369
silo_utilisation             883
rain_mm                      883
silo_capacity                883
opening_inventory_tonnes     883
avg_temp_c                   883
consumed_tonnes                0
behavior                       0
region                         0
cement_type                    0
site_id                        0
week                           0
planned_pour_tonnes            0
deliveries_tonnes              0
dtype: int64

## 5.7 Reconstruct Weekly Weather Variables

Weekly weather variables are calculated from the original daily cleaned dataset so that weeks with no cement activity still retain the corresponding environmental conditions. Rainfall is aggregated as weekly total precipitation, while temperature is represented by the weekly mean.

In [161]:
# ============================================
# Reconstruct Weekly Weather
# ============================================

# Make sure date is datetime
clean["date"] = pd.to_datetime(clean["date"])

# Create week-start column
weather = clean.copy()

weather["week"] = (
    weather["date"]
    .dt.to_period("W-SUN")
    .dt.start_time)

# Aggregate weather by week and site
weekly_weather = (
    weather
    .groupby(["week", "site_id"], as_index=False)
    .agg(
        rain_mm=("rain_mm", "sum"),
        avg_temp_c=("avg_temp_c", "mean")))

print("Weekly weather shape:", weekly_weather.shape)

display(weekly_weather.head())

Weekly weather shape: (4740, 4)

        week   site_id  rain_mm  avg_temp_c
0 2021-12-27  SITE_001     6.63       5.590
1 2021-12-27  SITE_002    10.34       5.325
2 2021-12-27  SITE_003     7.35      10.170
3 2021-12-27  SITE_004     5.77       9.205
4 2021-12-27  SITE_005    29.98      20.310

In [162]:
# Merge weekly weather into the complete panel

complete_weekly = complete_weekly.drop(
    columns=["rain_mm", "avg_temp_c"],
    errors="ignore")

complete_weekly = complete_weekly.merge(
    weekly_weather,
    on=["week", "site_id"],
    how="left")

print("\nMissing values after weather merge:")

print(
    complete_weekly[
        ["rain_mm", "avg_temp_c"]
    ].isna().sum())

Missing values after weather merge:
rain_mm       0
avg_temp_c    0
dtype: int64

## 5.8 Investigating Inventory and Silo Capacity

Inventory and silo-capacity variables are investigated before imputation to determine whether these values are stable at site level and can therefore be recovered for weeks with no activity.

In [163]:
# ============================================
# Investigate Silo Capacity
# ============================================

print("=" * 60)
print("Silo Capacity by Site")
print("=" * 60)

capacity_check = ( clean
    .groupby(["site_id", "cement_type"])["silo_capacity"]
    .agg(
        count="count",
        unique_values="nunique",
        minimum="min",
        maximum="max")
    .reset_index())

display(capacity_check.head(20))

============================================================
Silo Capacity by Site
============================================================

     site_id cement_type  count  unique_values  minimum  maximum
0   SITE_001       CEM_I    375              1      448      448
1   SITE_001      CEM_II    374              1      448      448
2   SITE_001     CEM_III    347              1      448      448
3   SITE_002       CEM_I    357              1      288      288
4   SITE_002      CEM_II    350              1      288      288
5   SITE_002     CEM_III    389              1      288      288
6   SITE_003       CEM_I    384              1      314      314
7   SITE_003      CEM_II    394              1      314      314
8   SITE_003     CEM_III    318              1      314      314
9   SITE_004       CEM_I    391              1      472      472
10  SITE_004      CEM_II    377              1      472      472
11  SITE_004     CEM_III    328              1      472      472
12  SITE_005       CEM_I    366              1      230      230
13  SITE_005      CEM_II    365              1      230      230
14  SITE_005     CEM_III    365              1      230      230
15  SITE_006       CEM_I    341              1      443      443
16  SITE_006      CEM_II    378              1      443      443
17  SITE_006     CEM_III    377              1      443      443
18  SITE_007       CEM_I    381              1      485      485
19  SITE_007      CEM_II    362              1      485      485

In [164]:
# Check whether silo capacity is consistent within each site

site_capacity_check = (
    clean
    .groupby("site_id")["silo_capacity"]
    .nunique())

print("Sites with one unique silo capacity:")
print((site_capacity_check == 1).sum())

print("\nSites with more than one silo capacity:")
print((site_capacity_check > 1).sum())

print("\nMaximum number of unique capacities at a site:")
print(site_capacity_check.max())

Sites with one unique silo capacity:
30

Sites with more than one silo capacity:
0

Maximum number of unique capacities at a site:
1

## 5.9 Recover Site-Level Silo Capacity

Silo capacity was found to be constant within each site across all cement types and observation periods. Therefore, missing weekly silo-capacity values are recovered using the known capacity for the corresponding site.

In [165]:
# ============================================
# Recover Site-Level Silo Capacity
# ============================================

# Create a site-level capacity lookup
site_capacity = (
    clean[["site_id", "silo_capacity"]]
    .dropna()
    .drop_duplicates())

# Check that there is only one capacity per site
assert (
    site_capacity.groupby("site_id")["silo_capacity"]
    .nunique()
    .max()
    == 1), "Silo capacity is not constant within at least one site."

# Merge site-level capacity into complete weekly data
complete_weekly = complete_weekly.drop(
    columns=["silo_capacity"],
    errors="ignore")

complete_weekly = complete_weekly.merge(
    site_capacity,
    on="site_id",
    how="left")

print(
    "Missing silo_capacity:",
    complete_weekly["silo_capacity"].isna().sum())

Missing silo_capacity: 0

## 5.10 Investigating Opening Inventory

Opening inventory is investigated to determine whether missing values can be reconstructed from the temporal inventory relationship rather than being replaced with arbitrary values.

In [166]:
# ============================================
# Investigate Opening Inventory
# ============================================

inventory_check = (
    clean
    .groupby(["site_id", "cement_type"])
    .agg(
        observations=("opening_inventory_tonnes", "count"),
        missing=("opening_inventory_tonnes", lambda x: x.isna().sum()),
        minimum=("opening_inventory_tonnes", "min"),
        maximum=("opening_inventory_tonnes", "max")
    )
    .reset_index())

print("=" * 60)
print("Opening Inventory by Site-Cement Series")
print("=" * 60)

display(inventory_check.head(20))

print("\nTotal missing opening inventory:")
print(
    clean["opening_inventory_tonnes"].isna().sum())

============================================================
Opening Inventory by Site-Cement Series
============================================================

     site_id cement_type  observations  missing  minimum  maximum
0   SITE_001       CEM_I           375        0     0.00   137.43
1   SITE_001      CEM_II           374        0     0.00   101.98
2   SITE_001     CEM_III           347        0     0.00   140.58
3   SITE_002       CEM_I           357        0    24.88   288.00
4   SITE_002      CEM_II           350        0    40.97   288.00
5   SITE_002     CEM_III           389        0    50.97   288.00
6   SITE_003       CEM_I           384        0     0.00   217.66
7   SITE_003      CEM_II           394        0     0.00   237.91
8   SITE_003     CEM_III           318        0     0.00   266.10
9   SITE_004       CEM_I           391        0    24.47   472.00
10  SITE_004      CEM_II           377        0    61.14   472.00
11  SITE_004     CEM_III           328        0   108.10   472.00
12  SITE_005       CEM_I           366        0     0.00    99.70
13  SITE_005      CEM_II           365        0     0.00   112.02
14  SITE_005     CEM_III           365        0     0.00   126.18
15  SITE_006       CEM_I           341        0     0.00   369.98
16  SITE_006      CEM_II           378        0     0.00   371.02
17  SITE_006     CEM_III           377        0     0.00   381.39
18  SITE_007       CEM_I           381        0     0.00   113.16
19  SITE_007      CEM_II           362        0     0.00    80.75

Total missing opening inventory:
0

In [167]:
# ============================================
# Check Inventory Balance Equation
# ============================================

inventory_balance = (
    clean["opening_inventory_tonnes"]
    + clean["deliveries_tonnes"]
    - clean["consumed_tonnes"])

difference = (
    clean["closing_inventory_tonnes"]
    - inventory_balance)

print("=" * 60)
print("Inventory Balance Check")
print("=" * 60)

print("Maximum absolute difference:")
print(difference.abs().max())

print("\nMean absolute difference:")
print(difference.abs().mean())

print("\nRows within 0.01 tonnes:")
print(
    (difference.abs() <= 0.01).mean() * 100,
    "%")

============================================================
Inventory Balance Check
============================================================
Maximum absolute difference:
67.96

Mean absolute difference:
5.739786496350365

Rows within 0.01 tonnes:
71.05231143552312 %

## 5.11 Weekly Lag Features

Historical weekly consumption features are created for each site-cement series. These lag features capture recent demand behaviour and provide the machine-learning models with temporal information for weekly demand forecasting.

In [168]:
# ============================================
# Create Weekly Lag Features
# ============================================

# Ensure correct ordering
complete_weekly = complete_weekly.sort_values(
    ["site_id", "cement_type", "week"]
).reset_index(drop=True)

# Create historical consumption lags
group_cols = ["site_id", "cement_type"]

complete_weekly["consumed_lag_1"] = (
    complete_weekly
    .groupby(group_cols)["consumed_tonnes"]
    .shift(1))

complete_weekly["consumed_lag_2"] = (
    complete_weekly
    .groupby(group_cols)["consumed_tonnes"]
    .shift(2))

complete_weekly["consumed_lag_4"] = (
    complete_weekly
    .groupby(group_cols)["consumed_tonnes"]
    .shift(4))

complete_weekly["consumed_lag_8"] = (
    complete_weekly
    .groupby(group_cols)["consumed_tonnes"]
    .shift(8))

print("Weekly dataset shape:", complete_weekly.shape)

print("\nMissing lag values:")
print(
    complete_weekly[
        [
            "consumed_lag_1",
            "consumed_lag_2",
            "consumed_lag_4",
            "consumed_lag_8"
        ]
    ].isna().sum())

Weekly dataset shape: (14220, 18)

Missing lag values:
consumed_lag_1     90
consumed_lag_2    180
consumed_lag_4    360
consumed_lag_8    720
dtype: int64

## 5.12 Time-Based Train, Validation and Test Split

A chronological split is used to preserve the temporal structure of the forecasting problem and prevent future observations from influencing model training. The training period covers January 2022 to June 2024, the validation period covers July to September 2024, and the test period covers October to December 2024. The test set is held out until final model selection.

In [169]:
# ============================================
# Time-Based Train / Validation / Test Split
# ============================================

TRAIN_END = pd.Timestamp("2024-06-30")
VAL_END = pd.Timestamp("2024-09-30")

# Remove rows where lag_8 is unavailable
# These are only the first 8 weeks of each series.
model_data = complete_weekly.dropna(
    subset=["consumed_lag_8"]
).copy()

# Chronological split
train = model_data[
    model_data["week"] <= TRAIN_END].copy()

val = model_data[
    (model_data["week"] > TRAIN_END) &
    (model_data["week"] <= VAL_END)].copy()

test = model_data[
    model_data["week"] > VAL_END].copy()

print("=" * 60)
print("TIME-BASED DATA SPLIT")
print("=" * 60)

for name, part in [
    ("Train", train),
    ("Validation", val),
    ("Test", test)]:
    print(
        f"{name:12s}: {len(part):6,} rows | "
        f"{part['week'].min().date()} -> "
        f"{part['week'].max().date()}")

============================================================
TIME-BASED DATA SPLIT
============================================================
Train       : 11,070 rows | 2022-02-21 -> 2024-06-24
Validation  :  1,260 rows | 2024-07-01 -> 2024-09-30
Test        :  1,170 rows | 2024-10-07 -> 2024-12-30

In [170]:
# Check that the periods do not overlap

print("\n" + "=" * 60)
print("Date Overlap Check")
print("=" * 60)

print(
    "Train/Validation overlap:",
    len(
        set(train["week"]).intersection(
            val["week"])))

print(
    "Validation/Test overlap:",
    len(set(val["week"]).intersection(
            test["week"])))

print(
    "Train/Test overlap:",
    len(
        set(train["week"]).intersection(
            test["week"]) ))

============================================================
Date Overlap Check
============================================================
Train/Validation overlap: 0
Validation/Test overlap: 0
Train/Test overlap: 0

## 5.13 Weekly Random Forest Model

A global Random Forest regression model is trained on the pooled weekly dataset across all sites and cement types. Site, cement type, region and behaviour are treated as categorical variables, while planned pours, weather conditions and historical consumption lags provide numerical predictors. Inventory-derived variables with unreliable weekly reconstruction are excluded from this first modelling experiment.

In [171]:
# ============================================
# Weekly Random Forest - Feature Preparation
# ============================================

TARGET = "consumed_tonnes"

feature_cols = [
    "planned_pour_tonnes",
    "rain_mm",
    "avg_temp_c",
    "silo_capacity",
    "consumed_lag_1",
    "consumed_lag_2",
    "consumed_lag_4",
    "consumed_lag_8",
    "site_id",
    "cement_type",
    "region",
    "behavior",
]

X_train = train[feature_cols]
y_train = train[TARGET]

X_val = val[feature_cols]
y_val = val[TARGET]

X_test = test[feature_cols]
y_test = test[TARGET]

print("X_train:", X_train.shape)
print("X_val:  ", X_val.shape)
print("X_test: ", X_test.shape)

print("\nTarget shapes:")
print("y_train:", y_train.shape)
print("y_val:  ", y_val.shape)
print("y_test: ", y_test.shape)

X_train: (11070, 12)
X_val:   (1260, 12)
X_test:  (1170, 12)

Target shapes:
y_train: (11070,)
y_val:   (1260,)
y_test:  (1170,)

In [172]:
# ============================================
# Check Model Inputs
# ============================================

print("=" * 60)
print("Missing Values in Model Features")
print("=" * 60)

print(X_train.isna().sum())

============================================================
Missing Values in Model Features
============================================================
planned_pour_tonnes    0
rain_mm                0
avg_temp_c             0
silo_capacity          0
consumed_lag_1         0
consumed_lag_2         0
consumed_lag_4         0
consumed_lag_8         0
site_id                0
cement_type            0
region                 0
behavior               0
dtype: int64

## 5.14 Weekly Random Forest Training

A global Random Forest regression model is trained using the pooled weekly observations from all site-cement series. Numerical demand, weather and operational features are combined with categorical site, cement type, region and behaviour information. Model performance is first assessed on the validation period, while the test set remains untouched until final model selection.

In [173]:
# ============================================
# Weekly Random Forest Preprocessor
# ============================================

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

# Numerical features
numeric_features = ["planned_pour_tonnes","rain_mm","avg_temp_c","silo_capacity",
    "consumed_lag_1", "consumed_lag_2","consumed_lag_4","consumed_lag_8",]

# Categorical features
categorical_features = ["site_id", "cement_type", "region","behavior",]

weekly_preprocessor = ColumnTransformer(
    transformers=[
        ("num", "passthrough", numeric_features ),
        ( "cat", OneHotEncoder( handle_unknown="ignore"  ),
            categorical_features),])

In [174]:
# ============================================
# Train Weekly Random Forest
# ============================================

weekly_rf_pipeline = Pipeline( steps=[("preprocessor", weekly_preprocessor),
 ("model", RandomForestRegressor( n_estimators=300,
                max_depth=15,
                min_samples_split=5,
                min_samples_leaf=2,
                random_state=42,
                n_jobs=-1, ) ),])

print("Training Weekly Random Forest...")

weekly_rf_pipeline.fit(
    X_train,
    y_train)

print("Weekly Random Forest training completed.")

Training Weekly Random Forest...
Weekly Random Forest training completed.

####Validation

In [175]:
# ============================================
# Weekly Random Forest Validation
# ============================================

y_val_pred_rf = weekly_rf_pipeline.predict(X_val)

# Prevent negative demand predictions
y_val_pred_rf = y_val_pred_rf.clip(min=0)

weekly_rf_val_metrics = evaluate(
    y_true=y_val,
    y_pred=y_val_pred_rf,
    y_train=y_train,
)

print("=" * 60)
print("Weekly Random Forest - Validation Results")
print("=" * 60)

for metric, value in weekly_rf_val_metrics.items():
    print(f"{metric:<18}: {value:.4f}")

============================================================
Weekly Random Forest - Validation Results
============================================================
WAPE              : 0.1847
RMSE              : 16.2675
MAE               : 10.0608
bias              : 0.6068
MAPE_nonzero      : 0.2063
pct_zero_actual   : 0.1032
MASE              : 0.2501

## 5.15 Planned-Pour Benchmark

The planned-pour forecast is used as the primary business benchmark. The benchmark assumes that weekly cement demand is equal to the planned cement pour. The Random Forest model must outperform this benchmark to demonstrate practical forecasting value.

In [176]:
# ============================================
# Planned-Pour Validation Benchmark
# ============================================

y_val_planned = val["planned_pour_tonnes"].clip(lower=0)

planned_pour_val_metrics = evaluate(
    y_true=y_val,
    y_pred=y_val_planned,
    y_train=y_train,
)

print("=" * 60)
print("Planned-Pour Benchmark - Validation Results")
print("=" * 60)

for metric, value in planned_pour_val_metrics.items():
    print(f"{metric:<18}: {value:.4f}")

============================================================
Planned-Pour Benchmark - Validation Results
============================================================
WAPE              : 0.3209
RMSE              : 30.4738
MAE               : 17.4786
bias              : 17.4786
MAPE_nonzero      : 0.3586
pct_zero_actual   : 0.1032
MASE              : 0.4344

In [177]:
# ============================================
# Compare Random Forest vs Planned Pour
# ============================================

comparison = pd.DataFrame({
    "Random Forest": weekly_rf_val_metrics,
    "Planned Pour": planned_pour_val_metrics,
})

print("=" * 60)
print("Validation Model Comparison")
print("=" * 60)

display(comparison)

============================================================
Validation Model Comparison
============================================================

                 Random Forest  Planned Pour
WAPE                  0.184685      0.320852
RMSE                 16.267529     30.473838
MAE                  10.060830     17.478587
bias                  0.606806     17.478587
MAPE_nonzero          0.206299      0.358562
pct_zero_actual       0.103175      0.103175
MASE                  0.250056      0.434419

## 5.16 Weekly LightGBM Model

A global LightGBM regression model is trained on the same weekly training and validation data used for the Random Forest model. Using identical features and chronological splits allows a direct comparison of the two machine-learning approaches at weekly frequency.

In [178]:
# ============================================
# Weekly LightGBM Model
# ============================================

from lightgbm import LGBMRegressor

weekly_lgbm_pipeline = Pipeline(
    steps=[("preprocessor", weekly_preprocessor),

        ( "model",LGBMRegressor(
                n_estimators=300,
                learning_rate=0.05,
                num_leaves=31,
                max_depth=10,
                subsample=0.8,
                colsample_bytree=0.8,
                random_state=42,
                verbosity=-1,) ), ])

print("Training Weekly LightGBM...")

weekly_lgbm_pipeline.fit(
    X_train,
    y_train)

print("Weekly LightGBM training completed.")

Training Weekly LightGBM...
Weekly LightGBM training completed.

In [179]:
# ============================================
# Weekly LightGBM Validation
# ============================================

y_val_pred_lgbm = weekly_lgbm_pipeline.predict(X_val)

# Prevent negative demand predictions
y_val_pred_lgbm = y_val_pred_lgbm.clip(min=0)

weekly_lgbm_val_metrics = evaluate(
    y_true=y_val,
    y_pred=y_val_pred_lgbm,
    y_train=y_train,)

print("=" * 60)
print("Weekly LightGBM - Validation Results")
print("=" * 60)

for metric, value in weekly_lgbm_val_metrics.items():
    print(f"{metric:<18}: {value:.4f}")

============================================================
Weekly LightGBM - Validation Results
============================================================
WAPE              : 0.1850
RMSE              : 16.2504
MAE               : 10.0757
bias              : 1.0955
MAPE_nonzero      : 0.2074
pct_zero_actual   : 0.1032
MASE              : 0.2504

### compare RF AND lightGBM

In [180]:
# ============================================
# Compare Weekly Models
# ============================================

weekly_model_comparison = pd.DataFrame({
    "Random Forest": weekly_rf_val_metrics,
    "LightGBM": weekly_lgbm_val_metrics,
})

print("=" * 60)
print("Weekly Model Comparison - Validation")
print("=" * 60)

display(weekly_model_comparison)

============================================================
Weekly Model Comparison - Validation
============================================================

                 Random Forest   LightGBM
WAPE                  0.184685   0.184958
RMSE                 16.267529  16.250391
MAE                  10.060830  10.075689
bias                  0.606806   1.095535
MAPE_nonzero          0.206299   0.207421
pct_zero_actual       0.103175   0.103175
MASE                  0.250056   0.250425

Weekly data was aggregated into a complete site-cement-week panel. No-activity weeks were identified and handled separately from missing operational values. Weather and site-level silo capacity were reconstructed where appropriate. Inventory-derived variables were excluded from the initial ML experiment because their weekly values could not be reliably reconstructed. Historical consumption lags were created at 1, 2, 4 and 8 weeks. A chronological train/validation/test split was used to evaluate weekly forecasting performance.

## 5.17 Random Forest Hyperparameter Tuning

Random Forest hyperparameters are tuned using time-aware cross-validation on the training data. TimeSeriesSplit is used to preserve chronological ordering and prevent future observations from being used to predict earlier observations. The validation period remains separate and is used only for final model selection.

In [181]:
# ============================================
# Time-Aware Random Forest Hyperparameter Tuning
# ============================================

from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit

# Time-aware cross-validation
tscv = TimeSeriesSplit(n_splits=3)

param_dist = {
    "model__n_estimators": [200, 300, 500, 700],
    "model__max_depth": [10, 15, 20, 25, None],
    "model__min_samples_split": [2, 5, 10],
    "model__min_samples_leaf": [1, 2, 4],
    "model__max_features": ["sqrt", "log2", 1.0],
}

rf_search = RandomizedSearchCV(
    estimator=weekly_rf_pipeline,
    param_distributions=param_dist,
    n_iter=15,
    cv=tscv,
    scoring="neg_root_mean_squared_error",
    random_state=42,
    n_jobs=-1,
    verbose=2,)

print("Tuning Weekly Random Forest...")

rf_search.fit(
    X_train,
    y_train)

print("Tuning completed.")

print("\nBest Parameters:")
print(rf_search.best_params_)

print("\nBest Time-Series CV RMSE:")
print(-rf_search.best_score_)

Tuning Weekly Random Forest...
Fitting 3 folds for each of 15 candidates, totalling 45 fits
Tuning completed.

Best Parameters:
{'model__n_estimators': 500, 'model__min_samples_split': 2, 'model__min_samples_leaf': 2, 'model__max_features': 1.0, 'model__max_depth': 10}

Best Time-Series CV RMSE:
16.275174220108646

In [182]:
# ============================================
# Tuned Random Forest Validation
# ============================================

tuned_rf = rf_search.best_estimator_

y_val_pred_tuned_rf = tuned_rf.predict(X_val)

y_val_pred_tuned_rf = y_val_pred_tuned_rf.clip(min=0)

tuned_rf_val_metrics = evaluate(
    y_true=y_val,
    y_pred=y_val_pred_tuned_rf,
    y_train=y_train,
)

print("=" * 60)
print("Tuned Weekly Random Forest - Validation")
print("=" * 60)

for metric, value in tuned_rf_val_metrics.items():
    print(f"{metric:<18}: {value:.4f}")

============================================================
Tuned Weekly Random Forest - Validation
============================================================
WAPE              : 0.1838
RMSE              : 16.1693
MAE               : 10.0146
bias              : 0.7724
MAPE_nonzero      : 0.2067
pct_zero_actual   : 0.1032
MASE              : 0.2489

In [183]:
# ============================================
# Compare Weekly RF Models
# ============================================

rf_tuning_comparison = pd.DataFrame({
    "Original RF": weekly_rf_val_metrics,
    "Tuned RF": tuned_rf_val_metrics,
    "LightGBM": weekly_lgbm_val_metrics,
})

print("=" * 60)
print("Weekly Model Comparison")
print("=" * 60)

display(rf_tuning_comparison)

============================================================
Weekly Model Comparison
============================================================

                 Original RF   Tuned RF   LightGBM
WAPE                0.184685   0.183837   0.184958
RMSE               16.267529  16.169261  16.250391
MAE                10.060830  10.014598  10.075689
bias                0.606806   0.772371   1.095535
MAPE_nonzero        0.206299   0.206681   0.207421
pct_zero_actual     0.103175   0.103175   0.103175
MASE                0.250056   0.248907   0.250425

### Confirm the tuned model and validation data

In [184]:
# ============================================
# 8-Week Forecast Evaluation
# Step 1: Confirm Model and Validation Data
# ============================================

print("=" * 60)
print("8-WEEK FORECAST EVALUATION SETUP")
print("=" * 60)

print(f"Validation start : {val['week'].min().date()}")
print(f"Validation end   : {val['week'].max().date()}")

print(f"\nValidation rows  : {len(val):,}")
print(f"Validation sites : {val['site_id'].nunique()}")
print(f"Cement types     : {val['cement_type'].nunique()}")

print("\nTuned Random Forest:")
print(rf_search.best_params_)

print("\nValidation feature columns:")
print(X_val.columns.tolist())

============================================================
8-WEEK FORECAST EVALUATION SETUP
============================================================
Validation start : 2024-07-01
Validation end   : 2024-09-30

Validation rows  : 1,260
Validation sites : 30
Cement types     : 3

Tuned Random Forest:
{'model__n_estimators': 500, 'model__min_samples_split': 2, 'model__min_samples_leaf': 2, 'model__max_features': 1.0, 'model__max_depth': 10}

Validation feature columns:
['planned_pour_tonnes', 'rain_mm', 'avg_temp_c', 'silo_capacity', 'consumed_lag_1', 'consumed_lag_2', 'consumed_lag_4', 'consumed_lag_8', 'site_id', 'cement_type', 'region', 'behavior']

## 8-Week Recursive Forecast Evaluation

The tuned Random Forest is evaluated using a recursive multi-step forecasting approach. Forecasts are generated sequentially from one to eight weeks ahead. For each forecast horizon, only information available at the forecasting origin is used.

Historical consumption is used to construct the lag features for the first forecast. For subsequent horizons, previously generated predictions are used when future consumption values are required. This prevents actual future consumption from being used as an input and avoids data leakage.

Performance is evaluated separately for each forecast horizon using WAPE, RMSE, MAE, bias and MASE.

In [185]:
# ============================================
# Check Validation Weekly Timeline
# ============================================

validation_weeks = (
    val["week"]
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

print("=" * 60)
print("VALIDATION WEEKLY TIMELINE")
print("=" * 60)

print("Number of validation weeks:", len(validation_weeks))
print("\nValidation weeks:")

for i, week in enumerate(validation_weeks, start=1):
    print(f"{i:2d}. {week.date()}")

============================================================
VALIDATION WEEKLY TIMELINE
============================================================
Number of validation weeks: 14

Validation weeks:
 1. 2024-07-01
 2. 2024-07-08
 3. 2024-07-15
 4. 2024-07-22
 5. 2024-07-29
 6. 2024-08-05
 7. 2024-08-12
 8. 2024-08-19
 9. 2024-08-26
10. 2024-09-02
11. 2024-09-09
12. 2024-09-16
13. 2024-09-23
14. 2024-09-30

### Check Required Validation Features

In [186]:
# ============================================
# 8-Week Forecast Evaluation
# Step 3: Check Required Validation Features
# ============================================

required_features = [
    "planned_pour_tonnes",
    "rain_mm",
    "avg_temp_c",
    "silo_capacity",
    "consumed_lag_1",
    "consumed_lag_2",
    "consumed_lag_4",
    "consumed_lag_8",
    "site_id",
    "cement_type",
    "region",
    "behavior",
]

print("=" * 60)
print("8-WEEK FORECAST FEATURE CHECK")
print("=" * 60)

print("\nMissing values:")
print(val[required_features].isna().sum())

print("\nRequired features present:")
for col in required_features:
    print(f"✓ {col}")

print("\nValidation series:")
print(val.groupby(["site_id", "cement_type"])
       .size()
       .describe()
)

============================================================
8-WEEK FORECAST FEATURE CHECK
============================================================

Missing values:
planned_pour_tonnes    0
rain_mm                0
avg_temp_c             0
silo_capacity          0
consumed_lag_1         0
consumed_lag_2         0
consumed_lag_4         0
consumed_lag_8         0
site_id                0
cement_type            0
region                 0
behavior               0
dtype: int64

Required features present:
✓ planned_pour_tonnes
✓ rain_mm
✓ avg_temp_c
✓ silo_capacity
✓ consumed_lag_1
✓ consumed_lag_2
✓ consumed_lag_4
✓ consumed_lag_8
✓ site_id
✓ cement_type
✓ region
✓ behavior

Validation series:
count    90.0
mean     14.0
std       0.0
min      14.0
25%      14.0
50%      14.0
75%      14.0
max      14.0
dtype: float64

## 8-Week Rolling-Origin Recursive Forecast

The tuned Random Forest is evaluated using rolling-origin recursive forecasting over an eight-week horizon. At each forecasting origin, only historical consumption available up to that point is used to initialise the lag features.

For each subsequent forecast week, the model's previous predictions are added to the historical sequence and used to construct future lag features. This prevents actual future consumption from being used during forecasting.

Future planned-pour and weather variables are taken from the corresponding validation weeks, as these variables are treated as available exogenous information for the forecasting exercise.

Forecast performance is recorded separately for horizons 1 to 8 weeks ahead.

In [ ]:
# ============================================================================
# 8-WEEK ROLLING-ORIGIN RECURSIVE FORECAST  (batched)
# ============================================================================

import numpy as np
import pandas as pd

HORIZON = 8
TARGET = "consumed_tonnes"

MODEL_FEATURES = [
    "planned_pour_tonnes", "rain_mm", "avg_temp_c", "silo_capacity",
    "consumed_lag_1", "consumed_lag_2", "consumed_lag_4", "consumed_lag_8",
    "site_id", "cement_type", "region", "behavior",
]
GROUP_COLS = ["site_id", "cement_type"]
LAG_STEPS = (1, 2, 4, 8)

tuned_rf = rf_search.best_estimator_

print("=" * 60)
print("MODEL USED FOR 8-WEEK FORECAST")
print("=" * 60)
print("Tuned Random Forest")
print(rf_search.best_params_)

model_data = complete_weekly.copy()
model_data["week"] = pd.to_datetime(model_data["week"])
model_data = model_data.sort_values(GROUP_COLS + ["week"]).reset_index(drop=True)

# ---------------------------------------------------------------------------
# Forecast origins - each needs 8 full validation weeks ahead of it
# ---------------------------------------------------------------------------
train_last_week = train["week"].max()
validation_weeks = val["week"].drop_duplicates().sort_values().reset_index(drop=True)

forecast_origins = [o for o in [train_last_week] + validation_weeks.tolist()
                    if len(validation_weeks[validation_weeks > o]) >= HORIZON]

print("\n" + "=" * 60)
print("FORECAST ORIGINS")
print("=" * 60)
for o in forecast_origins:
    print(o.date())
print("\nNumber of complete 8-week origins:", len(forecast_origins))

# ---------------------------------------------------------------------------
# Exogenous lookup: nested dict instead of a boolean scan per row.
# val_lookup[week][(site, cement)] -> the future row
# ---------------------------------------------------------------------------
val_lookup = {}
for wk_, g in val.groupby("week"):
    val_lookup[wk_] = {(r.site_id, r.cement_type): r for r in g.itertuples(index=False)}

# ---------------------------------------------------------------------------
# Recursive forecasting, batched across series
# ---------------------------------------------------------------------------
forecast_records = []

for origin in forecast_origins:
    print(f"\nForecast origin: {origin.date()}")

    future_weeks = validation_weeks[validation_weeks > origin].iloc[:HORIZON].tolist()
    historical = model_data[model_data["week"] <= origin]

    # consumption history and static attributes per series
    history, static = {}, {}
    for key, g in historical.groupby(GROUP_COLS):
        g = g.sort_values("week")
        history[key] = list(g[TARGET].fillna(0).values)
        static[key] = (g["region"].iloc[-1], g["behavior"].iloc[-1])

    for horizon, forecast_week in enumerate(future_weeks, start=1):
        week_rows = val_lookup.get(forecast_week, {})

        batch, keys, actuals = [], [], []
        for key, hist in history.items():
            future_row = week_rows.get(key)
            if future_row is None:
                continue                       # no exogenous row - skip, history unchanged

            lags = [hist[-l] if len(hist) >= l else np.nan for l in LAG_STEPS]
            if any(pd.isna(x) for x in lags):
                continue                       # lag-8 unavailable - cannot forecast safely

            site, cement = key
            region, behavior = static[key]
            batch.append({
                "planned_pour_tonnes": future_row.planned_pour_tonnes,
                "rain_mm": future_row.rain_mm,
                "avg_temp_c": future_row.avg_temp_c,
                "silo_capacity": future_row.silo_capacity,
                "consumed_lag_1": lags[0], "consumed_lag_2": lags[1],
                "consumed_lag_4": lags[2], "consumed_lag_8": lags[3],
                "site_id": site, "cement_type": cement,
                "region": region, "behavior": behavior,
            })
            keys.append(key)
            actuals.append(getattr(future_row, TARGET))

        if not batch:
            continue

        # one predict call for every series at this horizon step
        X_future = pd.DataFrame(batch)[MODEL_FEATURES]
        predictions = np.clip(tuned_rf.predict(X_future), 0, None)

        for key, pred, actual in zip(keys, predictions, actuals):
            site, cement = key
            forecast_records.append({
                "origin": origin, "week": forecast_week,
                "site_id": site, "cement_type": cement,
                "horizon": horizon, "actual": actual, "prediction": pred,
            })
            # feed the PREDICTION back, never the actual
            history[key].append(pred)

# ---------------------------------------------------------------------------
forecast_results = (pd.DataFrame(forecast_records)
                    .sort_values(["origin", "site_id", "cement_type", "horizon"])
                    .reset_index(drop=True))

print("\n" + "=" * 60)
print("8-WEEK FORECAST RESULTS")
print("=" * 60)
print("Forecast rows:", len(forecast_results))
print("Forecast origins:", forecast_results["origin"].nunique())
print("Series:", forecast_results[["site_id", "cement_type"]].drop_duplicates().shape[0])
print("Horizons:", sorted(forecast_results["horizon"].unique()))

display(forecast_results.head(20))

============================================================
MODEL USED FOR 8-WEEK FORECAST
============================================================
Tuned Random Forest
{'model__n_estimators': 500, 'model__min_samples_split': 2, 'model__min_samples_leaf': 2, 'model__max_features': 1.0, 'model__max_depth': 10}

============================================================
FORECAST ORIGINS
============================================================
2024-06-24
2024-07-01
2024-07-08
2024-07-15
2024-07-22
2024-07-29
2024-08-05

Number of complete 8-week origins: 7

Forecast origin: 2024-06-24

Forecast origin: 2024-07-01

Forecast origin: 2024-07-08

Forecast origin: 2024-07-15

Forecast origin: 2024-07-22

Forecast origin: 2024-07-29

Forecast origin: 2024-08-05

============================================================
8-WEEK FORECAST RESULTS
============================================================
Forecast rows: 5040
Forecast origins: 7
Series: 90
Horizons: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]

       origin       week   site_id cement_type  horizon  actual  prediction
0  2024-06-24 2024-07-01  SITE_001       CEM_I        1   92.64   95.310553
1  2024-06-24 2024-07-08  SITE_001       CEM_I        2   71.50  107.926195
2  2024-06-24 2024-07-15  SITE_001       CEM_I        3  151.26  127.572104
3  2024-06-24 2024-07-22  SITE_001       CEM_I        4   20.17   29.601246
4  2024-06-24 2024-07-29  SITE_001       CEM_I        5  176.77  165.174749
5  2024-06-24 2024-08-05  SITE_001       CEM_I        6  137.81   92.122153
6  2024-06-24 2024-08-12  SITE_001       CEM_I        7   24.64   25.307113
7  2024-06-24 2024-08-19  SITE_001       CEM_I        8   32.52   58.258808
8  2024-06-24 2024-07-01  SITE_001      CEM_II        1   44.07   36.173297
9  2024-06-24 2024-07-08  SITE_001      CEM_II        2   81.14   93.572868
10 2024-06-24 2024-07-15  SITE_001      CEM_II        3   41.60   32.864799
11 2024-06-24 2024-07-22  SITE_001      CEM_II        4   66.97   94.231504
12 2024-06-24 2024-07-29  SITE_001      CEM_II        5    0.00    0.000000
13 2024-06-24 2024-08-05  SITE_001      CEM_II        6    0.00    0.000000
14 2024-06-24 2024-08-12  SITE_001      CEM_II        7   34.99   31.870566
15 2024-06-24 2024-08-19  SITE_001      CEM_II        8   65.62   54.344598
16 2024-06-24 2024-07-01  SITE_001     CEM_III        1   42.23   65.653772
17 2024-06-24 2024-07-08  SITE_001     CEM_III        2   15.16   36.305887
18 2024-06-24 2024-07-15  SITE_001     CEM_III        3    0.00    0.000000
19 2024-06-24 2024-07-22  SITE_001     CEM_III        4   99.23   84.616313

In [188]:
# ============================================
# 8-WEEK FORECAST PERFORMANCE BY HORIZON
# ============================================

print("=" * 60)
print("8-WEEK RECURSIVE FORECAST PERFORMANCE")
print("=" * 60)

horizon_results = []

for h in range(1, 9):

    horizon_data = forecast_results[
        forecast_results["horizon"] == h
    ].copy()

    if horizon_data.empty:
        continue

    metrics = evaluate(
        y_true=horizon_data["actual"],
        y_pred=horizon_data["prediction"],
        y_train=y_train
    )

    results_row = {
        "horizon": f"Week {h}",
        "WAPE": metrics["WAPE"],
        "RMSE": metrics["RMSE"],
        "MAE": metrics["MAE"],
        "bias": metrics["bias"],
        "MAPE_nonzero": metrics["MAPE_nonzero"],
        "MASE": metrics["MASE"],
        "observations": len(horizon_data)
    }

    horizon_results.append(results_row)


horizon_results_df = pd.DataFrame(horizon_results)

print("\n")
display(horizon_results_df)

============================================================
8-WEEK RECURSIVE FORECAST PERFORMANCE
============================================================

  horizon      WAPE       RMSE        MAE      bias  MAPE_nonzero      MASE  observations
0  Week 1  0.179090  16.518032   9.937094  0.544400      0.195413  0.246980           630
1  Week 2  0.186706  16.921787  10.257906  1.045030      0.208775  0.254954           630
2  Week 3  0.189261  17.152638  10.257164  1.331751      0.221633  0.254935           630
3  Week 4  0.196726  17.607643  10.621381  1.758347      0.226252  0.263988           630
4  Week 5  0.199480  17.719814  10.816709  1.215647      0.230956  0.268842           630
5  Week 6  0.194821  17.348995  10.554721  1.228485      0.230026  0.262331           630
6  Week 7  0.192178  16.772639  10.394073  1.248191      0.229020  0.258338           630
7  Week 8  0.187916  15.719991  10.046834  0.941111      0.216950  0.249708           630

####  8-WEEK FORECAST VS PLANNED POUR BENCHMARK

In [189]:
# ============================================
# Add Planned Pour to 8-Week Forecast Results
# ============================================

forecast_results = forecast_results.merge(
    val[
        [ "week", "site_id","cement_type","planned_pour_tonnes" ]],
    on=["week","site_id","cement_type"],how="left")

print("=" * 60)
print("PLANNED POUR ADDED")
print("=" * 60)

print( "Missing planned-pour values:",
    forecast_results["planned_pour_tonnes"].isna().sum())

display(forecast_results.head(10))

============================================================
PLANNED POUR ADDED
============================================================
Missing planned-pour values: 0

      origin       week   site_id cement_type  horizon  actual  prediction  planned_pour_tonnes
0 2024-06-24 2024-07-01  SITE_001       CEM_I        1   92.64   95.310553               128.30
1 2024-06-24 2024-07-08  SITE_001       CEM_I        2   71.50  107.926195               143.39
2 2024-06-24 2024-07-15  SITE_001       CEM_I        3  151.26  127.572104               188.41
3 2024-06-24 2024-07-22  SITE_001       CEM_I        4   20.17   29.601246                50.15
4 2024-06-24 2024-07-29  SITE_001       CEM_I        5  176.77  165.174749               253.37
5 2024-06-24 2024-08-05  SITE_001       CEM_I        6  137.81   92.122153               149.18
6 2024-06-24 2024-08-12  SITE_001       CEM_I        7   24.64   25.307113                34.95
7 2024-06-24 2024-08-19  SITE_001       CEM_I        8   32.52   58.258808                91.45
8 2024-06-24 2024-07-01  SITE_001      CEM_II        1   44.07   36.173297                59.52
9 2024-06-24 2024-07-08  SITE_001      CEM_II        2   81.14   93.572868               124.06

### 8-WEEK FORECAST VS PLANNED POUR BENCHMARK

In [190]:
# ============================================
# 8-WEEK FORECAST VS PLANNED POUR BENCHMARK
# ============================================

benchmark_results = []

for h in range(1, 9):

    horizon_data = forecast_results[
        forecast_results["horizon"] == h
    ].copy()

    # Random Forest metrics
    rf_metrics = evaluate(
        y_true=horizon_data["actual"],
        y_pred=horizon_data["prediction"],
        y_train=y_train)

    # Planned Pour metrics
    planned_metrics = evaluate(
        y_true=horizon_data["actual"],
        y_pred=horizon_data["planned_pour_tonnes"],
        y_train=y_train)

    benchmark_results.append({
        "Horizon": f"Week {h}",

        "RF_WAPE": rf_metrics["WAPE"],
        "Planned_WAPE": planned_metrics["WAPE"],

        "RF_RMSE": rf_metrics["RMSE"],
        "Planned_RMSE": planned_metrics["RMSE"],

        "RF_MAE": rf_metrics["MAE"],
        "Planned_MAE": planned_metrics["MAE"],

        "RF_Bias": rf_metrics["bias"],
        "Planned_Bias": planned_metrics["bias"],

        "RF_MAPE_nonzero": rf_metrics["MAPE_nonzero"],
        "Planned_MAPE_nonzero": planned_metrics["MAPE_nonzero"],

        "RF_MASE": rf_metrics["MASE"],
        "Planned_MASE": planned_metrics["MASE"],

        "Observations": len(horizon_data)
    })


benchmark_results_df = pd.DataFrame(benchmark_results)

print("=" * 80)
print("8-WEEK RANDOM FOREST VS PLANNED POUR")
print("=" * 80)

display(benchmark_results_df)

================================================================================
8-WEEK RANDOM FOREST VS PLANNED POUR
================================================================================

,Horizon,RF_WAPE,Planned_WAPE,RF_RMSE,Planned_RMSE,RF_MAE,Planned_MAE,RF_Bias,Planned_Bias,RF_MAPE_nonzero,Planned_MAPE_nonzero,RF_MASE,Planned_MASE,Observations
0,Week 1,0.179090,0.299038,16.518032,30.522770,9.937094,16.592603,0.544400,16.592603,0.195413,0.326093,0.246980,0.412399,630
1,Week 2,0.186706,0.316504,16.921787,31.820727,10.257906,17.389175,1.045030,17.389175,0.208775,0.348009,0.254954,0.432197,630
2,Week 3,0.189261,0.329943,17.152638,32.231999,10.257164,17.881540,1.331751,17.881540,0.221633,0.373231,0.254935,0.444434,630
3,Week 4,0.196726,0.348821,17.607643,33.123306,10.621381,18.833127,1.758347,18.833127,0.226252,0.388566,0.263988,0.468086,630
4,Week 5,0.199480,0.341351,17.719814,32.459167,10.816709,18.509651,1.215647,18.509651,0.230956,0.388170,0.268842,0.460046,630
5,Week 6,0.194821,0.346334,17.348995,32.172563,10.554721,18.763143,1.228485,18.763143,0.230026,0.397935,0.262331,0.466346,630
6,Week 7,0.192178,0.349620,16.772639,32.127143,10.394073,18.909444,1.248191,18.909444,0.229020,0.404265,0.258338,0.469982,630
7,Week 8,0.187916,0.343491,15.719991,30.424827,10.046834,18.364571,0.941111,18.364571,0.216950,0.390575,0.249708,0.456440,630

---

# Random Forest on the SARIMAX Feature Set

Earlier comparisons between SARIMAX and the tree models were not like-for-like: the
SARIMAX runs were weekly per **site**, the ML runs were daily and per
**site x cement type**. Grain alone accounts for most of the apparent gap.

This section removes that confound. Same weekly per-site panel, same 8-week window,
same exogenous features the SARIMAX model was given — only the estimator changes.

Two variants are fitted:

- **exog only** — exactly the SARIMAX regressor set
- **exog + lags** — the fair equivalent, since SARIMAX gets autoregressive terms
  internally and a Random Forest has no such mechanism

In [191]:
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

from mig_cement.config import settings

TRAIN_END_W, VAL_END_W = "2024-06-30", "2024-09-30"
HORIZON_WEEKS = 8

fe = pd.read_parquet(settings.processed_dir / "operations_feature_engineered.parquet")
fe["date"] = pd.to_datetime(fe["date"]).dt.to_period("W-SUN").dt.start_time

# same aggregation rules as the SARIMAX weekly experiment
AGG_RF = {
    "y": "sum",
    "planned_pour_tonnes": "sum",
    "planned_pour_next_7": "last",
    "planned_pour_next_14": "last",
    "pour_blocked_rain": "sum",
    "frost": "sum",
    "rain_mm": "mean",
    "avg_temp_c": "mean",
    "opening_inventory_tonnes": "first",
    "inventory_vs_capacity": "first",
    "headroom_tonnes": "first",
    "cover_days_7": "first",
    "days_since_planned_pour": "first",
    "silo_capacity": "first",
    "region": "first",
    "behavior": "first",
}

wk = fe.groupby(["site_id", "date"], as_index=False).agg(AGG_RF)
wk["n_days"] = fe.groupby(["site_id", "date"]).size().values
wk = (wk[wk.n_days == 7].drop(columns="n_days")          # drop partial weeks
        .sort_values(["site_id", "date"]).reset_index(drop=True))

# lags and rolling means - shifted, so no leakage
for lag in (1, 2, 4, 8):
    wk[f"lag_{lag}"] = wk.groupby("site_id").y.shift(lag)
wk["roll_4"] = wk.groupby("site_id").y.transform(lambda s: s.shift(1).rolling(4).mean())
wk["roll_8"] = wk.groupby("site_id").y.transform(lambda s: s.shift(1).rolling(8).mean())

wk = wk.dropna().reset_index(drop=True)
print("weekly per-site panel:", wk.shape)
print("weeks:", wk.date.nunique(), "| sites:", wk.site_id.nunique())

weekly per-site panel: (4440, 24)
weeks: 148 | sites: 30

In [192]:
train_rf = wk[wk.date <= TRAIN_END_W]
val_rf = (wk[(wk.date > TRAIN_END_W) & (wk.date <= VAL_END_W)]
          .groupby("site_id").head(HORIZON_WEEKS))

print(f"train {len(train_rf):5,} rows  {train_rf.date.min().date()} -> {train_rf.date.max().date()}")
print(f"val   {len(val_rf):5,} rows  {val_rf.date.min().date()} -> {val_rf.date.max().date()}"
      f"  ({val_rf.groupby('site_id').size().mean():.0f} weeks per site)")

train 3,660 rows  2022-02-28 -> 2024-06-24
val     240 rows  2024-07-01 -> 2024-08-19  (8 weeks per site)

In [193]:
# SARIMAX exogenous regressors, verbatim
SARIMAX_EXOG = [
    "planned_pour_tonnes", "planned_pour_next_7", "planned_pour_next_14",
    "pour_blocked_rain", "frost", "rain_mm", "avg_temp_c",
    "opening_inventory_tonnes", "inventory_vs_capacity", "headroom_tonnes",
    "cover_days_7", "days_since_planned_pour",
]
LAGS = ["lag_1", "lag_2", "lag_4", "lag_8", "roll_4", "roll_8"]
CATS = ["site_id", "region", "behavior"]   # SARIMAX gets these free by fitting per site


def fit_rf(features, label, n_estimators=300):
    num = [f for f in features if f not in CATS]
    pre = ColumnTransformer([
        ("num", "passthrough", num),
        ("cat", OneHotEncoder(handle_unknown="ignore"), [f for f in features if f in CATS]),
    ])
    pipe = Pipeline([("preprocessor", pre),
                     ("model", RandomForestRegressor(n_estimators=n_estimators,
                                                     random_state=42, n_jobs=-1))])
    pipe.fit(train_rf[features], train_rf["y"])
    pred = np.clip(pipe.predict(val_rf[features]), 0, None)

    y = val_rf["y"].values
    nz = y != 0
    return {
        "model": label,
        "n_features": len(features),
        "MAPE": np.mean(np.abs((y[nz] - pred[nz]) / y[nz])),
        "RMSE": np.sqrt(np.mean((y - pred) ** 2)),
        "WAPE": np.abs(y - pred).sum() / np.abs(y).sum(),
        "MAE": np.abs(y - pred).mean(),
        "bias": (pred - y).mean(),
    }, pipe

In [194]:
results_rf = []

m_exog, rf_exog = fit_rf(SARIMAX_EXOG + CATS, "RF (SARIMAX exog only)")
results_rf.append(m_exog)

m_full, rf_full = fit_rf(SARIMAX_EXOG + LAGS + CATS, "RF (SARIMAX exog + lags)")
results_rf.append(m_full)

# SARIMAX figures from the weekly experiments above, same window
results_rf += [
    {"model": "SARIMAX (engineered, weekly)", "n_features": 12,
     "MAPE": 0.0834, "RMSE": 24.6977, "WAPE": 0.0905, "MAE": 15.0323, "bias": 3.5075},
    {"model": "SARIMAX (raw, weekly)", "n_features": 4,
     "MAPE": 0.0974, "RMSE": 27.6384, "WAPE": 0.1059, "MAE": 17.5896, "bias": -0.3019},
]

comparison_rf = pd.DataFrame(results_rf).set_index("model")[
    ["n_features", "MAPE", "RMSE", "WAPE", "MAE", "bias"]]
comparison_rf.round(4)

                              n_features    MAPE     RMSE    WAPE      MAE    bias
model
RF (SARIMAX exog only)                15  0.0703  21.7335  0.0787  13.0638  1.6707
RF (SARIMAX exog + lags)              21  0.0717  21.8798  0.0807  13.3978  1.1181
SARIMAX (engineered, weekly)          12  0.0834  24.6977  0.0905  15.0323  3.5075
SARIMAX (raw, weekly)                  4  0.0974  27.6384  0.1059  17.5896 -0.3019

In [195]:
imp = pd.Series(
    rf_full.named_steps["model"].feature_importances_[:len(SARIMAX_EXOG + LAGS)],
    index=SARIMAX_EXOG + LAGS,
).sort_values(ascending=False)

print("Random Forest feature importance (SARIMAX exog + lags):")
imp.head(12).to_frame("importance").round(4)

Random Forest feature importance (SARIMAX exog + lags):

                          importance
planned_pour_tonnes           0.8300
opening_inventory_tonnes      0.0250
cover_days_7                  0.0207
inventory_vs_capacity         0.0160
pour_blocked_rain             0.0127
rain_mm                       0.0095
lag_1                         0.0090
avg_temp_c                    0.0085
planned_pour_next_14          0.0080
lag_8                         0.0079
lag_4                         0.0078
lag_2                         0.0073

**Like-for-like, the Random Forest beats SARIMAX.** The earlier gap was grain and
features, not the estimator.

| model | MAPE | RMSE | bias |
|---|---|---|---|
| RF (SARIMAX exog only) | **7.1%** | **21.85** | +1.54 |
| RF (SARIMAX exog + lags) | 7.2% | 22.01 | +0.98 |
| SARIMAX (engineered, weekly) | 8.3% | 24.70 | +3.51 |

Three things worth noting:

- The forward-looking pour columns (`planned_pour_next_7`, `planned_pour_next_14`)
  are what close the gap. The pour schedule is known in advance and is the strongest
  signal in the data; the earlier Random Forest had only backward-looking lags.
- **The lag features add nothing** once the schedule is present — exog-only scores
  marginally better than exog + lags, and `planned_pour_tonnes` alone carries 83% of
  the feature importance. That is consistent with the Step 3 finding of no
  meaningful autocorrelation or seasonality: this is a regression problem with a
  strong exogenous driver, not a classical time-series problem.
- Weather regressors still use their actual validation values, which flatters both
  model families. A schedule-only variant is the number achievable in production.

---

# Final Comparison — All Models, Weekly Aggregation

Every model on the same footing: weekly per-site panel, 8-week validation window,
240 site-weeks, mean 166.1 t per site-week.

Assessed against the project target of **MAPE <= 15%**. The brief also names RMSE as
a selection metric but sets no numeric threshold for it, so RMSE is reported in
tonnes and as a share of mean weekly demand.

In [196]:
PROJECT_MAPE_TARGET = 0.15
MEAN_WEEKLY = val_rf["y"].mean()

final_comparison = pd.DataFrame([
    {"model": "Random Forest (engineered)",            "n_feat": 12, "MAPE": 0.0709, "RMSE": 21.853, "WAPE": 0.079, "MAE": 13.201, "bias":  1.537},
    {"model": "Random Forest (engineered + lags)",     "n_feat": 18, "MAPE": 0.0723, "RMSE": 22.013, "WAPE": 0.081, "MAE": 13.499, "bias":  0.979},
    {"model": "HistGradientBoosting (LightGBM proxy)", "n_feat": 18, "MAPE": 0.0755, "RMSE": 22.010, "WAPE": 0.084, "MAE": 13.876, "bias":  1.741},
    {"model": "Random Forest (lags only)",             "n_feat": 10, "MAPE": 0.0817, "RMSE": 23.084, "WAPE": 0.090, "MAE": 15.017, "bias":  0.685},
    {"model": "SARIMAX (engineered)",                  "n_feat": 12, "MAPE": 0.0850, "RMSE": 24.773, "WAPE": 0.093, "MAE": 15.432, "bias":  3.447},
    {"model": "SARIMAX (raw)",                         "n_feat":  4, "MAPE": 0.0986, "RMSE": 27.882, "WAPE": 0.107, "MAE": 17.827, "bias": -0.640},
    {"model": "Benchmark: planned pour",               "n_feat":  0, "MAPE": 0.2698, "RMSE": 73.409, "WAPE": 0.300, "MAE": 49.882, "bias": 49.882},
    {"model": "Baseline: train mean",                  "n_feat":  0, "MAPE": 0.5036, "RMSE": 67.141, "WAPE": 0.346, "MAE": 57.428, "bias":  0.268},
]).set_index("model")

final_comparison["MAPE %"] = (100 * final_comparison.MAPE).round(2)
final_comparison["RMSE % of mean"] = (100 * final_comparison.RMSE / MEAN_WEEKLY).round(1)
final_comparison["target MAPE <= 15%"] = np.where(
    final_comparison.MAPE <= PROJECT_MAPE_TARGET, "PASS", "FAIL")

final_comparison[["n_feat", "MAPE %", "RMSE", "RMSE % of mean",
                  "WAPE", "MAE", "bias", "target MAPE <= 15%"]]

                                       n_feat  MAPE %    RMSE  RMSE % of mean   WAPE     MAE    bias target MAPE <= 15%
model
Random Forest (engineered)                 12    7.09  21.853            13.2  0.079  13.201   1.537               PASS
Random Forest (engineered + lags)          18    7.23  22.013            13.3  0.081  13.499   0.979               PASS
HistGradientBoosting (LightGBM proxy)      18    7.55  22.010            13.3  0.084  13.876   1.741               PASS
Random Forest (lags only)                  10    8.17  23.084            13.9  0.090  15.017   0.685               PASS
SARIMAX (engineered)                       12    8.50  24.773            14.9  0.093  15.432   3.447               PASS
SARIMAX (raw)                               4    9.86  27.882            16.8  0.107  17.827  -0.640               PASS
Benchmark: planned pour                     0   26.98  73.409            44.2  0.300  49.882  49.882               FAIL
Baseline: train mean                        0   50.36  67.141            40.4  0.346  57.428   0.268               FAIL

In [197]:
best = final_comparison.MAPE.idxmin()
b = final_comparison.loc[best]
print(f"Best on validation: {best}")
print(f"  MAPE {100*b.MAPE:.2f}%  vs target 15%  ->  {100*(1 - b.MAPE/PROJECT_MAPE_TARGET):.0f}% inside target")
print(f"  RMSE {b.RMSE:.1f} t   ({100*b.RMSE/MEAN_WEEKLY:.1f}% of mean weekly demand of {MEAN_WEEKLY:.1f} t)")
print(f"  bias {b.bias:+.2f} t per site-week")
print()
pp = final_comparison.loc["Benchmark: planned pour"]
print(f"Against current practice (order to the schedule):")
print(f"  MAPE {100*pp.MAPE:.1f}% -> {100*b.MAPE:.1f}%   ({100*(b.MAPE/pp.MAPE - 1):+.0f}%)")
print(f"  RMSE {pp.RMSE:.1f} -> {b.RMSE:.1f} t         ({100*(b.RMSE/pp.RMSE - 1):+.0f}%)")
print(f"  bias {pp.bias:+.1f} -> {b.bias:+.1f} t per site-week")

Best on validation: Random Forest (engineered)
  MAPE 7.09%  vs target 15%  ->  53% inside target
  RMSE 21.9 t   (13.2% of mean weekly demand of 166.1 t)
  bias +1.54 t per site-week

Against current practice (order to the schedule):
  MAPE 27.0% -> 7.1%   (-74%)
  RMSE 73.4 -> 21.9 t         (-70%)
  bias +49.9 -> +1.5 t per site-week

**All six fitted models clear the 15% MAPE target; both naive approaches fail.**
The best, Random Forest on the engineered feature set, lands at **7.1% — less than
half the target**, with RMSE at 13% of mean weekly demand.

---

# Weather Regressors — What Is Actually Knowable at Order Time

Every result above feeds the model the **actual** rain and temperature for the
forecast window. Eight weeks ahead, nobody has those figures. Any number produced
that way describes a forecast that cannot be reproduced in production.

Three configurations are fitted, differing only in which regressors are assumed
available when the order is placed:

| # | configuration | assumption |
|---|---|---|
| 1 | full | actual weather known for the whole horizon — optimistic |
| 2 | no weather | weather dropped entirely |
| 3 | schedule only | only the pour schedule and site attributes — everything genuinely known 8 weeks out |

Configuration 3 also drops the inventory-state columns (`opening_inventory_tonnes`,
`cover_days_7`, `inventory_vs_capacity`, `headroom_tonnes`). Those describe the
position at the *start of the week being forecast*, which is known one week ahead but
not eight — the same objection as weather, applied consistently.

In [198]:
WEATHER_COLS = ["rain_mm", "avg_temp_c", "pour_blocked_rain", "frost"]
STATE_COLS = ["opening_inventory_tonnes", "inventory_vs_capacity",
              "headroom_tonnes", "cover_days_7"]
SCHEDULE_COLS = ["planned_pour_tonnes", "planned_pour_next_7",
                 "planned_pour_next_14", "days_since_planned_pour"]
SITE_COLS = ["silo_capacity"] + CATS

AVAILABILITY = {
    "1. Full (weather actuals)":  SCHEDULE_COLS + WEATHER_COLS + STATE_COLS + SITE_COLS,
    "2. No weather":              SCHEDULE_COLS + STATE_COLS + SITE_COLS,
    "3. Schedule only":           SCHEDULE_COLS + SITE_COLS,
}

for name, cols in AVAILABILITY.items():
    print(f"{name:28s} {len(cols):2d} features")

1. Full (weather actuals)    16 features
2. No weather                12 features
3. Schedule only              8 features

In [199]:
weather_results = []

for name, cols in AVAILABILITY.items():
    metrics, _ = fit_rf(cols, name)
    metrics["model"] = name
    weather_results.append(metrics)

weather_comparison = pd.DataFrame(weather_results).set_index("model")
weather_comparison["MAPE %"] = (100 * weather_comparison.MAPE).round(2)
weather_comparison["target MAPE <= 15%"] = np.where(
    weather_comparison.MAPE <= 0.15, "PASS", "FAIL")

weather_comparison[["n_features", "MAPE %", "RMSE", "WAPE", "MAE", "bias",
                    "target MAPE <= 15%"]].round(3)

                           n_features  MAPE %    RMSE   WAPE     MAE   bias target MAPE <= 15%
model
1. Full (weather actuals)          16    7.07  21.867  0.079  13.160  1.712               PASS
2. No weather                      12    9.03  24.643  0.098  16.243  1.573               PASS
3. Schedule only                    8   10.77  30.482  0.118  19.666  0.815               PASS

In [200]:
full = weather_comparison.loc["1. Full (weather actuals)"]
sched = weather_comparison.loc["3. Schedule only"]

print("Cost of being honest about the horizon:")
print(f"  MAPE {100*full.MAPE:.2f}% -> {100*sched.MAPE:.2f}%   "
      f"({100*(sched.MAPE/full.MAPE - 1):+.0f}%)")
print(f"  RMSE {full.RMSE:.2f} -> {sched.RMSE:.2f} t")
print()
print(f"Schedule-only vs current practice (order to the schedule):")
print(f"  MAPE 26.98% -> {100*sched.MAPE:.2f}%   "
      f"({100*(sched.MAPE/0.2698 - 1):+.0f}%)")
print(f"  bias +49.88 -> {sched.bias:+.2f} t per site-week")
print()
print(f"All three configurations clear the 15% target: "
      f"{(weather_comparison.MAPE <= 0.15).all()}")

Cost of being honest about the horizon:
  MAPE 7.07% -> 10.77%   (+52%)
  RMSE 21.87 -> 30.48 t

Schedule-only vs current practice (order to the schedule):
  MAPE 26.98% -> 10.77%   (-60%)
  bias +49.88 -> +0.82 t per site-week

All three configurations clear the 15% target: True

**All three clear the 15% target**, so this is a credibility decision rather than a
pass/fail one.

Configuration 1 at 7.0% assumes Oct–Dec rainfall was known in advance. It is the
best number and the least defensible; quoting it invites the question "how did you
know it would rain?"

**Configuration 3 at 10.8% is the number to lead with.** It uses only the pour
schedule and site attributes — information MIG genuinely holds when the order is
placed — and still improves on current practice by 60%. It is also the configuration
that matches how the model would actually be deployed.

Configuration 2 is the realistic middle: a weather forecast is available one to two
weeks out, so weeks 1–2 of the horizon could use it while weeks 3–8 could not. If
the dashboard shows per-week forecasts, this is worth revisiting as a hybrid.

## Decision — frozen configuration

**Configuration 3 (schedule only) is adopted as the production model.**

It uses only information MIG holds when the order is placed, clears the 15% MAPE
target with room, and improves on current practice by 60%. Configurations 1 and 2
are retained as an ablation showing what better information would be worth.

In [201]:
# ============================================================================
# FROZEN CONFIGURATION - Step 4 model selection complete
# No further changes without re-running the validation comparison above.
# ============================================================================

FINAL_ESTIMATOR = "RandomForestRegressor(n_estimators=300, random_state=42)"
FINAL_FEATURES = SCHEDULE_COLS + SITE_COLS
FINAL_GRAIN = "weekly, per site, weeks labelled by Monday start"
FINAL_HORIZON = HORIZON_WEEKS
FINAL_TARGET = "y (= consumed_tonnes, summed to the week)"

frozen = pd.Series({
    "estimator": FINAL_ESTIMATOR,
    "features": ", ".join(FINAL_FEATURES),
    "n_features": len(FINAL_FEATURES),
    "grain": FINAL_GRAIN,
    "horizon": f"{FINAL_HORIZON} weeks",
    "target": FINAL_TARGET,
    "tuning": "none - default hyperparameters",
    "train window": f"2022-01 to {TRAIN_END_W}",
    "validation MAPE": f"{100*weather_comparison.loc['3. Schedule only','MAPE']:.2f}%",
    "validation RMSE": f"{weather_comparison.loc['3. Schedule only','RMSE']:.2f} t",
    "validation bias": f"{weather_comparison.loc['3. Schedule only','bias']:+.2f} t/site-week",
})

print("=" * 70)
print("FROZEN MODEL CONFIGURATION")
print("=" * 70)
for k, v in frozen.items():
    print(f"  {k:18s} {v}")
print("=" * 70)

======================================================================
FROZEN MODEL CONFIGURATION
======================================================================
  estimator          RandomForestRegressor(n_estimators=300, random_state=42)
  features           planned_pour_tonnes, planned_pour_next_7, planned_pour_next_14, days_since_planned_pour, silo_capacity, site_id, region, behavior
  n_features         8
  grain              weekly, per site, weeks labelled by Monday start
  horizon            8 weeks
  target             y (= consumed_tonnes, summed to the week)
  tuning             none - default hyperparameters
  train window       2022-01 to 2024-06-30
  validation MAPE    10.77%
  validation RMSE    30.48 t
  validation bias    +0.82 t/site-week
======================================================================

## Section close

Model selection for Step 4 is complete.

| | |
|---|---|
| **Model** | Random Forest, 300 trees, default hyperparameters |
| **Features** | 8 — pour schedule, site attributes |
| **Grain** | Weekly, per site |
| **Horizon** | 8 weeks |
| **Validation MAPE** | **10.8%** against a 15% target |
| **Validation RMSE** | 30.5 t against a mean of 166 t per site-week |
| **Bias** | +0.84 t per site-week |

Deliberately excluded, with reasons recorded above: weather (not knowable at the
8-week horizon), inventory state (start-of-week position, known 1 week ahead but not
8), lag and rolling features (no measurable benefit once the schedule is present),
and hyperparameter tuning (result already well inside target; skipping it keeps one
more decision off the validation set).

---

# FUTURE WORK — Weather Climatology

> **Not part of the frozen model.** The configuration was frozen and the hold-out
> scored before this test was run. Adding a feature now would mean re-scoring the
> test split, and the second figure would no longer be an unbiased estimate. This
> section measures the opportunity for v2; it does not change the reported result.

The frozen model drops weather entirely because rainfall is not knowable eight weeks
ahead. That conflated two different things:

| | knowable at order time? |
|---|---|
| the **rule** — rain above 15 mm abandons the pour | **yes** — learned from history, permanent |
| the **input** — will it rain on 12 November | no — needs a forecast |
| the **expected frequency** — how often November in the North blocks a pour | **yes** — climatology |

The rule was learned in notebook 03 and never expires. What varies is how often it
fires, and that frequency is predictable from season and region even when the specific
days are not. The frozen model currently carries **no weather signal at all**, so it
mis-forecasts wetter months systematically.

In [203]:
# Climatology estimated from TRAINING DATA ONLY - a historical average, not a forecast
fe_c = pd.read_parquet(settings.processed_dir / "operations_feature_engineered.parquet")
fe_c["date"] = pd.to_datetime(fe_c["date"])
fe_c["week"] = fe_c["date"].dt.to_period("W-SUN").dt.start_time
fe_c["month"] = fe_c["date"].dt.month
for col in ["region", "behavior"]:
    fe_c[col] = fe_c[col].astype(str)

climatology = (fe_c[fe_c.date <= TRAIN_END_W]
               .groupby(["region", "month"])
               .agg(clim_block_rate=("pour_blocked_rain", "mean"),
                    clim_rain=("rain_mm", "mean"),
                    clim_frost_rate=("frost", "mean"))
               .reset_index())

print("P(pour blocked by rain) by region and month, from training data:")
climatology.pivot(index="month", columns="region", values="clim_block_rate").round(3)

P(pour blocked by rain) by region and month, from training data:

region   East  North  South   West
month
1       0.048  0.039  0.047  0.062
2       0.055  0.043  0.049  0.068
3       0.059  0.075  0.041  0.032
4       0.051  0.052  0.041  0.053
5       0.048  0.054  0.053  0.024
6       0.049  0.059  0.062  0.042
7       0.054  0.048  0.051  0.028
8       0.044  0.059  0.057  0.048
9       0.054  0.039  0.048  0.038
10      0.032  0.054  0.029  0.040
11      0.056  0.044  0.056  0.058
12      0.048  0.038  0.041  0.065

In [204]:
AGG_C = {"y": "sum", "planned_pour_tonnes": "sum", "planned_pour_next_7": "last",
         "planned_pour_next_14": "last", "days_since_planned_pour": "first",
         "silo_capacity": "first", "region": "first", "behavior": "first",
         "pour_blocked_rain": "sum", "frost": "sum", "rain_mm": "mean",
         "avg_temp_c": "mean", "month": "first"}

wk_c = fe_c.groupby(["site_id", "week"], as_index=False).agg(AGG_C)
wk_c["n_days"] = fe_c.groupby(["site_id", "week"]).size().values
wk_c = wk_c[wk_c.n_days == 7].drop(columns="n_days")
wk_c = wk_c.merge(climatology, on=["region", "month"], how="left")
wk_c["clim_blocked_days"] = wk_c.clim_block_rate * 7
wk_c["clim_frost_days"] = wk_c.clim_frost_rate * 7
wk_c = wk_c.sort_values(["site_id", "week"]).reset_index(drop=True)

tr_c = wk_c[wk_c.week <= TRAIN_END_W]
va_c = (wk_c[(wk_c.week > TRAIN_END_W) & (wk_c.week <= VAL_END_W)]
        .groupby("site_id").head(HORIZON_WEEKS))
y_c = va_c.y.values
nz_c = y_c != 0

CATS_C = ["site_id", "region", "behavior"]
SCHED_C = ["planned_pour_tonnes", "planned_pour_next_7",
           "planned_pour_next_14", "days_since_planned_pour"]
SITE_C = ["silo_capacity"] + CATS_C
CLIM_C = ["clim_blocked_days", "clim_frost_days", "clim_rain"]
ACTUAL_C = ["pour_blocked_rain", "frost", "rain_mm", "avg_temp_c"]

print(f"train {len(tr_c):,} | val {len(va_c):,} site-weeks")

train 3,900 | val 240 site-weeks

In [205]:
def fit_clim(cols, label):
    pre = ColumnTransformer([
        ("num", "passthrough", [c for c in cols if c not in CATS_C]),
        ("cat", OneHotEncoder(handle_unknown="ignore"), CATS_C)])
    m = Pipeline([("preprocessor", pre),
                  ("model", RandomForestRegressor(n_estimators=300, random_state=42, n_jobs=-1))])
    m.fit(tr_c[cols], tr_c.y)
    pred = np.clip(m.predict(va_c[cols]), 0, None)
    return {"configuration": label, "n_features": len(cols),
            "MAPE": np.mean(np.abs((y_c[nz_c] - pred[nz_c]) / y_c[nz_c])),
            "RMSE": np.sqrt(np.mean((y_c - pred) ** 2)),
            "bias": (pred - y_c).mean()}


climate_test = pd.DataFrame([
    fit_clim(SCHED_C + SITE_C, "3. schedule only (frozen model)"),
    fit_clim(SCHED_C + SITE_C + CLIM_C, "3b. + climatology (knowable at order time)"),
    fit_clim(SCHED_C + SITE_C + ACTUAL_C, "1. + actual weather (not knowable)"),
]).set_index("configuration")

climate_test["MAPE %"] = (100 * climate_test.MAPE).round(2)
climate_test["knowable at order time"] = ["yes", "yes", "no"]
climate_test[["n_features", "MAPE %", "RMSE", "bias", "knowable at order time"]].round(3)

                                            n_features  MAPE %    RMSE   bias knowable at order time
configuration
3. schedule only (frozen model)                      8   10.77  30.462  0.955                    yes
3b. + climatology (knowable at order time)          11   10.05  28.966  1.136                    yes
1. + actual weather (not knowable)                  12    9.37  27.242  2.005                     no

In [206]:
base = climate_test.loc["3. schedule only (frozen model)", "MAPE"]
clim_m = climate_test.loc["3b. + climatology (knowable at order time)", "MAPE"]
perfect = climate_test.loc["1. + actual weather (not knowable)", "MAPE"]

print(f"gap between frozen model and perfect weather knowledge: "
      f"{100*(base - perfect):.2f} MAPE points")
print(f"recovered by climatology alone:                        "
      f"{100*(base - clim_m):.2f} points "
      f"({100*(base - clim_m)/(base - perfect):.0f}% of the gap)")
print(f"\nand it uses no forecast - only historical averages by region and month")

gap between frozen model and perfect weather knowledge: 1.39 MAPE points
recovered by climatology alone:                        0.72 points (52% of the gap)

and it uses no forecast - only historical averages by region and month